### DISCUSSION TITLE
Cannot get my deployments to work "csi volumes are not allowed to be used" - Openshift

### DISCUSSION THREAD

**Discussion by jonatiao** [Azure/secrets-store-csi-driver-provider-azure#1062] [Q&A]
Hello,
The following POD manifest works fine, it mounts the secret inside the POD:

```
---
apiVersion: v1
kind: Pod
metadata:
  name: srv-java-test
  namespace: myns
spec:
  containers:
  - name: srv-java-test
    image: abc/my-java-ms:latest
    ports:
      - containerPort: 8087
        protocol: TCP
    imagePullPolicy: Always
    volumeMounts:
    - name: secrets-store-inline
      mountPath: "/mnt/secrets-store"
      readOnly: true
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "mykv"
        nodePublishSecretRef:
          name: secrets-store-creds
```

But when I try to do the same using deployment: 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: srv-java-test
  namespace: myns
  labels:
    app: srv-java-test
spec:
  selector:
    matchLabels:
      app: srv-java-test
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: srv-java-test
    spec:
      containers:
        - name: srv-java-test
          image: abc/my-java-ms:latest
          ports:
            - containerPort: 8087
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "mykv"
            nodePublishSecretRef:
              name: secrets-store-creds
```
I get the following error in the replicaset:

```
0s          Warning   FailedCreate              replicaset/srv-java-test-7877bdd445         Error creating: pods "srv-java-test-7877bdd445-" is forbidden: unable to validate against any security context constraint: [spec.volumes[0]: Invalid value: "csi": csi volumes are not allowed to be used, provider "dynatrace-activegate": Forbidden: not usable by user or serviceaccount, provider "dynatrace-operator": Forbidden: not usable by user or serviceaccount, provider "dynatrace-webhook": Forbidden: not usable by user or serviceaccount, provider "dynatrace-dynakube-oneagent-unprivileged": Forbidden: not usable by user or serviceaccount, provider "dynatrace-dynakube-oneagent-privileged": Forbidden: not usable by user or serviceaccount, provider "nonroot": Forbidden: not usable by user or serviceaccount, provider "hostmount-anyuid": Forbidden: not usable by user or serviceaccount, provider "elasticsearch-scc": Forbidden: not usable by user or serviceaccount, provider "log-collector-scc": Forbidden: not usable by user or serviceaccount, provider "machine-api-termination-handler": Forbidden: not usable by user or serviceaccount, provider "hostnetwork": Forbidden: not usable by user or serviceaccount, provider "hostaccess": Forbidden: not usable by user or serviceaccount, provider "node-exporter": Forbidden: not usable by user or serviceaccount, provider "privileged": Forbidden: not usable by user or serviceaccount, provider "privileged-genevalogging": Forbidden: not usable by user or serviceaccount]
```

I'm not understanding what I'm doing wrong. Did I forget something during the install?

thx!
