### DISCUSSION TITLE
Can a cronjob use secret store provider to mount secrets

### DISCUSSION THREAD

**Discussion by oren-auth10tix** [Azure/secrets-store-csi-driver-provider-azure#1849] [Q&A]
I'm trying to set up a cronjob that uses secrets store same as it works for deployments.
When the cronjob is trigger, the pod is in status `CreateContainerConfigError` with event of: `Error: secret "xxx-service-secret" not found`

Has anyone managed to use cronjob with secretstoreprovider?

Here is cronjob template I use.

``` yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .name }}
spec:
  schedule: {{ .schedule }}
  successfulJobsHistoryLimit: {{ .successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .name }}
            image: "{{ $imageName }}:{{ $imageTag }}"
            imagePullPolicy: {{ .image.imagePullPolicy }}
            {{- if .command }}
            command: {{ toYaml .command | nindent 12 }}
            {{- end }}
            resources:
              limits:
                cpu: {{ .resources.limits.cpu }}
            ports:
            - containerPort: {{ .ports.containerPort }}
            envFrom:
              - secretRef:
                  name:  {{ $serviceName }}-secret
              - configMapRef:
                  name:  {{ $serviceName }}
            {{- if .volumeMounts }}
            volumeMounts:
              {{- toYaml .volumeMounts | nindent 12 }}
            {{- end }}
          restartPolicy: OnFailure
          {{- if .volumes }}
          volumes:
          {{- toYaml .volumes | nindent 8 }}
          {{- end }}
{{- end }}
{{- end }}
```
