### DISCUSSION TITLE
Tolerations not specified for both the daemon sets

### DISCUSSION THREAD

**Discussion by sabz90** [Azure/secrets-store-csi-driver-provider-azure#929] [General]
When I specify the tolerations in the helm chart values file :-

```
secrets-store-csi-driver:
  enableSecretRotation: true
  linux:
    tolerations:
    - key: "critical"
      operator: "Equal"
      value: "yes"
      effect: "NoSchedule"
```

I see the toleration applied only to daemonset **csi-secrets-store-provider-azure-secrets-store-csi-driver** and NOT **csi-secrets-store-provider-azure**

Is this expected? If yes, why is it not required for the latter daemon set process to run in all the nodes?
