### ISSUE TITLE
Could not use with Azure File Share for Volume mount

### ISSUE THREAD

**Issue by ssrahul96** [Azure/secrets-store-csi-driver-provider-azure#1009]
**Have you**

- [ ] Read [Troubleshooting Guide](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/troubleshooting/)
- [ ] Searched on [GitHub issues](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues) and [Discussions](https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions)

**What steps did you take and what happened:**

Need to store Azure File Share keys in KeyVault and use in AKS

Create AKS secret : https://learn.microsoft.com/en-us/azure/aks/azure-files-volume#create-a-kubernetes-secret
```bash
kubectl create secret generic azure-secret --from-literal=azurestorageaccountname=$AKS_PERS_STORAGE_ACCOUNT_NAME --from-literal=azurestorageaccountkey=$STORAGE_KEY
```

Tried the below `SecretProviderClass` for the secret `rahulfs-fs-secret`  but its not working

```yaml
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kv-secrets
spec:
  provider: azure
  secretObjects:
    - secretName: kv-secret-acr-halo-image-pull 
      type: kubernetes.io/dockerconfigjson
      data:
        - objectName: acr-halo-image-pull
          key: .dockerconfigjson
    - secretName: kv-secret-rahulfs
      type: Opaque
      data:
        - objectName: azurestorageaccountname
          key: myfs
        - objectName: azurestorageaccountkey
          key: rahulfs-fs-secret
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "uaid"
    keyvaultName: "iodevopskv"
    objects: |
      array:
        - |
          objectName: acr-halo-image-pull
          objectType: secret
        - |
          objectName: rahulfs-fs-secret
          objectType: secret
    tenantId: "tid"
```

Note: `acr-halo-image-pull` is working fine

Error :

```
MountVolume.MountDevice failed for volume "#kv-secret-rahulfs#shared#shared#itemoptix" : fetching NodeStageSecretRef itemoptix/kv-secret-rahulfs failed: kubernetes.io/csi: failed to find the secret kv-secret-rahulfs in the namespace itemoptix with error: secrets "kv-secret-rahulfs" not found 
```

```
failed to get data in spc itemoptix/kv-secrets for secret kv-secret-rahulfs, err: file matching objectName azurestorageaccountname not found in the pod
```

**What did you expect to happen:**

**Anything else you would like to add:**

**Which access mode did you use to access the Azure Key Vault instance:**
User Assigned Managed Identity

**Environment:**

- Secrets Store CSI Driver version: 1.2.3:
- Azure Key Vault provider version: 1.3.0:
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`):
```
Client Version: v1.25.3
Kustomize Version: v4.5.7
Server Version: v1.23.12
Nodes: v1.23.12
```
- Cluster type: (e.g. AKS, aks-engine, etc): AKS
- Installation method: ([Helm](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/getting-started/installation/#deployment-using-helm) , [Deployment yamls](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/getting-started/installation/#using-deployment-yamls), [AKS managed add-on](https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver)): Helm

**Comment by aramase** [comment]
@ssrahul96 The `objects` in `SecretProviderClass` don't match the `secretObjects` fields defined. Here are docs on how to use the sync feature: https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/configurations/sync-with-k8s-secrets/. You need to mount the object first and define the same in `secretObjects` of the file to sync as Kubernetes secret. 

`azurestorageaccountname` is not defined in `objects`.

**Comment by ssrahul96** [comment]
Thanks @aramase , was able to resolve

```yaml
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kv-secrets
spec:
  provider: azure
  secretObjects:
    - secretName: kv-secret-acr-halo-image-pull 
      type: kubernetes.io/dockerconfigjson
      data:
        - objectName: acr-halo-image-pull
          key: .dockerconfigjson
    - secretName: fs-aks-secret
      type: Opaque
      data:
        - objectName: fs-name
          key: azurestorageaccountname
        - objectName: fs-secret
          key: azurestorageaccountkey
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "uaid"
    keyvaultName: "kv"
    objects: |
      array:
        - |
          objectName: acr-halo-image-pull
          objectType: secret
        - |
          objectName: fs-secret
          objectType: secret
        - |
          objectName: fs-name
          objectType: secret
    tenantId: "tid"
```

the `fs-name` is fileshare name only, hence it may not be stored in keyvault, i tired hardcoding the value, but it started to looking for the object name matching it, 

any possible ways to achieve that?
