### ISSUE TITLE
Secret provider takes the Disabled secret value from KV

### ISSUE THREAD

**Issue by aliaksei-babuk** [Azure/secrets-store-csi-driver-provider-azure#1011]
What steps did you take and what happened:
For adding auto rotation we have added the next configuration row in to helm configuration:
parameters:
enableSecretRotation: "true"

What did you expect to happen:
We expect that the fresh one secret value will be automatically added to the secret

Anything else you would like to add:
We have test secret in Azure KeyVault. With next values:
test1 Disaibled
test2 Disaibled
test3 Disaibled
test4 Enabled
test5 Enabled - Latest

When I have added a change to the config, CSI starts randomly taking test4 and test3 values after secret manual deletion.
Which provider are you using:
Azure Key Vault

Environment:

Secrets Store CSI Driver version: (use the image tag): v1
Kubernetes version: (use kubectl version): 1.24.4

yaml:
```
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault
  namespace: test
spec:
  provider: azure
  secretObjects:
  - secretName: active-directory
    type: Opaque
    data:
    - objectName: "test"
      key: test
  parameters:
    usePodIdentity: "true"
    useVMManagedIdentity: "false"
    enableSecretRotation: "true"
    userAssignedIdentityID: "///"
    resourceGroup: "///"
    keyvaultName: "///"
    subscriptionId: "///"
    tenantId: "///"
    objects: |
      array:
        - |
          objectName: test
          objectType: secret
```
##################

```
kubectl describe SecretProviderClass azure-keyvault        
Name:         azure-keyvault
Namespace:    ///
Labels:       fluxcd.io/sync-gc-mark=sha256.F30w1v17DDRRURFQ4_vGZ7p6vi0dYejAjdL8BoJUFn4
Annotations:  fluxcd.io/sync-checksum: 088f0f1e0675b749ea86679e057a0aaa54cf2639
API Version:  secrets-store.csi.x-k8s.io/v1
Kind:         SecretProviderClass
Metadata:
  Creation Timestamp:  2022-09-01T22:43:43Z
  Generation:          5
  Managed Fields:
    API Version:  secrets-store.csi.x-k8s.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
        f:labels:
          .:
          f:fluxcd.io/sync-gc-mark:
      f:spec:
        .:
        f:parameters:
          .:
          f:keyvaultName:
          f:resourceGroup:
          f:subscriptionId:
          f:tenantId:
          f:usePodIdentity:
          f:useVMManagedIdentity:
          f:userAssignedIdentityID:
        f:provider:
    Manager:      kubectl
    Operation:    Update
    Time:         2022-09-01T22:43:43Z
    API Version:  secrets-store.csi.x-k8s.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        f:parameters:
          f:objects:
        f:secretObjects:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2022-10-28T12:32:54Z
    API Version:  secrets-store.csi.x-k8s.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:fluxcd.io/sync-checksum:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        f:parameters:
          f:enableSecretRotation:
    Manager:         kubectl-client-side-apply
    Operation:       Update
    Time:            2022-10-31T06:26:34Z
  Resource Version:  613782014
  UID:               ///
Spec:
  Parameters:
    Enable Secret Rotation:  true
    Keyvault Name:           ///
    Objects:                 array:
  - |
    objectName: test
    objectType: test
  
    Resource Group:             //
    Subscription Id:            ///
    Tenant Id:                  ///
    Use Pod Identity:           true
    Use VM Managed Identity:    false
    User Assigned Identity ID:  
  Provider:                     azure
  Secret Objects:
    Data:
      Key:          test
      Object Name:  test

Events:             <none>
```
