### ISSUE TITLE
Facing issue to set environment variable to reference a kubernetes secret

### ISSUE THREAD

**Issue by irisvivian1993** [Azure/secrets-store-csi-driver-provider-azure#1012]
For our project, we are using Azure Key Vault to encrypt password for mosquitto exporter container, the secret already exists in Key Vault. I am following this way - https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/configurations/set-env-var/  created a Kubernetes secret and reference it by setting an environment variable for the password. However, the container is not created after I deploy the chart, error message shows ```Error: secret "keyvaultsecret" not found```. In our case, secret already exists in Key Vault, then what value should we use for the ```secretName``` in the secretObjects? Here is the output of my ``` helm install --debug --dry-run```

<img width="1099" alt="image" src="https://user-images.githubusercontent.com/26945875/199403015-851afb11-f54a-4c16-8621-d4488d8ec3d0.png">

secret-provider-class.yaml
```
# Source: mosquitto/templates/secret-provider-class.yaml
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: "dms-eg-kv-0-mosquitto"
  labels:
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/instance: goodly-guppy
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: mosquitto-1.0.23-users-qianwenyan-dev-update.104
  annotations:
    app.kubernetes.io/app-version: 2.0.14
    app.kubernetes.io/chart-version: 1.0.23-users-qianwenyan-dev-update.104
spec:
  provider: azure
  secretObjects:
  - secretName: keyvaultsecret
    type: Opaque
    data:
      - key: BmsMqtt--Password
        objectName: BmsMqtt--Password
  parameters:
    usePodIdentity: "false"
    keyvaultName: dms-eg-kv-0
    objects:  |
      array:
        - |
          objectName: mqttpasswordmosquitto
          objectType: secret
          objectVersion: ""
        - |
          objectName: BmsMqtt--Password
          objectType: secret
          objectVersion: ""
    tenantId: 72f988bf-86f1-41af-91ab-2d7cd011db47
```

stateful-set.yaml
```
# Source: mosquitto/templates/stateful-set.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mqttbroker
  labels:
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/instance: goodly-guppy
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: mosquitto-1.0.23-users-qianwenyan-dev-update.104
  annotations:
    app.kubernetes.io/app-version: 2.0.14
    app.kubernetes.io/chart-version: 1.0.23-users-qianwenyan-dev-update.104
spec:
  replicas: 1
  serviceName: mqttbroker
  selector:
    matchLabels:
      app.kubernetes.io/name: mosquitto
      app.kubernetes.io/instance: goodly-guppy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mosquitto
        app.kubernetes.io/instance: goodly-guppy
      annotations:
        checksum/config: 27076bf29b9be07f644e30a7b25424597931a50e280fb692cbbfb00a70bc0ab
        checksum/secret: e4444bca2b66f0babfc6555a342196d34db23389732ab51d75782b55563821f
        prometheus.io/path: /metrics
        prometheus.io/port: "9234"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
    spec:
      imagePullSecrets:
        - name: edgegateway-acr-secret
      containers:
        - name: mosquittoexporter
          image: "dmsacr0.azurecr.io/mosquittoexporter:0.8.0"
          resources:
            limits:
              cpu: 50m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
          env:
            - name: MQTT_USER
              value: edgegatewayuser
            - name: MQTT_PASS
              valueFrom:
                secretKeyRef:
                  name: keyVaultSecret
                  key: BmsMqtt--Password
            - name: MQTT_CERT
              value:
            - name: MQTT_KEY
              value:
            - name: MQTT_CLIENT_ID
              value: mosquitto-exporter
            - name: BROKER_ENDPOINT
              value: mqttbroker:1883
        - name: mosquitto
          image: "dmsacr0.azurecr.io/mosquitto:2.0.14"
          imagePullPolicy: IfNotPresent
          ports:
            - name: mqtt
              containerPort: 1883
              protocol: TCP
            - name: websocket
              containerPort: 9090
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: websocket
            initialDelaySeconds: 5
            periodSeconds: 1
          readinessProbe:
            tcpSocket:
              port: websocket
            initialDelaySeconds: 3
            periodSeconds: 3
          resources:
            limits:
              cpu: 100m
              memory: 1024Mi
            requests:
              cpu: 50m
              memory: 512Mi
          volumeMounts:
            - name: config
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
            - name: data
              mountPath: /mosquitto/data
              subPath: "qianwen-ring0/mosquitto"
            - name: dms-eg-kv-0
              mountPath: /etc/keyvault
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: mqttbroker
        - name: dms-eg-kv-0
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "dms-eg-kv-0-mosquitto"
            nodePublishSecretRef:
              name: "edgegateway-keyvault-secret"
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
```

**Comment by aramase** [comment]
@irisvivian1993 In `SecretProviderClass` the secret name you're requesting for sync with the driver is `keyvaultsecret` but in the statefulset pod spec the secret ref name is `keyVaultSecret`. The second one is using camel case and doesn't match the secret name provided in `SecretProviderClass`

**Comment by irisvivian1993** [comment]
Sorry, forgot to update the latest version of stateful-set.yaml in the post. Attached updated version at here, both of them use ```keyvaultsecret``` but got error ```secret "keyvaultsecret" not found```.

```
# Source: mosquitto/templates/stateful-set.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mqttbroker
  labels:
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/instance: goodly-guppy
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: mosquitto-1.0.23-users-qianwenyan-dev-update.111
  annotations:
    app.kubernetes.io/app-version: 2.0.14
    app.kubernetes.io/chart-version: 1.0.23-users-qianwenyan-dev-update.111
spec:
  replicas: 1
  serviceName: mqttbroker
  selector:
    matchLabels:
      app.kubernetes.io/name: mosquitto
      app.kubernetes.io/instance: goodly-guppy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mosquitto
        app.kubernetes.io/instance: goodly-guppy
      annotations:
        checksum/config: d2733eafd6239ef5334c694df799b60cc1849ac8386b7997294f8ad7641cae6
        checksum/secret: bb28ae3f9177b94b542293f250da3bd58566bae5f6bb638a3731db41adef0d9
        prometheus.io/path: /metrics
        prometheus.io/port: "9234"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
    spec:
      imagePullSecrets:
        - name: edgegateway-acr-secret
      containers:
        - name: mosquittoexporter
          image: "dmsacr0.azurecr.io/mosquittoexporter:0.8.0"
          resources:
            limits:
              cpu: 50m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
          env:
            - name: MQTT_USER
              value: edgegatewayuser
            - name: MQTT_PASS
              valueFrom:
                secretKeyRef:
                  name: keyvaultsecret
                  key: BmsMqtt--Password
            - name: MQTT_CERT
              value:
            - name: MQTT_KEY
              value:
            - name: MQTT_CLIENT_ID
              value: mosquitto-exporter
            - name: BROKER_ENDPOINT
              value: mqttbroker:1883
        - name: mosquitto
          image: "dmsacr0.azurecr.io/mosquitto:2.0.14"
          imagePullPolicy: IfNotPresent
          ports:
            - name: mqtt
              containerPort: 1883
              protocol: TCP
            - name: websocket
              containerPort: 9090
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: websocket
            initialDelaySeconds: 5
            periodSeconds: 1
          readinessProbe:
            tcpSocket:
              port: websocket
            initialDelaySeconds: 3
            periodSeconds: 3
          resources:
            limits:
              cpu: 100m
              memory: 1024Mi
            requests:
              cpu: 50m
              memory: 512Mi
          volumeMounts:
            - name: config
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
            - name: data
              mountPath: /mosquitto/data
              subPath: "qianwen-ring0/mosquitto"
            - name: dms-eg-kv-0
              mountPath: /etc/keyvault
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: mqttbroker
        - name: dms-eg-kv-0
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "dms-eg-kv-0-mosquitto"
            nodePublishSecretRef:
              name: "edgegateway-keyvault-secret"
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
```
