### ISSUE TITLE
Provide example of syncing a kubernetes.io/basic-auth secret

### ISSUE THREAD

**Issue by carlin-q-scott** [Azure/secrets-store-csi-driver-provider-azure#1017]
**Describe the solution you'd like**
I'd like an example of how to store a kubernetes.io/basic-auth secret in AKV and sync it to k8s.

**Anything else you would like to add:**
I tried to implement this by setting the AKV value as a json file with the username and password properties, and I set the content type to `application/x-json` based on the implementation from [akv2k8s](https://github.com/SparebankenVest/azure-key-vault-to-kubernetes). It synced as the full json file to both the username and password properties.

Here's my SecretProviderClass that I thought would work:
```yaml
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-sync
spec:
  provider: azure
  secretObjects:
  - secretName: keycloak-admin
    type: kubernetes.io/basic-auth
    data:
    - key: username
      objectName: account
    - key: password
      objectName: account
  parameters:
    objects: |
      array:
        - |
          objectName: account
          objectType: secret
```

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
- Azure Key Vault provider version: (use the image tag):
- Kubernetes version: (use `kubectl version`):
- Cluster type: (e.g. AKS, aks-engine, etc): AKS
