### ISSUE TITLE
Failed to parse workload identity tokens, service account tokens not found, when using Workload Identity

### ISSUE THREAD

**Issue by lalitmsft** [Azure/secrets-store-csi-driver-provider-azure#1022]
**Errror**
```
error: failed to parse workload identity tokens, error: service account tokens not found
```

**What steps did you take and what happened:**
####Service Account
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: ********-fc0d-4a2a-b712-************
    azure.workload.identity/tenant-id= ********-7f24-47e8-a7d3-**********
  labels:
    azure.workload.identity/use: "true"
  name: workload-identity-sa
  namespace: default
```

####SecretProvider Class
```yaml
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-oidc
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "******-4a2a-b712-**********"
    keyvaultName: "oidc-kv-**********"
    objects: |
      array:
        - |
          objectName: my-secret              
          objectType: secret
    tenantId: ********-7f24-47e8-a7d3-**********
```

####POD
```yaml
kind: Pod
apiVersion: v1
metadata:
  name: busybox-secrets-store-inline-oidc
spec:
  serviceAccountName: workload-identity-sa
  containers:
  - name: busybox
    image: k8s.gcr.io/e2e-test-images/busybox:1.29
    command:
      - "/bin/sleep"
      - "10000"
    volumeMounts:
    - name: secrets-store-inline
      mountPath: "/mnt/secrets-store"
      readOnly: true
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "azure-kvname-oidc"
```

#####We added the get policy for secrets from Key vault
```bash
az keyvault set-policy --name "${KEYVAULT_NAME}" --secret-permissions get --spn "${USER_ASSIGNED_IDENTITY_CLIENT_ID}"
```

#####Created Federated credential between the Service Account and User assigned Managed Identity
```bash
az identity federated-credential create --name "kubernetes-federated-credential-sc" --identity-name "${USER_ASSIGNED_IDENTITY_NAME}" --resource-group "${RESOURCE_GROUP}" --issuer "${SERVICE_ACCOUNT_ISSUER}" --subject "system:serviceaccount:${SERVICE_ACCOUNT_NAMESPACE}:${SERVICE_ACCOUNT_NAME}"
```
**What did you expect to happen:**
The secrets to be fetched from keyvault and mounted to the correct path

**Anything else you would like to add:**
Workload Identity without CSI driver is working properly in the cluster

**Which access mode did you use to access the Azure Key Vault instance:**
Workload Identity

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): latest
- Azure Key Vault provider version: (use the image tag): latest
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`):
  - Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.8", GitCommit:"83d00b7cbf10e530d1d4b2403f22413220c37621", GitTreeState:"clean", BuildDate:"2022-11-09T19:50:11Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/amd64"}
- Cluster type: (e.g. AKS, aks-engine, etc): AKS
- Installation method: ([Helm](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/getting-started/installation/#deployment-using-helm) , [Deployment yamls](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/getting-started/installation/#using-deployment-yamls), [AKS managed add-on](https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver)): Helm

**Error in the Cluster**
```text
 Warning  FailedMount  21m (x115 over 22h)   kubelet  Unable to attach or mount volumes: unmounted volumes=[secrets-store-inline], unattached volumes=[kube-api-access-w6qrd secrets-store-inline]: timed out waiting for the condition
  Warning  FailedMount  7m2s (x657 over 22h)  kubelet  MountVolume.SetUp failed for volume "secrets-store-inline" : rpc error: code = Unknown desc = failed to mount secrets store objects for pod default/busybox-secrets-store-inline-oidc, err: rpc error: code = Unknown desc = failed to mount objects, error: failed to parse workload identity tokens, error: service account tokens not found
  Warning  FailedMount  77s (x469 over 22h)   kubelet  Unable to attach or mount volumes: unmounted volumes=[secrets-store-inline], unattached volumes=[secrets-store-inline kube-api-access-w6qrd]: timed out waiting for the condition
```

Is there some setup missing or do we have some known issue with workload Identity.
