### ISSUE TITLE
Azure Key Vault CSI Driver Add-on don't rotate secrets when i update them in Key Vault

### ISSUE THREAD

**Issue by coffee-seeds** [Azure/secrets-store-csi-driver-provider-azure#1065]
**Have you**

- [x] Read [Troubleshooting Guide](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/troubleshooting/)
- [x] Searched on [GitHub issues](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues) and [Discussions](https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions)

**What steps did you take and what happened:**

I renovated in Azure Key Vault my tls certificate but the Secret is not updated with this information, This is my secreprovider.yaml:

```
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.tls.name }}-tls                                              # SecretProviderClass resource name. This is referenced in the volumes section in the deployment
  namespace: {{ .namespace }}
  labels:
  {{ include "api-bootstrap.labels" $ | nindent 4 }}
spec:
  provider: azure                                                               # Needs to be set to azure as its our only provider      
  secretObjects:
  - secretName: {{ .Values.tls.secretName }}                                    # Name of the Kubernetes Secret object that will be generated 
    type: kubernetes.io/tls                                                     # Type of the Kubernetes Secret object e.g. Opaque, kubernetes.io/tls
    data:
    - objectName: {{ .Values.tls.objectName }}                                  # Certificate hosted in your Azure Key Vault (NAME MUST MATCH)  
      key: tls.key                                                              # This can be called what you need, this is to reference this object in the secret.
    - objectName: {{ .Values.tls.objectName }}                                  # Set to the name of your certificate hosted inside your key vault   
      key: tls.crt
  parameters:                                                                   # SecretProviderClass credentials (stated in the values file)
    {{ with .Values.tls.parameters }}
    {{ toYaml . | nindent 4 }}
    {{ end }}
    objects:  |
      array:
        - |
          objectName: {{ .Values.tls.objectName }}
          objectType: secret      
````

And this it's my deployment:

````
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api-bootstrap.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "api-bootstrap.labels" . | indent 4 }}
  annotations:
  {{- with .Values.deployment.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      namespace: {{ .Release.Namespace }}
      labels:
{{ include "gfps-bootstrap.labels" . | indent 8 }}
      {{- if .Values.deployment.podAnnotations }}
      annotations:
      {{- with .Values.deployment.podAnnotations }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        tty: true
        volumeMounts:
          - mountPath: {{ .Values.tls.volumepath }}/secrets-store
            name: {{ .Values.tls.volumename }}
            readOnly: true
          - mountPath: {{ .Values.api.volumepath }}/secrets-store
            name: {{ .Values.api.volumename }}
            readOnly: true
          {{- range .Values.databases }}
          - mountPath: {{ .volumepath }}/secrets-store
            name: {{ .volumename }}
            readOnly: true
          {{- end }}
        {{- if .Values.ldap.enabled }}
          - mountPath: {{ .Values.ldap.volumepath }}/secrets-store
            name: {{ .Values.ldap.volumename }}
            readOnly: true
        {{- end }}
        ports:
        - containerPort: 22
      volumes:                                                                               # Secrets created by SecretProviderClass are mounted as volumes in the deployment
      - name: {{ .Values.tls.volumename }}
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: {{ .Values.tls.name }}-tls                                  # tls SecretProviderClass name
      - name: {{ .Values.api.volumename }}
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: {{ .Values.api.name }}-csi                                  # api SecretProviderClass name
      {{- range .Values.databases }}
      - name: {{ .volumename }}
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: {{ .name }}-csi                                             # database SecretProviderClass name
      {{- end }}
      {{- if .Values.ldap.enabled }}
      - name: {{ .Values.ldap.volumename }}
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: {{ .Values.ldap.name }}-csi                                 # LDAP SecretProviderClass name
      {{- end }}
      imagePullSecrets:
        {{ toYaml .Values.deployment.imagePullSecrets }}
  strategy:
    {{- toYaml .Values.deployment.strategy | nindent 4 }}

````

Also the aks addons are enabled:

````
az aks show -g XXXX -n XXXX --query 'addonProfiles.azureKeyvaultSecretsProvider'
The behavior of this command has been altered by the following extension: aks-preview
{
  "config": {
    "enableSecretRotation": "true",
    "rotationPollInterval": "5m"
  },

````

**What did you expect to happen:**

When I deployed the secretproviderclass they took all the information correctly from azure key vault, i.e. the connectivity between azure key vault and kubernetes is correct.

The problem is when I update a certificate in azure key vault, the secretproviderclass are not able to update the secret with the new information.

obviously if I delete the secretsproviderclass and secrets and redeploy, the secret will come with the updated certificate, but  the idea is that I don't have to touch that, but once I update the certificate in azure key vault the secret is automatically updated.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Which access mode did you use to access the Azure Key Vault instance:**
[e.g. Service Principal, Pod Identity, User Assigned Managed Identity, System Assigned Managed Identity]

User Assigned Managed Identity

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): mcr.microsoft.com/oss/kubernetes-csi/csi-node-driver-registrar:v2.5.1
- Azure Key Vault provider version: (use the image tag): I don't know hot to get it
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`): v1.23.12
- Cluster type: (e.g. AKS, aks-engine, etc): AKS
- Installation method: ([Helm](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/getting-started/installation/#deployment-using-helm) , [Deployment yamls](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/getting-started/installation/#using-deployment-yamls), [AKS managed add-on](https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver)): AKS managed add-on
