### ISSUE TITLE
multiple key vault support

### ISSUE THREAD

**Issue by davildaran** [Azure/secrets-store-csi-driver-provider-azure#1088]
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

The ability to specify multiple Azure Key Vaults/SecretProviderClasses for the same service in the same namespace.

E.g. `serviceA/dev/secret-provider-class.yaml`
```
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secrets
  namespace: serviceA
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ...
    keyvaultName: serviceA-keyvault1
    cloudName: ""
    tenantId: ...
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secrets
  namespace: serviceA
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ...
    keyvaultName: serviceA-keyvaultB
    cloudName: ""
    tenantId: ...
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Looked into a few ways of trying to specify this. `kustomize build path/to/dev/` yields valid yaml but overrides to just (1) single `SecretProviderClass` definition. 

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): `secrets-store.csi.x-k8s.io/v1`
- Azure Key Vault provider version: (use the image tag): 
- Kubernetes version: (use `kubectl version`): `1.26`
- Cluster type: (e.g. AKS, aks-engine, etc): AKS
