### ISSUE TITLE
Deployment fails when trying to create a secret into a different namespace

### ISSUE THREAD

**Issue by ReySka91** [Azure/secrets-store-csi-driver-provider-azure#1118]
I'm trying to deploy an Ingress Nginx deployment into 'ingress' namespace. In the deployment, I'm using SecretProviderClass in which I have configured the synced key vault secret to be created in the 'maxx-dev' namespace'. Service account linked to deployment has 'secret create' permissions to the 'maxx-dev' namespace. 

When creating the deployment, I get a timeout error related to the secret creation: 
![image](https://user-images.githubusercontent.com/9673002/231141377-5936af32-b195-4732-893a-87bbef0a1c65.png)

When I configure the secret to be created in the same namespace 'ingrss' as the ingress nginx deployment, everything works fine.

Here's my relevant code:

Ingress Nginx deployment:
```
apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
   ...
    labels:
   ...
    name: ingress-nginx-controller
    namespace: ingress
  spec:
    replicas: 2
   ...
    template:
     ...
      spec:
        containers:
          name: controller
          ...
          volumeMounts:
         ...
          - mountPath: /mnt/secrets-store
            name: ingress-tls
            readOnly: true
       ...
        serviceAccount: ingress-controller
        serviceAccountName: ingress-controller
        volumes:
        ...
        - csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: ingress-tls
          name: ingress-tls
``` 

SecretProviderClass:
```
apiVersion: secrets-store.csi.x-k8s.io/v1
  kind: SecretProviderClass
  metadata:
    name: ingress-tls
    namespace: ingress
  spec:
    parameters:
      clientID: fb6b...
      keyvaultName: maxx...
      objects: "array:\r\n  - |\r\n    objectName: wildcard-certificate\r\n    objectType:
        secret\r\n        \r\n"
      tenantId: f098...
      usePodIdentity: "false"
      useVMManagedIdentity: "false"
    provider: azure
    secretObjects:
    - data:
      - key: tls.key
        objectName: wildcard-certificate
      - key: tls.crt
        objectName: wildcard-certificate
      secretName: maxx-dev/wildcard-certificate
      type: kubernetes.io/tls
```

Am I doing something wrong or is it even possible to use SecretProviderClass to create secrets in different namespaces? This important as these secrets are going to be used by ingress rule resources that are in the maxx-dev namespace with all of our applications
