### ISSUE TITLE
Unable to read azure keyvault secrets as environment  variable into ARO

### ISSUE THREAD

**Issue by san6789** [Azure/secrets-store-csi-driver-provider-azure#1128]
We are trying to access azure keyvault secrets with ARO pod as environment variables. We have installed respective drivers as well. 

our secret provider class:
```
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
   name: azure-test
spec:
   provider: azure
   secretObjects:
     - data:
         - key: azure-test-read
           objectName: test-123
       secretName: azure-test-read
       type: Opaque 
   parameters:
     usePodIdentity: "false"
     useVMManagedIdentity: "false"
     userAssignedIdentityID: ""
     keyvaultName: "AZP-test-KV"
     objects: |
       array:
         - |
           objectName: test-123
           objectType: secret
           objectVersion: ""
     tenantId: xxxxxx-xxx-4xxxx-xxx-xxxx
```

$ oc apply -f SecretProviderClass.yaml 
secretproviderclass.secrets-store.csi.x-k8s.io/azure-test unchanged

we have deployed the pod as well:

pod:
```
kind: Pod
apiVersion: v1
metadata:
   name: kv-access-sample-pod-3
spec:
   serviceAccountName: test-azurekeyvault
   containers:
   - name: ubuntu
     image:-ubuntu:20.04
     command: ['sleep', 'infinity']
     env:
       - name: test
         valueFrom:
           secretKeyRef:
             key: azure-test-read
             name: azure-test-read
```
while checking the event of the openshift UI:
PodP[kv-access-sample-pod-3](https://cxxxxxx/k8s/ns/xxxxx/pods/kv-access-sample-pod-3)
NamespaceNS[ocpxxxxx](https://xxxxxxxx/k8s/cluster/namespaces/xxxxx)
Just now
Generated from kubelet on nebula-f7jvg-worker-westeurope2-zxlrm
4 times in the last 0 minutes
**Error: secret "azure-test-read" not found**
I am getting this error.

like its unable to create the secret  in the ARO secret manager while deploying the secret provider class.

 Cluster type: ARO
