### ISSUE TITLE
`clientID` property for workload identity is case sensitive

### ISSUE THREAD

**Issue by afscrome** [Azure/secrets-store-csi-driver-provider-azure#1157]
**Have you**

- [X] Read [Troubleshooting Guide](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/troubleshooting/)
- [X] Searched on [GitHub issues](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues) and [Discussions](https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions)

**What steps did you take and what happened:**
When setting up workload identity, you have to provide a `clientID` field on `SecretProviderClass`.  If you provide this field as `clientId` instead (lower case `d`), you end up with a cryptic error when starting a pod using the secret reference.

> MountVolume.SetUp failed for volume "my-secrets" : rpc error: code = Unknown desc = failed to mount secrets store objects for pod my/my-7441ba8468-aqjgm, err: rpc error: code = Unknown desc = failed to mount objects, error: failed to create auth config, error: failed to get credentials, nodePublishSecretRef secret is not set

**What did you expect to happen:**
I expected the casing `clientId` to work since that is the same casing used for `tenantId`.  Or at the very least a clearer error message that points you in the direction of a missing `clientId` rather than an unhelpful `nodePublishSecretRef secret is not set`.

**Anything else you would like to add:**
Example manifests reproducing the issue
```
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: my-secrets
spec:
  provider: azure
  secretObjects: # ...
  parameters:
    usePodIdentity: 'false'
    useVmIdentity: 'false'
    clientId: {{ .Values.clientId }}
    keyvaultName: {{ .Values.keyVault.name }}
    tenantId: {{ .Values.tenantId }}
    cloudName: AzurePublicCloud
    objects: # ...
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my
spec:
  template:
    metadata:
        azure.workload.identity/use: "true"
    spec:
      automountServiceAccountToken: false
      serviceAccountName: azure-workload-identity
      containers:
        - name: my
          image: '{{ .Values.image }}'
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: my-secrets
          volumeMounts:
            - name: my-secrets
              readOnly: true
              mountPath: /mnt/akv
      volumes:
        - name: my-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: my-secrets
```

**Which access mode did you use to access the Azure Key Vault instance:**
Workload Identity

**Environment:**

- Secrets Store CSI Driver version: mcr.microsoft.com/oss/kubernetes-csi/csi-node-driver-registrar:v2.6.2
- Azure Key Vault provider version: mcr.microsoft.com/oss/azure/secrets-store/provider-azure:v1.4.0
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`): 1.24.9
- Cluster type: AKS
- Installation method: AKS managed addon
