### ISSUE TITLE
Errorpkcs12: expected exactly two safe bags in PFX PDU

### ISSUE THREAD

**Issue by garethmorris78** [Azure/secrets-store-csi-driver-provider-azure#116]
**What steps did you take and what happened:**
Setup provider as per https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/README.md

Used Helm to install with no issues. driver deployed on both windows and linux nodes. 
Added AKS managed identity to the key vault permissions ( GET for key, cert and secret) 

Created a new SAN certificate ( using Active Directory Certificate Authority  ). 

Exported as PFX format and Imported into Azure KeyVault as a certificate using Powershell Import-AzKeyVaultCertificate cmdlet

Created a new SecretProviderClass

```
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: mykeyvault
spec:
  provider: azure
  secretObjects:                                
secret objects
  - secretName: ingress-tls-csi
    type: kubernetes.io/tls
    data: 
     - objectName: mycert
       key: tls.key
     - objectName: mycert
       key: tls.crt
  parameters:
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "xxxxxxxxxxxxxxxxx" 
    keyvaultName: "mykeyvault" 
    objects: |
      array:
        - |
          objectName: mycert
          objectType: secret
          
    resourceGroup: "mygroup"
    subscriptionId: "xxxxx"
    tenantId: "xxxxxxx"
```
Created new NGINX ingress deployment with a volume mount

```
volumes:
    - name: mykv
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "mykeyvault"

```

Error from CSI driver pod secure-store

time="2020-06-01T13:40:43Z" level=error msg="error invoking provider, err: exit status 1, output: time=\"2020-06-01T13:40:43Z\" level=fatal msg=\"[error] : failed to get objectType:secret, objectName:mycert, objectVersion:: pkcs12: expected exactly two safe bags in the PFX PDU\"\n

**What did you expect to happen:**

A new kubernetes tls secret created and a volume mounted in nginx ingress controller pod. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Which access mode did you use to access the Azure Key Vault instance:**
User Assigned Managed Identity

**Environment:**

- Secrets Store CSI Driver version: 
- Azure Key Vault provider version: (use the image tag):0.0.6
- Kubernetes version: (use `kubectl version`): 1.16.9
- Cluster type: (e.g. AKS, aks-engine, etc): AKS
