### ISSUE TITLE
How to add label to the synced secret?

### ISSUE THREAD

**Issue by zalyoung** [Azure/secrets-store-csi-driver-provider-azure#117]
**Describe the solution you'd like**
We are using spring-cloud-kubernetes library to load the values from synced secrets in k8s. But  it needs the secret label to get the specified/correct secret.

**Anything else you would like to add:**
The secretObjects doesn't have any  label related parameters
```
  secretObjects:                              
  - data:
    - key: username                          
      objectName: foo1                        
    secretName: foosecret   
    type: Opaque 
```

**Environment:**

- Secrets Store CSI Driver version:  csi-node-driver-registrar:v1.2.0 , secrets-store-csi:v0.0.11
- Azure Key Vault provider version: 0.0.6
- Kubernetes version: v1.16.9
- Cluster type: AKS
