### ISSUE TITLE
Secret not getting synced to AKS cluster

### ISSUE THREAD

**Issue by allwritesri** [Azure/secrets-store-csi-driver-provider-azure#1176]
**Have you**

- [*] Read [Troubleshooting Guide](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/troubleshooting/)
- [*] Searched on [GitHub issues](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues) and [Discussions](https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions)

**What steps did you take and what happened:**
This is the secretproviderclass:
```
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ic-rei-kv-spc
spec:
  secretObjects:
    - secretName: testcloud
      type: kubernetes.io/tls
      data: 
      - objectName: wildcard-rei-testcloud-com
        key: tls.key
      - objectName: wildcard-rei-testcloud-com
        key: tls.crt
  parameters:
    keyvaultName: ic-e2-kv-qa
    objects: |
        array:
          - |
            objectName: wildcard-rei-testcloud-com
            objectType: secret
    tenantId: {{tenantId}}
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{userAssignedIdentityID}}
  provider: azure
 ``` 

Upon mounting on the pod with the path /mnt/secrets-store I am able to see the certificate mounted.

However when doing describe on pod, I am seeing below exception:

```
 Warning  FailedToCreateSecret  2m16s (x23 over 74m)  csi-secrets-store-controller  timed out waiting for the condition
```

I verified that the cluster has both clusterrole and clusterbindingrole related to secret syncing.

```
admin                                                                  2022-06-08T13:58:22Z
aks-secretproviderclasses-admin-role                                   2022-09-29T17:08:08Z
aks-secretproviderclasses-role                                         2022-09-29T17:08:04Z
aks-secretproviderclasses-viewer-role                                  2022-09-29T17:08:09Z
aks-secretprovidersyncing-role                                         2022-09-29T17:08:06Z
aks-secretprovidertokenrequest-role                                    2022-09-29T17:08:10Z
```
```
aks-secretprovidersyncing-rolebinding                  ClusterRole/aks-secretprovidersyncing-role                                         228d
```
**What did you expect to happen:**
I expect the secret to be created.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Which access mode did you use to access the Azure Key Vault instance:**
 User Assigned Managed Identity

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): v1.3.0.3
- Azure Key Vault provider version: (use the image tag):v1.4.0
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`):  v1.24.3
- Cluster type: (e.g. AKS, aks-engine, etc): AKS
- Installation method: ([Helm](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/getting-started/installation/#deployment-using-helm) , [Deployment yamls](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/getting-started/installation/#using-deployment-yamls), [AKS managed add-on](https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver)): NON-Helm
