### ISSUE TITLE
SecretObjects not creating k8s secret

### ISSUE THREAD

**Issue by sainipankaj90k** [Azure/secrets-store-csi-driver-provider-azure#1198]
**Have you**

- [x] Read [Troubleshooting Guide](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/troubleshooting/)
- [x] Searched on [GitHub issues](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues) and [Discussions](https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions)

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Installed secret-store csi driver using below helm commands:

helm repo add secrets-store-csi-driver https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
helm install csi-secrets-store secrets-store-csi-driver/secrets-store-csi-driver --namespace kube-system

post that deployed below yaml (the mounted volume had the secrets but not the k8s secret)

``` yaml

---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-sync2
spec:
  provider: azure
  secretObjects:                                  # [OPTIONAL] SecretObject defines the desired state of synced K8s secret objects
    - secretName: foosecret
      type: Opaque
      labels:
        environment: "test"
      data:
        - objectName: secretalias                 # name of the mounted content to sync. this could be the object name or object alias. The mount is mandatory for the content to be synced as Kubernetes secret.
          key: username
  parameters:
    usePodIdentity: "false"                       # [OPTIONAL] if not provided, will default to "false"
    useVMManagedIdentity: "true"
    keyvaultName: "ptkv050623"                        # the name of the KeyVault
    objects: |
      array:
        - |
          objectName: secret1
          objectType: secret                      # object types: secret, key or cert
          objectAlias: secretalias
        - |
          objectName: my-key
          objectType: key
        - |
          objectName: certpkcs1
          objectType: cert
        - |
          objectName: certpem1
          objectType: cert
        - |
          objectName: certpkcs1
          objectType: secret
          objectAlias: certpkcs1notls
        - |
          objectName: certpem1
          objectType: secret
          objectAlias: certpem1notls
    tenantId: "xxxxx"                               # the tenant ID of the KeyVault

    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deployment2
  labels:
    app: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: busybox
          image: registry.k8s.io/e2e-test-images/busybox:1.29-4
          command:
            - "/bin/sleep"
            - "10000"
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-sync2"
```

**What did you expect to happen:**
The secret 'foosecret' to be present in default namespace. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Which access mode did you use to access the Azure Key Vault instance:**
[e.g. Service Principal, Pod Identity, User Assigned Managed Identity, System Assigned Managed Identity]

    **usePodIdentity: "false"**                       # [OPTIONAL] if not provided, will default to "false"
    **useVMManagedIdentity: "true"**

**Environment:**
TEST

- Secrets Store CSI Driver version: (use the image tag):
      mcr.microsoft.com/oss/azure/secrets-store/provider-azure:v1.4.1
- Azure Key Vault provider version: (use the image tag):
      mcr.microsoft.com/oss/azure/secrets-store/provider-azure:v1.4.1
      [
	{
		"image": "mcr.microsoft.com/oss/kubernetes-csi/azuredisk-csi:v1.26.4"
	},
	{
		"image": "mcr.microsoft.com/oss/kubernetes-csi/livenessprobe:v2.10.0"
	},
	{
		"image": "mcr.microsoft.com/oss/kubernetes-csi/csi-node-driver-registrar:v2.8.0"
	}
    ]

- **Kubernetes version:** (use `kubectl version` and `kubectl get nodes -o wide`):
         **kubectl version**
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:57:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.10", GitCommit:"4cb79fde82e99937e74e1248902ad1952d75f998", GitTreeState:"clean", BuildDate:"2023-05-19T00:02:33Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}

**kubectl get nodes -o wide**
NAME                                STATUS   ROLES   AGE   VERSION    INTERNAL-IP    EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
aks-agentpool-16237003-vmss000000   Ready    agent   45h   v1.24.10   10.224.0.113   <none>        Ubuntu 18.04.6 LTS   5.4.0-1109-azure   containerd://1.7.1+azure-1
aks-agentpool-16237003-vmss000001   Ready    agent   45h   v1.24.10   10.224.0.222   <none>        Ubuntu 18.04.6 LTS   5.4.0-1109-azure   containerd://1.7.1+azure-1
aks-userpool-16237003-vmss000000    Ready    agent   45h   v1.24.10   10.224.1.75    <none>        Ubuntu 18.04.6 LTS   5.4.0-1109-azure   containerd://1.7.1+azure-1
aks-userpool-16237003-vmss000001    Ready    agent   45h   v1.24.10   10.224.0.4     <none>        Ubuntu 18.04.6 LTS   5.4.0-1109-azure   containerd://1.7.1+azure-1

**- Cluster type: (e.g. AKS, aks-engine, etc):**
AKS

**- Installation method:** ([Helm](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/getting-started/installation/#deployment-using-helm) , [Deployment yamls](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/getting-started/installation/#using-deployment-yamls), [AKS managed add-on](https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver)):
using helm:

helm repo add secrets-store-csi-driver https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
helm install csi-secrets-store secrets-store-csi-driver/secrets-store-csi-driver --namespace kube-system

**Comment by eduardogoncalves** [comment]
I'm facing the same issue. If I can see the variables from Azure Key Vault with `kubectl exec busybox-secrets-store-inline -- cat /mnt/secrets-store/secret1` command, but when I add env reference, it doesn't create the secret. I'm following: https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/configurations/set-env-var/

**Comment by nilekhc** [comment]
@sainipankaj90k Have turned on sync secrets while installing via helm?

https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/configurations/sync-with-k8s-secrets/

**Comment by sainipankaj90k** [comment]
After setting 'syncSecret.enabled' to 'true', I was able to see most of the secrets to sync.

Though, right now I can see secrets got created for type 'secret' and 'keys'. But secret for certs are not getting created.

@nilekhc / @eduardogoncalves , do you see I'm missing something here? 


Refer below yaml :
``` yaml
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-sync2
spec:
  parameters:
    keyvaultName: ptkv050623
    objects: |
      array:
        - |
          objectName: secret1
          objectType: secret                      # object types: secret, key or cert
          objectAlias: secretalias
        - |
          objectName: my-key
          objectType: key
        - |
          objectName: certpkcs1
          objectType: cert
        - |
          objectName: certpem1
          objectType: cert
        - |
          objectName: certpkcs1
          objectType: secret
          objectAlias: certpkcs1notls
        - |
          objectName: certpem1
          objectType: secret
          objectAlias: certpem1notls2
    tenantId: 72f988bf-86f1-41af-91ab-2d7cd011db47
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  provider: azure
  secretObjects:
  - data:
    - key: username
      objectName: secretalias
    secretName: foosecret
    type: secret
  - data:
    - key: signing-key
      objectName: my-key
    secretName: foomy-key
    type: key
  - data:
    - objectName: certpem1
    secretName: foopem1
    type: kubernetes.io/tls
  - data:
    - objectName: certpkcs1
    secretName: foocertpkcs1
    type: kubernetes.io/tls
  - data:
    - objectName: certpem1notls2
    secretName: foopem1notls
    type: kubernetes.io/tls
  - data:
    - objectName: certpkcs1notls
    secretName: foocertpkcs1notls
    type: kubernetes.io/tls

```
