### ISSUE TITLE
Pods restart every time the chart is deployed

### ISSUE THREAD

**Issue by doug-papenthien-by** [Azure/secrets-store-csi-driver-provider-azure#121]
**What steps did you take and what happened:**
As part of integrating this module with our CI/CD pipeline, we're configuring it to do a helm deployment of the CSI driver chart every time the pipeline is run.  However, I've noticed that the pods restart every single time this is done even when nothing about the configuration changes.

Is there a good reason for this?  At least one of the pods can take several minutes to terminate and restart.

**What did you expect to happen:**
Pods should only restart if changes are required to the deployment.

**Which access mode did you use to access the Azure Key Vault instance:**
Service Principal

**Environment:**
- Secrets Store CSI Driver version: v0.0.11
- Azure Key Vault provider version: 0.0.6
- Kubernetes version: 1.16.6
- Cluster type: AKS

**Comment by aramase** [comment]
@doug-papenthien-by How are you redeploying every time in the CI? If the chart already exists and is redeployed, then the helm revision # changes every time. Since helm revision # is used as a label in all the daemonsets, k8s detects changes in the daemonset metadata and restarts all the pods. 

```
  labels:
    app: secrets-store-csi-driver
    app.kubernetes.io/managed-by: Helm
    chart: secrets-store-csi-driver
    chartVersion: 0.0.11
    heritage: Helm
    release: csi
    revision: "2"
```
