### ISSUE TITLE
Kubectl patch command for faster secret addition

### ISSUE THREAD

**Issue by abudavis** [Azure/secrets-store-csi-driver-provider-azure#1214]
Install method: Using helm
Platform: Openshift 4.10.30
CSI driver 1.3.0

This is not really a bug but we need some assistance in creating a kubectl/oc patch command to inject a new secret1 array objects into the existing yaml structure shown below for our automation whenever a new secret is added to Azure Key Vault:

```
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-test
  namespace: abc
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    keyvaultName: "test-vault"
    objects: |
      array:
        - |
          objectName: secret1
          objectType: secret
          objectVersion: ""
    tenantId: "dxxxx"
  secretObjects:
    - secretName: secret1
      type: Opaque
      data:
        - objectName: secret1
          key: json
```
