### ISSUE TITLE
Unable to mount secret when using workload identity

### ISSUE THREAD

**Issue by Jamess-Lucass** [Azure/secrets-store-csi-driver-provider-azure#1284]
**Have you**

- [x] Read [Troubleshooting Guide](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/troubleshooting/)
- [x] Searched on [GitHub issues](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues) and [Discussions](https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions)

When I mount the volume onto a pod.
eg. 

```yaml
cat <<EOF | kubectl apply -f -
kind: Pod
apiVersion: v1
metadata:
  name: busybox-secrets-store-inline-wi
spec:
  containers:
    - name: busybox
      image: registry.k8s.io/e2e-test-images/busybox:1.29-4
      command:
        - "/bin/sleep"
        - "10000"
      volumeMounts:
      - name: secrets-store01-inline
        mountPath: "/mnt/secrets-store"
        readOnly: true
  volumes:
    - name: secrets-store01-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "azure-kvname-wi"
EOF
```

I see the following error appear in the Pods events
```json
MountVolume.SetUp failed for volume "secrets-store01-inline" : rpc error: code
= Unknown desc = failed to mount secrets store objects for pod
default/busybox-secrets-store-inline-wi, err: rpc error: code = Unknown desc =
failed to mount objects, error: failed to get keyvault client: failed to get
authorizer for keyvault client: failed to acquire token: FromAssertion(): http
call(https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/oauth2/v2.0/token)(POST)
error: reply status code was 401:

{
  "error": "unauthorized_client",
  "error_description": "AADSTS70021: No matching federated identity record found for presented assertion. Assertion Issuer 'https://uksouth.oic.prod-aks.azure.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/'. Assertion Subject: 'system:serviceaccount:default:default'. Assertion Audience: 'api://AzureADTokenExchange'. https://docs.microsoft.com/en-us/azure/active-directory/develop/workload-identity-federation\r\nTrace ID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx\r\nCorrelation ID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx\r\nTimestamp: 2023-08-22 20:59:57Z",
  "error_codes": [
    70021
  ],
  "timestamp": "2023-08-22 20:59:57Z",
  "error_uri": "https://login.microsoftonline.com/error?code=70021"
}
```
I've confirmed the `Assertion Issuer` is correct and matches the federation credential.

Where does the `Assertion Subject` value come from?

My managed identity federation credential subject identifier is `system:serviceaccount:default:workload-identity-sa` where `workload-identity-sa` is the name of the `ServiceAccount` I have provisioned in Kubernetes. 

**I don't know why it's trying to query `system:serviceaccount:default:default`.** I'm sure i've just missed something but I've followed the docs and troubleshooting guide and cannot find what is wrong.

```yaml
kubectl get serviceaccount/workload-identity-sa -o yaml

apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  labels:
    azure.workload.identity/use: "true"
  name: workload-identity-sa
  namespace: default
```

```yaml
kubectl get secretproviderclass/azure-kvname-wi -o yaml

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"secrets-store.csi.x-k8s.io/v1","kind":"SecretProviderClass","metadata":{"annotations":{},"name":"azure-kvname-wi","namespace":"default"},"spec":{"parameters":{"clientID":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx","cloudName":"","keyvaultName":"XXXXXXXXXXX","objects":"array:\n  - |\n    objectName: test123\n    objectType: secret\n    objectVersion: \"\"\n","tenantId":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx","usePodIdentity":"false","useVMManagedIdentity":"false"},"provider":"azure"}}
  generation: 1
  name: azure-kvname-wi
  namespace: default
spec:
  parameters:
    clientID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    cloudName: ""
    keyvaultName: XXXXXXXXXXXX
    objects: |
      array:
        - |
          objectName: test123
          objectType: secret
          objectVersion: ""
    tenantId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
  provider: azure
````

I am able to successfully query the secret by running. I see the secret value appear in the pod logs.
```yaml
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Pod
metadata:
  name: quick-start
  namespace: default
  labels:
    azure.workload.identity/use: "true"
spec:
  serviceAccountName: "workload-identity-sa"
  containers:
    - image: ghcr.io/azure/azure-workload-identity/msal-go
      name: oidc
      env:
      - name: KEYVAULT_URL
        value: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      - name: SECRET_NAME
        value: "test123"
  nodeSelector:
    kubernetes.io/os: linux
EOF
```

So it's not an issue with something else being misconfigured, it's only isolated to when I attempt to mount the secrets via a volume.

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
`image: mcr.microsoft.com/oss/kubernetes-csi/secrets-store/driver:v1.3.4`

- Azure Key Vault provider version: (use the image tag):
`image: mcr.microsoft.com/oss/azure/secrets-store/provider-azure:v1.4.1`

- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`):
`v1.26.6`

- Cluster type: (e.g. AKS, aks-engine, etc):
`AKS`

- Installation method: ([Helm](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/getting-started/installation/#deployment-using-helm) , [Deployment yamls](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/getting-started/installation/#using-deployment-yamls), [AKS managed add-on](https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver)):
`AKS managed addon`

specifying this value in the terraform configuration for AKS will automatically enable the `azure-keyvault-secrets-provider` addon
```terraform
key_vault_secrets_provider {
    secret_rotation_enabled = true
  }
```

## Replicate entire setup

<details>
  <summary>Expand for Full terraform configuration.</summary>
  
  ```terraform
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 3.69.0"
    }

    kubectl = {
      source  = "gavinbunney/kubectl"
      version = ">= 1.14.0"
    }
  }
}

provider "azurerm" {
  features {}
}

provider "kubectl" {
  host                   = azurerm_kubernetes_cluster.aks.kube_config.0.host
  client_key             = base64decode(azurerm_kubernetes_cluster.aks.kube_config.0.client_key)
  client_certificate     = base64decode(azurerm_kubernetes_cluster.aks.kube_config.0.client_certificate)
  cluster_ca_certificate = base64decode(azurerm_kubernetes_cluster.aks.kube_config.0.cluster_ca_certificate)
  load_config_file       = false
}

provider "kubernetes" {
  host                   = azurerm_kubernetes_cluster.aks.kube_config.0.host
  client_key             = base64decode(azurerm_kubernetes_cluster.aks.kube_config.0.client_key)
  client_certificate     = base64decode(azurerm_kubernetes_cluster.aks.kube_config.0.client_certificate)
  cluster_ca_certificate = base64decode(azurerm_kubernetes_cluster.aks.kube_config.0.cluster_ca_certificate)
}

locals {
  workload_namespace = "default"
  workload_name      = "workload-identity-sa"

  kv_name = "kv-test-XXXXXX"

  kv_secret_name = "test123"
}

resource "azurerm_resource_group" "rg" {
  name     = "rg-ecommerce-demo-01"
  location = "uksouth"
}

resource "azurerm_kubernetes_cluster" "aks" {
  name                      = "aks-ecommerce-demo-01"
  location                  = azurerm_resource_group.rg.location
  resource_group_name       = azurerm_resource_group.rg.name
  dns_prefix                = "test-ecommerce-demo"
  oidc_issuer_enabled       = true
  workload_identity_enabled = true

  key_vault_secrets_provider {
    secret_rotation_enabled = true
  }

  default_node_pool {
    name                        = "default"
    node_count                  = 2
    vm_size                     = "Standard_D4s_v3"
    temporary_name_for_rotation = "akstempnode"
  }


  identity {
    type = "SystemAssigned"
  }

  tags = {
    Environment = "Development"
  }
}

data "azurerm_client_config" "current" {}

resource "azurerm_user_assigned_identity" "aks_workload_identity" {
  location            = azurerm_resource_group.rg.location
  name                = "aks-workload-identity"
  resource_group_name = azurerm_resource_group.rg.name

  depends_on = [
    azurerm_resource_group.rg
  ]
}

resource "azurerm_federated_identity_credential" "workload_identity_credentials" {
  name                = "workload-identity-credentials"
  resource_group_name = azurerm_resource_group.rg.name
  audience            = ["api://AzureADTokenExchange"]
  issuer              = azurerm_kubernetes_cluster.aks.oidc_issuer_url
  parent_id           = azurerm_user_assigned_identity.aks_workload_identity.id
  subject             = "system:serviceaccount:${local.workload_namespace}:${local.workload_name}"

  depends_on = [
    azurerm_kubernetes_cluster.aks,
    azurerm_user_assigned_identity.aks_workload_identity
  ]
}

resource "azurerm_key_vault" "key_vault" {
  name                        = local.kv_name
  location                    = azurerm_resource_group.rg.location
  resource_group_name         = azurerm_resource_group.rg.name
  enabled_for_disk_encryption = true
  tenant_id                   = data.azurerm_client_config.current.tenant_id
  soft_delete_retention_days  = 7
  purge_protection_enabled    = false

  sku_name = "standard"

  access_policy {
    tenant_id = data.azurerm_client_config.current.tenant_id
    object_id = data.azurerm_client_config.current.object_id

    secret_permissions = [
      "Get",
      "Set",
    ]
  }

  access_policy {
    tenant_id = data.azurerm_client_config.current.tenant_id
    object_id = azurerm_user_assigned_identity.aks_workload_identity.principal_id

    secret_permissions = [
      "Get",
      "List",
    ]
  }

  depends_on = [
    azurerm_resource_group.rg,
    azurerm_user_assigned_identity.aks_workload_identity
  ]
}

resource "azurerm_key_vault_secret" "test_secret" {
  name         = local.kv_secret_name
  value        = "SecretValue123"
  key_vault_id = azurerm_key_vault.key_vault.id

  depends_on = [
    azurerm_key_vault.key_vault,
  ]
}

resource "kubernetes_service_account" "aks_workload_service_account" {
  metadata {
    name      = local.workload_name
    namespace = local.workload_namespace
    annotations = {
      "azure.workload.identity/client-id" = azurerm_user_assigned_identity.aks_workload_identity.client_id
    }
    labels = {
      "azure.workload.identity/use" = "true"
    }
  }

  depends_on = [
    azurerm_user_assigned_identity.aks_workload_identity
  ]
}

resource "kubectl_manifest" "secret_provider_class" {
  yaml_body = <<-EOF
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
name: azure-kvname-wi
spec:
provider: azure
parameters:
  usePodIdentity: "false"
  useVMManagedIdentity: "false"
  clientID: "${azurerm_user_assigned_identity.aks_workload_identity.client_id}"
  keyvaultName: "${local.kv_name}"
  cloudName: ""
  objects:  |
    array:
      - |
        objectName: ${local.kv_secret_name}
        objectType: secret
        objectVersion: ""
  tenantId: "${data.azurerm_client_config.current.tenant_id}"
EOF

  depends_on = [
    azurerm_user_assigned_identity.aks_workload_identity
  ]
}
```
</details>

I also followed and copied the commands from [here](https://learn.microsoft.com/en-us/azure/aks/csi-secrets-store-identity-access#configure-workload-identity) to see if there was anything in the terraform configuration and I get the same error when copying the commands from the docs.
