### ISSUE TITLE
AAD Pod Identity Auth - Sync with Kubernetes Secrets

### ISSUE THREAD

**Issue by cloudpea** [Azure/secrets-store-csi-driver-provider-azure#132]
**What steps did you take and what happened:**
I have installed the helm chart successfully all pods running and no errors in the logs and have deployed the below secret provider classes to sync a secret. If i only want to sync to a kubernetes secret what do i use as the selector within AzureIdentityBinding. 

Documentation here - https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/docs/pod-identity-mode.md 

 ```yaml
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: keyvault
  namespace: kube-secrets
spec:
  provider: keyvault                  
  parameters:
    usePodIdentity: "true"
    keyvaultName: "<redacted>"
    objects:  |
      array:
        - |
          objectName: aks-keyvault-controller-test-secret
          objectType: secret
    resourceGroup: "<redacted>"                      
    subscriptionId: "<redacted>"
    tenantId: "<redacted>"      
---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: kv-secret-test-secret
  namespace: kube-secrets
spec:
  provider: keyvault                             
  secretObjects:
  - data:
    - objectName: aks-keyvault-controller-test-secret
      key: value
    secretName: kv-secret-test-secret
    type: Opaque 
```

**What did you expect to happen:**

KeyVauly secret to sync to a Kubernetes secret.

**Anything else you would like to add:**
I am unsure of which pod authenticates to KeyVault and i need to grant access via the Selector in 
AzureIdentityBinding

**Which access mode did you use to access the Azure Key Vault instance:**
Pod Identity

**Environment:**
- Secrets Store CSI Driver version: v0.0.11
- Azure Key Vault provider version: 0.0.6
- Kubernetes version:  1.18.2
- Cluster type: AKS

**Comment by aramase** [comment]
> If i only want to sync to a kubernetes secret what do i use as the selector within AzureIdentityBinding.

`AzureIdentityBinding` would be reference to the `AzureIdentity` and `Selector` as defined in the doc - https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/docs/pod-identity-mode.md
It's not possible to only sync as a kubernetes secret and not have the contents mounted as files in the pod. The sync as K8s secret is done by getting the contents from the fs. 

You should be able to consolidate the `SecretProviderClass` into one like this -


```yaml
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
 name: keyvault
 namespace: kube-secrets
spec:
 provider: keyvault         <------ should be azure
 secretObjects:
 - data:
   - objectName: aks-keyvault-controller-test-secret
     key: value
   secretName: kv-secret-test-secret
   type: Opaque     
 parameters:
   usePodIdentity: "true"
   keyvaultName: "<redacted>"
   objects:  |
     array:
       - |
         objectName: aks-keyvault-controller-test-secret
         objectType: secret
   tenantId: "<redacted>"      
```

Add the `aadpodidbinding` to the application pod that's using the CSI volume as documented in the [pod-identity](https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/docs/pod-identity-mode.md) doc.
