### ISSUE TITLE
pod stuck in ContainerCreating: failed to mount secrets store objects for pod. Status=403 Code="Forbidden"

### ISSUE THREAD

**Issue by tuxerrante** [Azure/secrets-store-csi-driver-provider-azure#1328]
**Have you**

- [X] Read [Troubleshooting Guide](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/troubleshooting/)
- [X] Searched on [GitHub issues](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues) and [Discussions](https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions)
- [X] followed these guides
   - https://learn.microsoft.com/en-us/azure/aks/csi-secrets-store-driver#upgrade-an-existing-aks-cluster-with-azure-key-vault-provider-for-secrets-store-csi-driver-support
   - https://learn.microsoft.com/en-us/azure/aks/csi-secrets-store-identity-access#configure-workload-identity
 

**What steps did you take and what happened:**
After enabling CSI addon on AKS 1.27.3, and following above mentioned guides with the workload identity authentication method I get to the end with stucked workloads.
The reason is some wrong configuration on the roles used to access the key vault.

Checking from the portal I see "Key Vault Administrator" correctly assigned to my app.
My app ID (USER_ASSIGNED_CLIENT_ID) is the one used in the service account and in the SecretProviderClass.

**What did you expect to happen:**
A secret should be mounted in the testing pod.

**Steps:**
Vars
```sh
export APPLICATION_NAME="csi-secrets-app"
export AZ_KV_PROVIDER_CLIENT_ID="XXX"
export CLUSTER_NAME=aks-test
export FEDERATED_IDENTITY_NAME="${CLUSTER_NAME}-federatedidentity"
export KEYVAULT_NAME="XXX"
export KEYVAULT_SECRET_NAME="secret-01"
export LOCATION="westeurope"
export NAMESPACE="csi-secrets"
export RESOURCE_GROUP="aff-XXX"
export SECRET_PROVIDER_CLASS=azure-kvname-wi
export SERVICE_ACCOUNT_NAME="workload-identity-sa" 
export VAULT_URL="https://XXX"
export SUBSCRIPTION_ID="8f7d6be2-728a-490b-997e-f23b01ad202a"

export AKS_OIDC_ISSUER="$(az aks show --resource-group $RESOURCE_GROUP --name $CLUSTER_NAME --query "oidcIssuerProfile.issuerUrl" -o tsv)"
export USER_ASSIGNED_CLIENT_ID="$(az identity show -g $RESOURCE_GROUP --name $APPLICATION_NAME --query 'clientId' -o tsv)"
export IDENTITY_TENANT=$(az aks show --name $CLUSTER_NAME --resource-group $RESOURCE_GROUP --query identity.tenantId -o tsv)
export KEYVAULT_SCOPE=$(az keyvault show --name $KEYVAULT_NAME --query id -o tsv)
###
```

Service Account
```
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: ${USER_ASSIGNED_CLIENT_ID}
  name: ${SERVICE_ACCOUNT_NAME}
  namespace: ${NAMESPACE}

```

SecretProviderClass
```
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  namespace: ${NAMESPACE}
  name: ${SECRET_PROVIDER_CLASS}            # needs to be unique per namespace
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: "${USER_ASSIGNED_CLIENT_ID}"  # Setting this to use workload identity
    keyvaultName: ${KEYVAULT_NAME}          # Set to the name of your key vault
    cloudName: ""                           # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: secret-01
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: key-01
          objectType: key
          objectVersion: ""
    tenantId: "${IDENTITY_TENANT}"        # The tenant ID of the key vault

```

Pod
```
# This is a sample pod definition for using SecretProviderClass and workload identity to access your key vault
kind: Pod
apiVersion: v1
metadata:
  namespace: ${NAMESPACE}
  name: busybox-secrets-store-inline-wi
  labels:  
    azure.workload.identity/use: "true"
spec:
  serviceAccountName: "${SERVICE_ACCOUNT_NAME}"
  containers:
    - name: busybox
      image: registry.k8s.io/e2e-test-images/busybox:1.29-4
      command:
        - "/bin/sleep"
        - "10000"
      volumeMounts:
      - name: secrets-store01-inline
        mountPath: "/mnt/secrets-store"
        readOnly: true
  volumes:
    - name: secrets-store01-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "${SECRET_PROVIDER_CLASS}"

```

```sh
az aks enable-addons --addons azure-keyvault-secrets-provider --name $CLUSTER_NAME --resource-group $RESOURCE_GROUP --enable-secret-rotation
az account set --subscription $SUBSCRIPTION_ID

# Workload identity running with some issue
kubectl get -A pod -l app=workload-identity-webhook
# NAMESPACE                        NAME                                                   READY   STATUS             RESTARTS         AGE
# azure-workload-identity-system   azure-wi-webhook-controller-manager-5c5b79f9d4-ct47c   0/1     Error              71 (5m11s ago)   5h39m
# azure-workload-identity-system   azure-wi-webhook-controller-manager-5c5b79f9d4-qnrbp   1/1     Running            0                2d2h
# azure-workload-identity-system   azure-wi-webhook-controller-manager-5c5b79f9d4-ww7qq   1/1     Running            0                2d2h
# azure-workload-identity-system   azure-wi-webhook-controller-manager-7db9547547-8bhpr   0/1     CrashLoopBackOff   71 (64s ago)     5h41m

kubectl -n azure-workload-identity-system logs -l app=workload-identity-webhook
# {"level":"info","timestamp":"2023-10-06T16:03:16.795505Z","logger":"entrypoint","caller":"/workspace/main.go:162$main.setupWebhook","message":"registering webhook to the webhook server"}
# panic: unable to set up pod mutator: failed to get AAD endpoint: autorest/azure: There is no cloud environment matching the name "${AZURE_ENVIRONMENT:-AZUREPUBLICCLOUD}"
# goroutine 83 [running]:
# main.setupWebhook({0x1b2b0c0, 0xc000327c00}, 0x0?)
#         /workspace/main.go:165 +0x19c
# created by main.mainErr
#         /workspace/main.go:144 +0xc71

kubectl create ns $NAMESPACE
envsubst < yaml/wi-sa.yaml | kubectl apply -f -

# Check the SA was correctly annotated with the client ID
kubectl -n $NAMESPACE get sa workload-identity-sa -o yaml

# Create the app if not done before
az identity create --name $APPLICATION_NAME --resource-group $RESOURCE_GROUP

# Assign admin role to the app
az role assignment create --role "Key Vault Administrator" --assignee $USER_ASSIGNED_CLIENT_ID --scope $KEYVAULT_SCOPE
# ⚠️ **Is an admin role really needed**? Isn't Reader enough?

# Create the federated identity credential between the managed identity, service account issuer, and subject 
az identity federated-credential create --name $FEDERATED_IDENTITY_NAME --identity-name $APPLICATION_NAME --resource-group $RESOURCE_GROUP --issuer ${AKS_OIDC_ISSUER} --subject system:serviceaccount:${NAMESPACE}:${SERVICE_ACCOUNT_NAME}

# Deploy a SecretProviderClass 
envsubst < yaml/secret-provider-class.yaml | kubectl apply -f -

# Let's try a single POD first
envsubst < yaml/csi-pod.yaml | kubectl apply -f -
kubectl -n $NAMESPACE get pods -w
# NAME                              READY   STATUS              RESTARTS   AGE
# busybox-secrets-store-inline-wi   0/1     ContainerCreating   0          12s

# POD LOGS
40s         Warning   FailedMount   pod/busybox-secrets-store-inline-wi   
MountVolume.SetUp failed for volume "secrets-store01-inline" : rpc error: code = Unknown desc = failed to mount secrets store objects for pod csi-secrets/busybox-secrets-store-inline-wi, err: rpc error: code = Unknown desc = failed to mount objects, error: failed to get objectType:secret, objectName:secret-01, objectVersion:: keyvault.BaseClient#GetSecret: Failure responding to request: StatusCode=403 -- 
Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="The user, group or application 'appid=XXX;
oid=YYY;
iss=https://ZZZ' does not have secrets get permission on key vault 'KEYVAULT_NAME;location=...'. ...
 InnerError={"code":"AccessDenied"}
```
I've already checked the client ID here in the log output is the same with Admin role as set up above.

**Which access mode did you use to access the Azure Key Vault instance:**
Workload identity
https://learn.microsoft.com/en-us/azure/aks/csi-secrets-store-identity-access#configure-workload-identity

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):  
   - mcr.microsoft.com/oss/kubernetes-csi/csi-node-driver-registrar:v2.8.0
   - mcr.microsoft.com/oss/kubernetes-csi/secrets-store/driver:v1.3.4
   - mcr.microsoft.com/oss/azure/secrets-store/provider-azure:v1.4.1

- Azure Key Vault provider version: (use the image tag): ?
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`):
```
kubectl version --short
Client Version: v1.26.1
Kustomize Version: v4.5.7
Server Version: v1.27.3

kubectl get nodes -o wide
kubectl get nodes -o wide
NAME                                STATUS   ROLES   AGE    VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
aks-agentpool-29737789-vmss00000h   Ready    agent   2d2h   v1.27.3   10.224.0.4    <none>        Ubuntu 22.04.3 LTS   5.15.0-1041-azure   containerd://1.7.5-1
aks-ephemeral-35351927-vmss000000   Ready    agent   2d2h   v1.27.3   10.224.0.6    <none>        Ubuntu 22.04.3 LTS   5.15.0-1041-azure   containerd://1.7.5-1
aks-ephemeral-35351927-vmss000001   Ready    agent   2d2h   v1.27.3   10.224.0.7    <none>        Ubuntu 22.04.3 LTS   5.15.0-1041-azure   containerd://1.7.5-1
```

- Cluster type: (e.g. AKS, aks-engine, etc): AKS
- Installation method: ([Helm](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/getting-started/installation/#deployment-using-helm) , [Deployment yamls](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/getting-started/installation/#using-deployment-yamls), [AKS managed add-on](https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver)):
AKS managed add-on
