### ISSUE TITLE
Environment Variable and Volume Mount

### ISSUE THREAD

**Issue by adamcarter81** [Azure/secrets-store-csi-driver-provider-azure#133]
Slightly related to : https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/99

Perhaps my understanding isn't correct, or the documentation could be clearer:

What I am trying to achieve: read a value from the KV, present it as an environment variable for the deployment, via a Kubernetes secret. The two secrets are a username & password

What works:
A clean namespace, I deploy the SecretProviderClass reading the secrets and syncing with Kubernetes secrets
I deploy the nginx-secrets-store and verify the secret exists in the ns
I can deploy my application OK - the pods start as they find the secret and it is converted to an environment variable.Bingo!

What does not work / what I would expect:
A clean namespace, I deploy the SecretProviderClass reading the secrets and syncing with Kubernetes secrets
I  deploy my application pods don't start as they don't find the secret. The deployment yaml should mount the volume and create the secret as per the nginx-secrets-store deployment. I can't see what is different about they way I am mounting the volume and the way the nginx-secrets-store is mounting the volume.

My question - Should I have to deploy the  nginx-secrets-store  before deploying my application?
I thought from the documentation that  nginx-secrets-store was only for testing the config?

Thanks

**Comment by aramase** [comment]
@adamcarter81 This is a sample deployment for using the secret content as env vars -

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx0
  labels:
    app: nginx
spec:
  replicas: 250
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
          - name: secrets-store-inline
            mountPath: "/mnt/secrets-store"
            readOnly: true
        env:
         - name: FOO_SECRET1
           valueFrom:
             secretKeyRef:
               name: foosecret
               key: bar
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure"
            nodePublishSecretRef:
              name: secrets-store-creds
```

and this is the `SecretProviderClass`

```yaml
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure
spec:
  provider: azure
  secretObjects:
  - data:
    - key: foo
      objectName: secret1
    - key: bar
      objectName: secret2
    secretName: foosecret
    type: Opaque
  parameters:
    usePodIdentity: "false"
    keyvaultName: "$KEYVAULT"
    objects: |
      array:
        - |
          objectName: secret1
          objectType: secret
          objectVersion: ""
        - |
          objectName: secret2
          objectType: secret
          objectVersion: ""
    tenantId: "$TENANT_ID"
```

> My question - Should I have to deploy the nginx-secrets-store before deploying my application?

No, that's a sample pod. You could do the same with your application pod/deployment. Please note, the volumes is required. The sync with Kubernetes secrets is an optional feature that depends on the mounted content. If you're still having issues after using the above manifests, please provide the `SecretProviderClass` and deployment manifest yaml that you're using.
