### ISSUE TITLE
"Identity not found"

### ISSUE THREAD

**Issue by Svessir** [Azure/secrets-store-csi-driver-provider-azure#1356]
**Have you**

- [x] Read [Troubleshooting Guide](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/troubleshooting/)
- [x] Searched on [GitHub issues](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues) and [Discussions](https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions)

**What steps did you take and what happened:**
Here is the defintion:
```
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: b2c-secrets
spec:
  provider: azure
  parameters:
    objects: |
      array:
        - |
          objectName: Identity-Service--ClientSecret
          objectType: secret
    tenantId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    keyvaultName: <key-vault-name>
    usePodIdentity: "false"
    clientID: xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
```
And here is the error I get:
```
"failed to process mount request" err="failed to get objectType:secret, objectName:Identity-Service--ClientSecret, objectVersion:: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://<key-vault-name>.vault.azure.net/secrets/<secret-name>/?api-version=2016-10-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {\"error\":\"invalid_request\",\"error_description\":\"Identity not found\"} Endpoint http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&client_id=%24%7BUSER_ASSIGNED_CLIENT_ID%7D&resource=https%3A%2F%2Fvault.azure.net"
```

**What did you expect to happen:**
To get access to the key vault

**Anything else you would like to add:**
Here is another thread I found on the issue: https://learn.microsoft.com/en-us/answers/questions/1300991/why-is-csi-giving-an-identity-not-found-error.
I've used the csi driver before and it worked then. I followed the same steps now and it does not work. Is it incompatible with the current kubernetes version?

**Which access mode did you use to access the Azure Key Vault instance:**
I've tried both workload identity and user assigned managed identity access modes.

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): v1.3.4
- Azure Key Vault provider version: (use the image tag): v1.4.1
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`): v1.26.6 
- Cluster type: (e.g. AKS, aks-engine, etc): AKS
- Installation method: ([Helm](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/getting-started/installation/#deployment-using-helm) , [Deployment yamls](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/getting-started/installation/#using-deployment-yamls), [AKS managed add-on](https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver)): AKS managed-add-on
