### ISSUE TITLE
Get certificate in pfx format

### ISSUE THREAD

**Issue by nilsga** [Azure/secrets-store-csi-driver-provider-azure#138]
**Describe the solution you'd like**
I would like to get a certificate in it's raw format.

**Anything else you would like to add:**
I have a certificate in pfx format, and would like it to stay that way when it is exported to the mount, and not converted to pem. But  seems like it is not possible to configure this behavior?

**Comment by MistyKuu** [comment]
+1. It's a standard scenario for .NET applications with HTTPS. It only supports .PFX format but not PEM.
We need to have a way to store pfx file in Azure Key Vault -> map it to kubernetes secrets as it is -> map to a file (in pfx format) -> reference the path with ASPNETCORE_Kestrel__Certificates__Default__Path env variable

**Comment by hermanho** [comment]
Here is a workaround to get the cert from keyvault and generate pfx key for IdentityServer4 in pod on Kubernetes. Basically it is converted with openssl in container. The pfx cert file is saved to /ssl/certificate.pfx .


```yaml
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: az-kv-provider
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: "client_id"
    keyvaultName: "my-keyvault"
    cloudName: ""
    objects: |
      array:
        - |
          objectName: web_ssl
          objectType: secret
          objectVersion: ""
    resourceGroup: ""
    subscriptionId: ""
    tenantId: "abc.onmicrosoft.com"
```

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testing-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testing-web
  template:
    metadata:
      labels:
        app: testing-web
        aadpodidbinding: test
    spec:
      initContainers:
        - image: alpine
          name: convert-certs
          command:
            [
              "sh",
              "-c",
              "apk add openssl && openssl pkcs12 -in /kvmnt/web_ssl -export -out /ssl/certificate.pfx -password pass:",
            ]
          volumeMounts:
            - name: az-kv-secrets-store
              mountPath: /kvmnt
              readOnly: true
            - name: ssl
              mountPath: /ssl
      containers:
        - name: web
          image: your_aspnetcore_docker_image
          volumeMounts:
            - name: ssl
              mountPath: /ssl
              readOnly: true
      volumes:
        - name: ssl
          emptyDir: {}
        - name: az-kv-secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: az-kv-provider
```

**Comment by MistyKuu** [comment]
Working like a charm. Thanks for sharing it but I'd really like to see it supported natively by this plugin

**Comment by hermanho** [comment]
I deleted the original code because I found a bug. Now it is fixed and I re-post it.

```yaml
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: az-kv-provider
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: "client_id"
    keyvaultName: "my-keyvault"
    cloudName: ""
    objects: |
      array:
        - |
          objectName: web_ssl
          objectType: secret
          objectVersion: ""
    resourceGroup: ""
    subscriptionId: ""
    tenantId: "abc.onmicrosoft.com"
```

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-test
  template:
    metadata:
      labels:
        app: ubuntu-test
        aadpodidbinding: test
    spec:
      initContainers:
        - image: alpine
          name: convert-certs
          command:
            [
              "sh",
              "-c",
              "apk add openssl && openssl pkcs12 -in /kvmnt/web_ssl -export -out /ssl/certificate -password pass:",
            ]
          volumeMounts:
            - name: az-kv-secrets-store
              mountPath: /kvmnt
              readOnly: true
            - name: ssl
              mountPath: /ssl
      containers:
        - name: web
          image: your_aspnetcore_docker_image
          volumeMounts:
            - name: ssl
              mountPath: /ssl
              readOnly: true
      volumes:
        - name: ssl
          emptyDir: {}
        - name: az-kv-secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: az-kv-provider
```

**Comment by pwiens** [comment]
This plugin really should support pulling down the raw pkcs12 cert. I wasn't expecting it to be a PEM, in addition the cert chain in the PEM is in the wrong order. It should be server cert -> intermediates -> root but it looks like the order is reversed.

**Comment by aramase** [comment]
can be supported with this issue - https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/89

**Comment by dzrhythm** [comment]
I'm curious as to the justification for converting PFX to PEM in this provider. Why not just leave the file format as it exists in Key Vault (albeit base64 encoded for PFX)? This is what the [FlexVolume ](https://github.com/Azure/kubernetes-keyvault-flexvol) version of this provider did, which was handy. That way everyone can choose the format they need.

**Comment by aramase** [comment]
The current default is PEM, so the driver can use the content to create a kubernetes tls secret for ingress if configured in `SecretProviderClass`. We are planning to natively support configuring the expected format, so users can decide the format in which they expect the contents. Default will be `PEM` to support backward compatibility.

**Comment by dzrhythm** [comment]
Thanks @aramase. Any estimate for delivery? This is an impediment for us migrating from the FlexVolume driver, which is going out of support. We are deploying .NET Core 3.1 applications and are mounting certs for Kestrel (no ingress controllers). Unfortunately not even 3.1 has built-in support for private key PEM files, so we'd have to parse the PEM and build the cert object ourselves.

**Comment by kenans** [comment]
We are in the same situation as @dzrhythm. Kestrel only supports PFX cert currently and won't be supporting PEM until 5.0.0-preview.8.x.x according to [one of the Github issues](https://github.com/dotnet/aspnetcore/issues/4706). It would be great that the CSI driver could support mounting or creating an Opaque type of secret with PFX cert directly on k8s.

**Comment by aramase** [comment]
We'll add this to our next milestone and include it as part of `v0.0.8` release.

**Comment by kenans** [comment]
Hi @aramase, I tested the PFX feature but the I got a question about it.  My `SecretProviderClass` config is something like below,
```
  spec:
    parameters:
      keyvaultName: KV
      objects: |
        array:
          - |
            objectName: "cert-pfx-name"
            objectType: secret
            objectVersion: ""
            objectFormat: "pfx"
            objectAlias: "cert-pfx-alias"
      resourceGroup: RG
      subscriptionId: SUB
      tenantId: TENANT
      usePodIdentity: "true"
    provider: azure
    secretObjects:
    - data:
      - key: https.pfx
        objectName: cert-pfx-alias
      secretName: k8s-cert-pfx
      type: Opaque
```

With this I'm able to mount the csi volume into a pod and I can see the k8s secret created successfully. However, when I check out the cert file content from the mounted volume, I was expecting the file to be the binary PFX format but it was actually the base64 encoded version of it. To get the original PFX cert, I would have to decode the file again. I wonder if the behavior by design?

Note what the KeyVault GetSecret API returns is not the raw PFX file but actually the base64 encoded of it. I also wonder if it's what causes the problem?
