### ISSUE TITLE
Azure Key Vault Provider for Secrets Store CSI Driver in an AKS cluster with ServicePrincipal 

### ISSUE THREAD

**Issue by linoytzarfatyMicrosoft** [Azure/secrets-store-csi-driver-provider-azure#1383]
I created a Service Principle(app registration) and provided necessary permission on the AKV and then created AKS with the SP credentials with the following command:

az aks create -n linoy-aks-kv -g linoy-kv-provider --enable-addons azure-keyvault-secrets-provider --service-principal c743821a-7b70-434b-b446-61782b733406 --client-secret ***

 then I applied the following SecretProviderClass:

# This is a SecretProviderClass example using a service principal to access Key Vault
```
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kv-aks-sp
spec:
  provider: azure
  secretObjects:                            # secretObjects defines the desired state of synced K8s secret objects
  - secretName: ingress-tls-csi
    type: kubernetes.io/tls
    data: 
    - objectName: cert-wildcard-ssl
      key: tls.key
    - objectName: cert-wildcard-ssl
      key: tls.crt
  parameters:
    usePodIdentity: "false"         # [OPTIONAL] if not provided, will default to "false"
    userAssignedIdentityID: 8358b055-11da-4c76-a32c-587231e1d14a
    keyvaultName: "kv-aks-sp"          # the name of the KeyVault
    cloudName: ""                   # [OPTIONAL for Azure] if not provided, azure environment will default to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: cert-wildcard-ssl
          objectType: secret        
          objectVersion: ""        
    tenantID: "***"
```
 

The tls certification with type: kubernetes.io/tls does not appear 

kubectl get secret : 

<img width="745" alt="image" src="https://github.com/Azure/secrets-store-csi-driver-provider-azure/assets/106018941/67cb3e51-a5dd-473e-abb8-66510900604d">

Why I cant see the tls certificate?

How to integrate the Azure Key Vault Provider for Secrets Store CSI Driver in an AKS cluster with ServicePrincipal?

thanks
