### ISSUE TITLE
K8s Secret Not Created

### ISSUE THREAD

**Issue by ajit-pendse** [Azure/secrets-store-csi-driver-provider-azure#1464]
**Have you**

- [X] Read [Troubleshooting Guide](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/troubleshooting/)
- [X] Searched on [GitHub issues](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues) and [Discussions](https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions)

**What steps did you take and what happened:**
Created a SecretProviderClass with `secretObjects` and `parameters`. Using Managed Identity created when CSI Driver is initialized - following the documentation [here](https://learn.microsoft.com/en-us/azure/aks/csi-secrets-store-driver). Full content of SecretProviderClass yaml are below -
```yaml
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name:  test-akv # needs to be unique per namespace
  namespace: test
spec:
  provider: azure
  secretObjects:                             
  - secretName: test-config-secret
    type: Opaque
    labels:
      releasename: test
    data:
      - objectName: dbpassword-config
        key: db_password.conf
      - objectName: rootpassword-config
        key: root_password.conf
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "<client ID for the managed identity>" # Setting this to use workload identity
    keyvaultName: doha-kra-vault       # Set to the name of your key vault
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: dbpassword-config             # Set to the name of your secret
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: rootpassword-config                # Set to the name of your key
          objectType: secret
          objectVersion: ""
    tenantId: "<tenant-id>"        # The tenant ID of the key vault
```

**What did you expect to happen:**
Secret with name `test-config-secret` should be created in namespace `test` - either as part of SecretProviderClass deployment or after deploying the pod that uses the secret.

**Anything else you would like to add:**

Same key vault is accessible and getting mounted as a volume on the pod when using inline method without creating a Kubernetes Secret as mentioned in points 3 and 5 [here](https://learn.microsoft.com/en-us/azure/aks/csi-secrets-store-identity-access#configure-managed-identity).

Sample configuration that works - 
```
kind: Pod
apiVersion: v1
metadata:
  name: busybox-secrets-store-inline-user-msi
spec:
  containers:
    - name: busybox
      image: registry.k8s.io/e2e-test-images/busybox:1.29-4
      command:
        - "/bin/sleep"
        - "10000"
      volumeMounts:
      - name: secrets-store01-inline
        mountPath: "/mnt/secrets-store"
        readOnly: true
  volumes:
    - name: secrets-store01-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "test-akv"
```

**Which access mode did you use to access the Azure Key Vault instance:**
Default managed identity created after enabling the `azure-keyvault-secrets-provider` addon. The managed identity name is of the format `azurekeyvaultsecretsprovider-<cluster name>`. Secrets User access is provided on the key vault for this identity.

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): Image used - mcr.microsoft.com/oss/kubernetes-csi/secrets-store/driver:v1.3.4-1
- Azure Key Vault provider version: (use the image tag): Image used - mcr.microsoft.com/oss/azure/secrets-store/provider-azure:v1.4.1
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`): 
  ```
    Client Version: v1.28.4
    Server Version: v1.28.3
  ```
  Details of Nodes -
  ```
    OS-IMAGE: Ubuntu 22.04.3 LTS
    KERNEL-VERSION: 5.15.0-1054-azure
    CONTAINER-RUNTIME: containerd://1.7.7-1
  ```

- Cluster type: (e.g. AKS, aks-engine, etc): AKS
- Installation method: ([Helm](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/getting-started/installation/#deployment-using-helm) , [Deployment yamls](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/getting-started/installation/#using-deployment-yamls), [AKS managed add-on](https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver)): AKS managed add-on
