### ISSUE TITLE
Cannot mount TLS cert for k8s secret syncing - on new pods

### ISSUE THREAD

**Issue by julie-ng** [Azure/secrets-store-csi-driver-provider-azure#150]
### Sync TLS Cert in Key Vault for Ingress controller

I am trying to load a cert from key vault into the nginx-ingress controller via CSI driver (and sync'd k8s secret) per this tutorial
https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/sample/ingress-controller-tls/README.md#deploy-a-secretsproviderclass-resource

### Problem / Bug

BUT this **does not work** if the pods are not _already_ running

### Environment

- Secrets Store CSI Driver version: 0.0.7 via `csi-secrets-store-provider-azure-0.0.8` chart
- Azure Key Vault provider version: ? Not sure which version you are requesting
- Kubernetes version: 1.16.9 
- Cluster type: AKS

### Prerequisites

- TLS Cert is in Key Vault
- AKS Cluster is up and running 
 - csi-driver deployed and running
 - aad-pod-identity deployed and running (not part of tutorial but part of my setup)

Then I run `helm install…` and it the controller pods never start.

For reference, this is my CRD, where 👈   refers to 2 options and its effects. Obviously, only 1 is applied at a time.

```yaml
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kv
  namespace: ingress
spec:
  provider: azure

  # mount these objects from key vault
  parameters:
    usePodIdentity: "true"
    keyvaultName: ${AZ_KEY_VAULT_NAME}
    objects:  |
      array:
        - |
          objectName: aks-tls-cert
          objectType: cert     👈  controller pods start, but cert is mangled
          objectType: secret  👈  pods cannot start
        - |
          objectName: hello-world
          objectType: secret
    resourceGroup: ${AZURE_RESOURCE_GROUP}
    subscriptionId: ${AZURE_SUBSCRIPTION_ID}
    tenantId: ${AZURE_TENANT_ID}

  # sync to k8s secret objects
  secretObjects:
  - secretName: tls-cert # for k8s
    type: kubernetes.io/tls
    data:
    - objectName: aks-tls-cert # from kv
      key: tls.key
    - objectName: aks-tls-cert
      key: tls.crt
```

### Symptoms - Ingress Controller Pods do not start

- the `default-backend` pod deploys fine
- but controller pods get stuck in `ContainerCreating` status **because it cannot mount the certificate _as a secret_**. See Logs:

```
│   Type     Reason       Age        From                                      Message                                                                                           │
│   ----     ------       ----       ----                                      -------                                                                                           │
│   Normal   Scheduled    <unknown>  default-scheduler                         Successfully assigned ingress/nginx-ingress-controller-7d8b78f86-4lltx to aks-default-39712770-vm │
│ ss000000                                                                                                                                                                       │
│   Warning  FailedMount  29s        kubelet, aks-default-39712770-vmss000000  MountVolume.SetUp failed for volume "key-vault" : kubernetes.io/csi: mounter.SetupAt failed: rpc  │
│ error: code = Unknown desc = error mounting secret time="2020-07-09T12:42:23Z" level=fatal msg="[error] : failed to get objectType:secret, objectName:aks-tls-cert, obje │
│ ctVersion:: pkcs12: expected exactly two items in the authenticated safe"                                                                                                      │
│  for pod: 9aced1c8-6d31-4a64-9ec2-c57a0f01d586, ns: ingress                                                                                                                    │
│   Warning  FailedMount  27s  kubelet, aks-default-39712770-vmss000000  MountVolume.SetUp failed for volume "key-vault" : kubernetes.io/csi: mounter.SetupAt failed: rpc error: │
│  code = Unknown desc = error mounting secret time="2020-07-09T12:42:25Z" level=fatal msg="[error] : failed to get objectType:secret, objectName:aks-tls-cert, objectVers │
│ ion:: pkcs12: expected exactly two items in the authenticated safe"                                                                                                            │
│  for pod: 9aced1c8-6d31-4a64-9ec2-c57a0f01d586, ns: ingress                                                                                                                    │
│   Warning  FailedMount  26s  kubelet, aks-default-39712770-vmss000000  MountVolume.SetUp failed for volume "key-vault" : kubernetes.io/csi: mounter.SetupAt failed: rpc error: │
│  code = Unknown desc = error mounting secret time="2020-07-09T12:42:26Z" level=fatal msg="[error] : failed to get objectType:secret, objectName:aks-tls-cert, objectVers │
│ ion:: pkcs12: expected exactly two items in the authenticated safe"                                                                                                            │
│  for pod: 9aced1c8-6d31-4a64-9ec2-c57a0f01d586, ns: ingress                                                                                                                    │
│   Warning  FailedMount  23s  kubelet, aks-default-39712770-vmss000000  MountVolume.SetUp failed for volume "key-vault" : kubernetes.io/csi: mounter.SetupAt failed: rpc error: │
│  code = Unknown desc = error mounting secret time="2020-07-09T12:42:29Z" level=fatal msg="[error] : failed to get objectType:secret, objectName:aks-tls-cert, objectVers │
│ ion:: pkcs12: expected exactly two items in the authenticated safe"                                                                                                            │
│  for pod: 9aced1c8-6d31-4a64-9ec2-c57a0f01d586, ns: ingress                                                                                                                    │
│   Warning  FailedMount  18s  kubelet, aks-default-39712770-vmss000000  MountVolume.SetUp failed for volume "key-vault" : kubernetes.io/csi: mounter.SetupAt failed: rpc error: │
│  code = Unknown desc = error mounting secret time="2020-07-09T12:42:34Z" level=fatal msg="[error] : failed to get objectType:secret, objectName:aks-tls-cert, objectVers │
│ ion:: pkcs12: expected exactly two items in the authenticated safe"                                                                                                            │
│  for pod: 9aced1c8-6d31-4a64-9ec2-c57a0f01d586, ns: ingress                                                                                                                    │
│   Warning  FailedMount  10s  kubelet, aks-default-39712770-vmss000000  MountVolume.SetUp failed for volume "key-vault" : kubernetes.io/csi: mounter.SetupAt failed: rpc error: │
│  code = Unknown desc = error mounting secret time="2020-07-09T12:42:42Z" level=fatal msg="[error] : failed to get objectType:secret, objectName:aks-tls-cert, objectVers │
│ ion:: pkcs12: expected exactly two items in the authenticated safe"                                                                                                            │
│  for pod: 9aced1c8-6d31-4a64-9ec2-c57a0f01d586, ns: ingress
```

To the example above fails because I am using `objectType: secret` per [tutorial](https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/sample/ingress-controller-tls/README.md#deploy-a-secretsproviderclass-resource) from this repo.

### Mount as `cert`-> container starts, but certificate is mangled.

As the tutorial describes, because of how Key Vault works, we have to load a secret. Although the container can start when I switch to `objectType: cert`, the certificate is broken, which can be verified like so:

```
$ kubectl describe secret tls-cert
Name:         tls-cert
Namespace:    ingress
Labels:       <none>
Annotations:  <none>

Type:  kubernetes.io/tls

Data
====
tls.crt:  2228 bytes 
tls.key:  62 bytes 👈  this number is too small
```

## Solution?

I understand the need to be compatible with Key Vault and follow its design. But we need to offer a workaround or interface that abstracts away Azure's design philosophy from developers.

The problem with this bug is that it's no longer possible to automate this infrastructure setup because results cannot be achieved asynchronously.

I've also tried updating the CRD after the pod's are created. But because the cert is already mounted, the k8s secret doesn't seem to update/sync. And of course restarting pods does not work because then they don't mount.

Any ideas on how to get this working?
