### ISSUE TITLE
[Feature request] Reject input with invisible/zero-width character

### ISSUE THREAD

**Issue by JoeyC-Dev** [Azure/secrets-store-csi-driver-provider-azure#1544]
**Describe the solution you'd like**
For example, there is a yaml file as below, and it should be rejected:
```
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-wi 
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: 00000000-0000-0000-0000-000000000000​
    keyvaultName: ${KEYVAULT_NAME}
    cloudName: ""
    objects:  |
      array:
        - |
          objectName: secret1 
          objectType: secret 
          objectVersion: ""      
    tenantId: "${IDENTITY_TENANT}" 
```

![image](https://github.com/Azure/secrets-store-csi-driver-provider-azure/assets/142381267/48bcd199-3050-428a-bd3e-296a9a1ddf66)

When there is a root cause like this happening to an incident, it is a disaster to find out the root cause. 
(The reason I submitted this feature request is because it happened recently. We just had no where out at the time until we find the "space-like" thing when manually opened the yaml with VSC. The issue kept for 3 days.)

**Anything else you would like to add:**
N/A

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): v1.4.2
- Azure Key Vault provider version: (use the image tag):v1.5.1
- Kubernetes version: (use `kubectl version`): 1.28.3
- Cluster type: (e.g. AKS, aks-engine, etc): AKS
