### ISSUE TITLE
Why are the objects a string and not a map?

### ISSUE THREAD

**Issue by Vad1mo** [Azure/secrets-store-csi-driver-provider-azure#155]
Having an objects as string makes no sense in yaml/json context. 

```yaml
    objects:  |
      array:
        - |
          objectName: secret1
          objectAlias: SECRET_1     # [OPTIONAL available for version > 0.0.4] object alias
          objectType: secret        # object types: secret, key or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: key1
          objectAlias: ""
          objectType: key
          objectVersion: ""
```

When working with those type of manifests where a yaml map is encoded in a string things become very complicated and errors are difficult to spot. 

What is the background of doing it this way and is there a possibility this could be improved?
