### ISSUE TITLE
Get the pfx from Azure Key Vault mantaining the password

### ISSUE THREAD

**Issue by priscofarina** [Azure/secrets-store-csi-driver-provider-azure#1767]
**Have you**

- [x] Read [Troubleshooting Guide](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/troubleshooting/)
- [x] Searched on [GitHub issues](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues) and [Discussions](https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions)

**What steps did you take and what happened:**
I am importing a pfx file in the Azure Key Vault but when I try to read the pfx file from the KV then the pfx fetched file got mounted in my pod but without a password (I want the same password of my pfx file which I have mounted in the KV):

```
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: my-secrets-azure-keyvault-secrets
spec:
  provider: azure
  secretObjects:
    - secretName: my-secrets
      type: Opaque
      data:
------
  parameters:
    usePodIdentity: "false"
    keyvaultName: {{ required "A valid .Values.secrets.keyvaultName entry required!" (index (.Values.secrets) "keyvaultName") }}
    tenantId: {{ required "A valid .Values.secrets.tenantId entry required!" (index (.Values.secrets) "tenantId") }}
    objects: |
      array:
        - |
          objectName: FILEPFX
          objectType: secret
          objectFormat: pfx
          objectEncoding: base64
          objectAlias: FILEPFX.pfx
```

**What did you expect to happen:**

I was expecting that the pfx file mounted is getting retrieved maintaining the password.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Which access mode did you use to access the Azure Key Vault instance:**
[e.g. Service Principal, Pod Identity, User Assigned Managed Identity, System Assigned Managed Identity]

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):   
   secrets-store-csi-driver-1.4.6
   image: mcr.microsoft.com/oss/kubernetes-csi/csi-node-driver-registrar:v2.11.1

- Azure Key Vault provider version: (use the image tag):
  image: mcr.microsoft.com/oss/azure/secrets-store/provider-azure:v1.6.0

- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`):

```
   kubectl version
   Client Version: v1.31.2 
   Kustomize Version: v5.4.2
   Server Version: v1.27.10+c79e5e2
```
- Cluster type: **OpenShift version 4.14.16**
