### ISSUE TITLE
Issue when deploying example pod with VMSS User Assigned Managed Identity

### ISSUE THREAD

**Issue by lastcoolnameleft** [Azure/secrets-store-csi-driver-provider-azure#179]
**What steps did you take and what happened:**
https://github.com/Azure/secrets-store-csi-driver-provider-azure#deploy-your-kubernetes-resources

```
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvname
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"         # [OPTIONAL] if not provided, will default to "false"
    useVMManagedIdentity: "true"   # [OPTIONAL available for version > 0.0.4] if not provided, will default to "false"
    userAssignedIdentityID: "3f9cf9dd-7707-4a2a-a323-c255b0f1c2fa"
    keyvaultName: "msal-proxy"          # the name of the KeyVault
    objects:  |
      array:
        - |
          objectName: examplepasswd
          objectType: secret        # object types: secret, key or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
    resourceGroup: "msal-proxy-rg"               # [REQUIRED for version < 0.0.4] the resource group of the KeyVault
    subscriptionId: "df8428d4-bc25-4601-b458-1c8533ceec0b"            # [REQUIRED for version < 0.0.4] the subscription ID of the KeyVault
    tenantId: "72f988bf-86f1-41af-91ab-2d7cd011db47"                    # the tenant ID of the KeyVau 
```

```
kind: Pod
apiVersion: v1
metadata:
  name: nginx-secrets-store-inline
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - name: secrets-store-inline
      mountPath: "/mnt/secrets-store"
      readOnly: true
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "azure-kvname"
        nodePublishSecretRef:
          name: secrets-store-creds
```

**What did you expect to happen:**
I expected the pod to successfully deploy, but instead got:
```
  Normal   Scheduled    3m7s                default-scheduler                           Successfully assigned default/nginx-secrets-store-inline to aks-nodepool1-32922832-vmss000002
  Warning  FailedMount  64s                 kubelet, aks-nodepool1-32922832-vmss000002  Unable to attach or mount volumes: unmounted volumes=[secrets-store-inline], unattached volumes=[secrets-store-inline default-token-fgqf2]: timed out waiting for the condition
  Warning  FailedMount  59s (x9 over 3m7s)  kubelet, aks-nodepool1-32922832-vmss000002  MountVolume.SetUp failed for volume "secrets-store-inline" : fetching NodePublishSecretRef default/secrets-store-creds failed: kubernetes.io/csi: failed to find the secret secrets-store-creds in the namespace default with error: secrets "secrets-store-creds" not found       [0.4s]
```

**Anything else you would like to add:**
The example nginx.yaml references secrets-store-creds but doesn't provide any detail about it, or even if it's an optional value.
It's unclear from the documentation, but I think that this is only valuable if your using SP identity because I found steps for it there `secrets-store-creds`; however, not in the User/System Assigned Managed Identity.

**Which access mode did you use to access the Azure Key Vault instance:**
User Assigned Managed Identity

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):us.gcr.io/k8s-artifacts-prod/csi-secrets-store/driver:v0.0.12
- Azure Key Vault provider version: (use the image tag): mcr.microsoft.com/k8s/csi/secrets-store/provider-azure:0.0.7
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`):v1.16.10
- Cluster type: (e.g. AKS, aks-engine, etc): AKS
