### ISSUE TITLE
Create multiple secret objects from a single SecretProviderClass

### ISSUE THREAD

**Issue by zicaden** [Azure/secrets-store-csi-driver-provider-azure#198]
Hello Team,

I am trying to use a single SecretProviderClass to create multiple secret objects. I tried the following configuration - but found that only the first secret object ["mtls-secret" in this example] was created and the second one ["ca-secret" in this example] was not. 

The objects are correctly loaded into the mount volume.

Is there something wrong with my configuration / this is not supported?

```
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: akv-csi-mtls
spec:
  provider: azure
  secretObjects:                                # secretObjects defines the desired state of synced K8s secret objects
  - secretName: mtls-secret
    type: kubernetes.io/tls
    data:
    - objectName: aks-tls-cert
      key: tls.crt
    - objectName: aks-tls-cert
      key: tls.key
  - secretName: ca-secret
    type: kubernetes.io/tls
    data:
    - objectName: aks-ca-cert
      key: ca.crt
  parameters:
    usePodIdentity: "false"
    keyvaultName: "az-kv"                        # the name of the KeyVault
    objects: |
      array:
        - |
          objectName: aks-tls-cert
          objectType: secret
        - |
          objectName: aks-ca-cert
          objectType: secret
    tenantId: "xxxx-xxxx-xxxx-xxx"                  # the tenant ID of the KeyVault
```
