### ISSUE TITLE
Unable to retrieve the actual certificate, secret only retrieving the ca signing certs.

### ISSUE THREAD

**Issue by mansing2** [Azure/secrets-store-csi-driver-provider-azure#226]
We are trying to retrieve the certificate (We have a trusted certificate from Digicert) from Azure Key vault using the CSI driver to use with NGINX Ingress Controller. The kubernetes secret is getting created but when the certificate is retrieved using ```kubectl get secret ingress-tls-csi``` we don't get the actual certificate and it only returns the ca signing certs. 

Also when we check the log of ingress controller we get an error ```Error getting SSL certificate "ignite/ingress-tls-csi": local SSL certificate ignite/ingress-tls-csi was not found. Using default certificate``` though the ingress-tls-csi secret does exist. 

SecretProviderClass.yaml
```
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{.Values.secretproviderclass}}
spec:
  provider: azure
  secretObjects:                                # secretObjects defines the desired state of synced K8s secret objects
  - secretName: ingress-tls-csi
    type: kubernetes.io/tls
    data: 
    - objectName: ignite-all-sites-com
      key: tls.key
    - objectName: ignite-all-sites-com
      key: tls.crt
  parameters:
    usePodIdentity: "true"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    keyvaultName: {{.Values.keyvault_name}}
    cloudName: AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: ignite-all-sites-com
          objectType: secret
    resourceGroup: {{.Values.resource_group}}
    subscriptionId: {{.Values.subscription_id}}
    tenantId: {{.Values.tenantid}}
```

ingress.yaml
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-tls
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
  - hosts:
    - test.mydomain.com
    secretName: ingress-tls-csi
  rules:
  - host: test.mydomain.com
    http:
      paths:
      - backend:
          serviceName: nginx-two
          servicePort: 80
        path: /
```

**Which access mode did you use to access the Azure Key Vault instance:**
Pod Identity

**Environment:**

- Secrets Store CSI Driver version: latest
- Azure Key Vault provider version: latest
- Kubernetes version: 1.16.10
- Cluster type: AKS
