### ISSUE TITLE
secretObjects not creating Secrets

### ISSUE THREAD

**Issue by dkirrane** [Azure/secrets-store-csi-driver-provider-azure#230]
**What steps did you take and what happened:**

I have the following `SecretProviderClass` in namespace called `mine` namespace.
But it is not creating a Secert `foo` in mine namespace.

When I create a Pod and mount the Secret as file it works. 
But it just doesn't create any K8s Secret. 

Anyway way to debug this furthur. I don't see anything in when I run describe on SecretProviderClass

```
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: mine
  namespace: mine
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"
    keyvaultName: "my-kv"
    tenantId: "xxxxxxxxxxxxx"
    cloudName: "AzurePublicCloud"
    objects:  |
      array:
        - |
          objectName: my-service-secret
          objectType: secret
        - |
          objectName: my-access-cert
          objectType: secret

  secretObjects:
  - secretName: foo
    type: Opaque
    data:
    - objectName: my-service-secret
      key: my-service-secret
    - objectName: my-access-cert
      key: my-access-cert

```

**What did you expect to happen:**
Secret `foo` gets created in same namespace as SecretProviderClass

**Anything else you would like to add:**

**Which access mode did you use to access the Azure Key Vault instance:**
[e.g. Service Principal, Pod Identity, User Assigned Managed Identity, System Assigned Managed Identity]
Pod Identity

**Environment:**
AKS 1.18.6 & csi-secrets-store-provider-azure provider Helm chart 0.0.7

- Secrets Store CSI Driver version: (use the image tag):
- Azure Key Vault provider version: (use the image tag):
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`): 1.18.6
- Cluster type: (e.g. AKS, aks-engine, etc): AKS

**Comment by aramase** [comment]
@dkirrane Is the `SecretProviderClass` in the same namespace as the pod?

If yes, could you check the logs for the CSI driver pod (container - `secrets-store`) running on the same node as the workload pod?

**Comment by dkirrane** [comment]
Yes both pod and SPC in same namespace. Redeployed the Pod, Checked node it was on. No new logs in secrets store container. Some older logs. Nothing new.

```
2020-09-10T19:38:41.976918512Z  time="2020-09-10T19:38:41Z" level=debug msg="GRPC request: "
2020-09-10T19:38:41.976921712Z  time="2020-09-10T19:38:41Z" level=debug msg="GRPC response: ready:<value:true > "
```

**Comment by aramase** [comment]
@dkirrane Just to confirm, you're using `0.0.7` helm chart release? That release uses `v0.0.11` version of the driver. 

Do you have another `SecretProviderClass` with the same name in another namespace?

1. `kubectl get secretproviderclass -A`
2. `kubectl describe pod nginx-env-secrets -n mine`
3. After redeploying the pod, logs from the `secrets-store` container pod from the CSI driver pod running on the same node as the `nginx-env-secrets` pod. Could you provide the entire log file?

**Comment by dkirrane** [comment]
yip correct on versions.
redeployed chart again

```
helm repo add csi-secrets-store-provider-azure https://raw.githubusercontent.com/Azure/secrets-store-csi-driver-provider-azure/master/charts

helm install key-vault-csi csi-secrets-store-provider-azure/csi-secrets-store-provider-azure \
     --version 0.0.7 --namespace key-vault-csi

# Install SPC and Pod manifests
kubectl apply -f .
```

```
$ kubectl get secretproviderclass -A
NAMESPACE   NAME   AGE
mine        spc    16s
```

```
# No secret called 'foo' created in namespace 'mine'
$ kubectl get Secrets -n mine
NAME                  TYPE                                  DATA   AGE
default-token-wmbbx   kubernetes.io/service-account-token   3      23h
istio.default         istio.io/key-and-cert                 3      23h
```

```
kubectl describe pod nginx-env-secrets -n mine

Name:         nginx-env-secrets
Namespace:    mine
Priority:     0
Node:         aks-sbx4-38476688-vmss000003/10.153.9.51
Start Time:   Fri, 11 Sep 2020 19:44:36 +0100
Labels:       aadpodidbinding=ixcc-sbx-4-pod-mi
Annotations:  Status:  Pending
IP:           XXXXXXXXXXXXX
IPs:
  IP:  XXXXXXXX
Containers:
  nginx:
    Container ID:
    Image:          nginx
    Image ID:
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CreateContainerConfigError
    Ready:          False
    Restart Count:  0
    Environment:
      SERVICE_URI:  <set to the key 'my-service-secret' in secret 'foo'>  Optional: false
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-wmbbx (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  spc:
    Type:              CSI (a Container Storage Interface (CSI) volume source)
    Driver:            secrets-store.csi.k8s.io
    FSType:
    ReadOnly:          true
    VolumeAttributes:      secretProviderClass=spc
  default-token-wmbbx:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-wmbbx
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                  From                                   Message
  ----     ------     ----                 ----                                   -------
  Normal   Scheduled  <unknown>            default-scheduler                      Successfully assigned mine/nginx-env-secrets to aks-sbx4-38476688-vmss000003
  Normal   Pulled     42s (x8 over 2m8s)   kubelet, aks-sbx4-38476688-vmss000003  Successfully pulled image "nginx"
  Warning  Failed     42s (x8 over 2m8s)   kubelet, aks-sbx4-38476688-vmss000003  Error: secret "foo" not found
  Normal   Pulling    27s (x9 over 2m10s)  kubelet, aks-sbx4-38476688-vmss000003  Pulling image "nginx"
```


`secrets-store` logs from aks-sbx4-38476688-vmss000003 node:
[https://gist.github.com/dkirrane/c5bcde1e3e5545b0ee61f47aeb56374a](https://gist.github.com/dkirrane/c5bcde1e3e5545b0ee61f47aeb56374a)

[SecretProviderClass.yaml](https://gist.github.com/dkirrane/af2c3576812bef85668dab3170500276)

[nginx-env-secrets.yaml](https://gist.github.com/dkirrane/94d0bbce085600d5f96b4a76094a5896)

**Comment by aramase** [comment]
@dkirrane There are 2 issues with the manifests you shared - 
1. There is no `volumeMount` in the pod spec. If there is no `volumeMount` kubelet will not invoke the CSI driver for mount for the pod. 
2. The `secretObjects` need to be one level above under spec. In the example you shared it's under `spec.parameters` which isn't right.

Here is sample pod - https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/test/bats/tests/azure/nginx-pod-secrets-store-inline-volume-crd.yaml and secret provider class - https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/test/bats/tests/azure/azure_synck8s_v1alpha1_secretproviderclass.yaml

**Comment by dkirrane** [comment]
Ok so my Pod was missing volumeMounts. Once I added that the Secret got created.
```
      volumeMounts:
      - name: foo
        mountPath: "/mnt/secrets-store"
        readOnly: true
  volumes:
    - name: foo
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: spc
```


So, is there a way to sync to K8s Secrets without adding volumes to Pods. For instance, a Helm chart I cannot change that uses this approach to get secrets i.e. no volumes
https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables
