### ISSUE TITLE
How to connect XX.crt file and YY.key secrets in KV to tls.crt and tls.key in k8s ?

### ISSUE THREAD

**Issue by mchudinov** [Azure/secrets-store-csi-driver-provider-azure#232]
I follow the documentation provided here https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/sample/ingress-controller-tls/README.md

The document reference only one secret in KV, but there must be two: one certificate and one key for that certificate.

```
objects: |
      array:
        - |
          objectName: FILE-CRT
          objectType: secret                  
        - |
          objectName: FILE-KEY
          objectType: secret          
```
It is unclear how to put them both in k8s as a `secretObject ` type of `kubernetes.io/tls` 

Then document says nothing about `userAssignedIdentityID`. Kubernetes will not get an access to KV without `userAssignedIdentityID` property defined and identity configured in Azure AD.

The proper setup should look like this:
```
kind: SecretProviderClass
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
metadata:
  name: azure-tlscsi
spec:
  provider: azure
  secretObjects:                                # secretObjects defines the desired state of synced K8s secret objects
  - secretName: ingress-tls-csi
    type: kubernetes.io/tls
    data: 
    - objectName: ingresscert
      key: tls.key
    - objectName: ingresscert
      key: tls.crt
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"          
    userAssignedIdentityID: "xxx"           
    keyvaultName: "fmdclient"                        # the name of the Key Vault    
    objects: |
      array:
        - |
          objectName: FILE-CRT
          objectType: secret                  
        - |
          objectName: FILE-KEY
          objectType: secret          
    resourceGroup: "xxx"                              # the resource group name of the key vault
    subscriptionId: "xxx"  # the subscription ID of the key vault    
    tenantId: "xxx"        # the tenant ID of the key vault
```
