### ISSUE TITLE
Integration with Kubeflow's PodDefault (or PodPreset) doesn't seem to work

### ISSUE THREAD

**Issue by Shaked** [Azure/secrets-store-csi-driver-provider-azure#239]
Integration with PodDefault (or PodPreset) doesn't seem to work

Honestly, I am not 100% sure that this is a driver's bug, so forgive me if that's the case.

However, if you know how this can be fixed, I would be more than happy to file a PR. 

I have also opened https://github.com/kubeflow/kubeflow/issues/5315. 

**What steps did you take and what happened:**

Steps: 

1. I have installed kubeflow https://github.com/kubeflow/kubeflow 
2. I have set a PodDefault under my namespace. In case you are not familiar with the term,

> Kubeflow components, which are in charge of creating pods (e.g., notebook controller) add some of available PodDefault labels to the pods when required. For Jupyter notebooks, for instance, Notebook UI asks users which PodDefault needs to be applied to the notebook pods (see this issue). Notebook-controller, then, adds the corresponding PodDefault labels to Notebook pods.

> Admission webhook controller in general, intercepts requests to the Kubernetes API server, and can modify and/or validate the requests. Here the admission webhook is implemented to modify pods based on the available PodDefaults. When a pod creation request is received, the admission webhook looks up the available PodDefaults which match the pod's label. It then, mutates the Pod spec according to PodDefault's spec. For the above PodDefault, when a pod creation request comes which has the label `add-gcp-secret:"true"', it appends the volume and volumeMounts to the pod as described in the PodDefault spec.

(https://github.com/kubeflow/kubeflow/blob/eebcb110197f48236555caf9f1235b2d43a0c973/components/admission-webhook/README.md)

You can set the same PodDefault using this:

```
NAME=shaked
NAMESPACE=kubeflow-klein-shaked; 
<<EOF | kubectl -n $NAMESPACE apply -f -
apiVersion: "kubeflow.org/v1alpha1"
kind: PodDefault
metadata:
  name: azure-keyvault-v2
  namespace: $NAMESPACE
spec:
  selector:
    matchLabels:
      azure-keyvault-v2: "true"
  desc: "add azure keyvault v2"
  env:
    - name: WHO_AM_I
      value: $NAME
  volumeMounts:
    - name: secrets-store-inline
      mountPath: /secrets
      readOnly: true
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "azure-jupyter-default"
        nodePublishSecretRef: 
          name: kvcreds
EOF
```

3. I have configured a `SecretProviderClass`: 

```
KEY_VAULT_NAME="";
TENANT_ID="";
╰─$ cat <<EOF | kubectl apply -f -
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-jupyter-default
spec:
  provider: azure
  parameters:
    keyvaultName: "$KEY_VAULT_NAME"          # the name of the KeyVault
    objects:  |
      array:
        - |
          objectName: kubeflow-config;
          objectAlias: config.json
          objectType: secret
        - |
          objectName: mysql-config
          objectAlias: mysql.conf
          objectType: secret
    tenantId: "$TENANT_ID"
EOF
```

4. I have created a new Jupyter notebook through kubeflow's dashboard and selected the above PodDefault. 

**What did you expect to happen:**

I expected that the volume `secrets-store-inline` will be mounted with the secrets taken from Azure KeyVault. However, instead, I'm seeing:

```
  secrets-store-inline:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
```

When I create a PodDefault with the old plugin, aka https://github.com/Azure/kubernetes-keyvault-flexvol/, this works as expected: 

```
NAMESPACE=<YOUR USER NAMESPACE>; 
NAME=<YOUR USER>
AKV_TENANT_ID=<TENANT_ID>;\
AKV_NAME=<AKV_NAME>;\
AKV_ALIASES="config.json;mysql.conf";\
AKV_OBJECTS="kubeflow-config;mysql-config";\
<<EOF | kubectl -n $NAMESPACE apply -f -
apiVersion: "kubeflow.org/v1alpha1"
kind: PodDefault
metadata:
  name: azure-keyvault
  namespace: $NAMESPACE
spec:
  selector:
    matchLabels:
      azure-keyvault: "true"
  desc: "add azure keyvault"
  env:
    - name: WHO_AM_I
      value: $NAME
  volumeMounts:
    - name: secret-volume
      mountPath: /secrets
  volumes:
    - name: secret-volume
      flexVolume:
        driver: "azure/kv"
        secretRef:
          name: kvcreds
        options:
          usepodidentity: "false"
          keyvaultname: $AKV_NAME
          keyvaultobjectnames: $AKV_OBJECTS
          keyvaultobjectaliases: $AKV_ALIASES
          keyvaultobjecttypes: "secret;secret"
          tenantid: $AKV_TENANT_ID
EOF
```

```
$ kubectl describe pod test-0

  secret-volume:
    Type:       FlexVolume (a generic volume resource that is provisioned/attached using an exec based plugin)
    Driver:     azure/kv
    FSType:
    SecretRef:  &LocalObjectReference{Name:kvcreds,}
    ReadOnly:   false
    Options:    map[keyvaultname:stage-green-eye keyvaultobjectaliases:config.json;mysql.conf keyvaultobjectnames:kubeflow-config;mysql-config keyvaultobjecttypes:secret;secret tenantid:TENANTID usepodidentity:false]
  myvol:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
```

So basically all volumes are working as expected except the one with the `CSI` driver. 

**Anything else you would like to add:**

I tried to debug as much as possible, so few notes I would like to add: 

1. Logs show nothing, as if there's no call made to the CSI driver:

```
╰─$ ku default logs -f csi-secrets-store-provider-azure-1600638025-secrets-store-qrh5q  -c secrets-store --since 10s                                                                                                130 ↵
time="2020-09-24T16:02:36Z" level=debug msg="GRPC call: /csi.v1.Identity/Probe"
time="2020-09-24T16:02:36Z" level=debug msg="GRPC request: {}"
time="2020-09-24T16:02:36Z" level=debug msg="GRPC response: {\"ready\":{\"value\":true}}"
time="2020-09-24T16:02:51Z" level=debug msg="GRPC call: /csi.v1.Identity/Probe"
time="2020-09-24T16:02:51Z" level=debug msg="GRPC request: {}"
time="2020-09-24T16:02:51Z" level=debug msg="GRPC response: {\"ready\":{\"value\":true}}"
time="2020-09-24T16:03:06Z" level=debug msg="GRPC call: /csi.v1.Identity/Probe"
time="2020-09-24T16:03:06Z" level=debug msg="GRPC request: {}"
time="2020-09-24T16:03:06Z" level=debug msg="GRPC response: {\"ready\":{\"value\":true}}"
time="2020-09-24T16:03:21Z" level=debug msg="GRPC call: /csi.v1.Identity/Probe"
time="2020-09-24T16:03:21Z" level=debug msg="GRPC request: {}"
time="2020-09-24T16:03:21Z" level=debug msg="GRPC response: {\"ready\":{\"value\":true}}"
``` 

2. Kubeflow's PodDefault component creates one pod out of the original pod and the PodDefault, then, before the creation of the pod, the component applies a patch: https://github.com/kubeflow/kubeflow/blob/eebcb110197f48236555caf9f1235b2d43a0c973/components/admission-webhook/main.go#L417 - although the patch is correct, I suspect that the CSI driver is failing in this part. What do you think? 

3. I have tried to create my own pod together with the CSI driver configuration and it does load the secrets. Logs also show it's working as expected:

```
21Z" level=debug msg="GRPC response: {\"ready\":{\"value\":true}}"
time="2020-09-23T14:52:36Z" level=debug msg="GRPC call: /csi.v1.Identity/Probe"
time="2020-09-23T14:52:36Z" level=debug msg="GRPC request: {}"
time="2020-09-23T14:52:36Z" level=debug msg="GRPC response: {\"ready\":{\"value\":true}}"
time="2020-09-23T14:52:42Z" level=info msg="reconcile started" node=NODENAME secretproviderclasspodstatus=kubeflow-klein-shaked/test-shaked-kubeflow-klein-shaked-azure-jupyter-default
time="2020-09-23T14:52:43Z" level=debug msg="GRPC call: /csi.v1.Node/NodePublishVolume"
time="2020-09-23T14:52:43Z" level=debug msg="GRPC request: {\"readonly\":true,\"secrets\":\"***stripped***\",\"target_path\":\"/var/lib/kubelet/pods/<UUID>/volumes/kubernetes.io~csi/secrets-store-inline/mount\",\"volume_capability\":{\"AccessType\":{\"Mount\":{}},\"access_mode\":{\"mode\":1}},\"volume_context\":{\"csi.storage.k8s.io/ephemeral\":\"true\",\"csi.storage.k8s.io/pod.name\":\"test-shaked\",\"csi.storage.k8s.io/pod.namespace\":\"kubeflow-klein-shaked\",\"csi.storage.k8s.io/pod.uid\":\"<UUID>\",\"csi.storage.k8s.io/serviceAccount.name\":\"default\",\"secretProviderClass\":\"azure-jupyter-default\"},\"volume_id\":\"csi-ecdf9bfe9c347c93ce041bcebc2c704f56b49b01f2492a1bb53354ad19a8b41a\"}"
time="2020-09-23T14:52:43Z" level=debug msg="target /var/lib/kubelet/pods/<UUID>/volumes/kubernetes.io~csi/secrets-store-inline/mount, volumeId csi-ecdf9bfe9c347c93ce041bcebc2c704f56b49b01f2492a1bb53354ad19a8b41a, attributes map[csi.storage.k8s.io/ephemeral:true csi.storage.k8s.io/pod.name:test-shaked csi.storage.k8s.io/pod.namespace:kubeflow-klein-shaked csi.storage.k8s.io/pod.uid:<UUID> csi.storage.k8s.io/serviceAccount.name:default secretProviderClass:azure-jupyter-default], mountflags []"
time="2020-09-23T14:52:43Z" level=debug msg="Calling provider: azure for pod: kubeflow-klein-shaked/test-shaked"
time="2020-09-23T14:52:43Z" level=warning msg="minimum compatible azure provider version not set for pod: <UUID>, ns: kubeflow-klein-shaked"
time="2020-09-23T14:52:43Z" level=info msg="provider command invoked: /etc/kubernetes/secrets-store-csi-providers/azure/provider-azure --attributes [REDACTED] --secrets [REDACTED] [--targetPath /var/lib/kubelet/pods/<UUID>/volumes/kubernetes.io~csi/secrets-store-inline/mount --permission 420]"
time="2020-09-23T14:52:45Z" level=info msg="time=\"2020-09-23T14:52:43Z\" level=info msg=\"not using pod identity or vm assigned user identity to access keyvault\"\ntime=\"2020-09-23T14:52:43Z\" level=info msg=\"objects: array:\\n  - |\\n    objectName: kubeflow-config\\n    objectAlias: config.json\\n    objectType: secret\\n  - |\\n    objectName: mysql-config\\n    objectAlias: mysql.conf\\n    objectType: secret\\n\"\ntime=\"2020-09-23T14:52:43Z\" level=info msg=\"unmarshaled keyVaultObjects: [{kubeflow-config config.json  secret } {mysql-config mysql.conf  secret }]\"\ntime=\"2020-09-23T14:52:43Z\" level=info msg=\"keyVaultObjects len: 2\"\ntime=\"2020-09-23T14:52:43Z\" level=info msg=\"fetching object: kubeflow-config, type: secret from key vault\"\ntime=\"2020-09-23T14:52:43Z\" level=info msg=\"azure: using client_id+client_secret to retrieve access token\"\ntime=\"2020-09-23T14:52:44Z\" level=info msg=\"successfully mounted config.json\"\ntime=\"2020-09-23T14:52:44Z\" level=info msg=\"fetching object: mysql-config, type: secret from key vault\"\ntime=\"2020-09-23T14:52:44Z\" level=info msg=\"azure: using client_id+client_secret to retrieve access token\"\ntime=\"2020-09-23T14:52:45Z\" level=info msg=\"successfully mounted mysql.conf\"\n"
time="2020-09-23T14:52:45Z" level=info msg="reconcile started" node=NODENAME secretproviderclasspodstatus=kubeflow-klein-shaked/test-shaked-kubeflow-klein-shaked-azure-jupyter-default
time="2020-09-23T14:52:45Z" level=debug msg="GRPC response: {}"
time="2020-09-23T14:52:45Z" level=info msg="no secret objects defined for spc, nothing to reconcile" node=NODENAME secretproviderclasspodstatus=kubeflow-klein-shaked/test-shaked-kubeflow-klein-shaked-azure-jupyter-default
time="2020-09-23T14:52:51Z" level=debug msg="GRPC call: /csi.v1.Identity/Probe"
time="2020-09-23T14:52:51Z" level=debug msg="GRPC request: {}"```
```

**Which access mode did you use to access the Azure Key Vault instance:**

I am using a Service Principal

**Environment:**

- Secrets Store CSI Driver version: :
- Azure Key Vault provider version: :

```
╰─$ helm -n default show chart csi-secrets-store-provider-azure/csi-secrets-store-provider-azure
apiVersion: v1
appVersion: 0.0.8
dependencies:
- condition: secrets-store-csi-driver.install
  name: secrets-store-csi-driver
  repository: https://raw.githubusercontent.com/kubernetes-sigs/secrets-store-csi-driver/master/charts
  version: 0.0.13
description: A Helm chart to install the Secrets Store CSI Driver and the Azure Keyvault
  Provider inside a Kubernetes cluster.
home: https://github.com/Azure/secrets-store-csi-driver-provider-azure
kubeVersion: '>=1.16.0-0'
maintainers:
- email: anish.ramasekar@gmail.com
  name: Anish Ramasekar
name: csi-secrets-store-provider-azure
sources:
- https://github.com/Azure/secrets-store-csi-driver-provider-azure
version: 0.0.10
```

- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`):
```
╰─$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:35:15Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-gke.1504", GitCommit:"fb367de18820fe57bac5d97ad60b7a2cef8765e9", GitTreeState:"clean", BuildDate:"2020-09-09T01:00:23Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```

```
kubectl get nodes -o wide
v1.17.9-gke.1504 
```

- Cluster type: (e.g. AKS, aks-engine, etc): `GKE`

Kubeflow version: 1.0.1
