### ISSUE TITLE
Unable to mount secrets volume to Windows pods using pod identity

### ISSUE THREAD

**Issue by Extant-1** [Azure/secrets-store-csi-driver-provider-azure#250]
**What steps did you take and what happened:**
On our AKS cluster I set installed the key vault CSI driver using helm char v 0.0.10 with only windows enabled and linux disabled (for both the driver and provider). 

I then configured a SecretProviderClass that uses pod identity to retrive a single test secret from the key vault. After setting up the azureidentity and corresponding binding, I configured the pod label with aadpodidbinding and added the volumemount. 

When the pods are initializing they are throwing an error from the kubelet:
``
Warning  FailedMount  103s (x10 over 18m)  kubelet, akswin1000002  (combined from similar events): MountVolume.SetUp failed for volume "secrets-store-inline" : rpc error: code = Unknown desc = error mounting secret time="2020-10-02T02:22:04Z" level=fatal msg="[error] : failed to get keyvaultClient: failed to get key vault token: Get \"http://localhost:2579/host/token/?resource=https://vault.azure.net\": dial tcp [::1]:2579: connectex: No connection could be made because the target machine actively refused it."
``

**What did you expect to happen:**
The secret volume to be mounted to the pod 

**Anything else you would like to add:**
SecretProviderClass (sensitive information redacted)

```
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-app-aks
  namespace: testing
spec:
  provider: azure                   
  parameters:
    usePodIdentity: "true"         # [OPTIONAL for Azure] if not provided, will default to "false"
    useVMManagedIdentity: "false"   # [OPTIONAL available for version > 0.0.4] if not provided, will default to "false"
    keyvaultName: "<key vault name>"          # the name of the KeyVault
    objects:  |
      array:
        - |
          objectName: csi-test-secret
          objectAlias: TESTSECRET     # [OPTIONAL available for version > 0.0.4] object alias
          objectType: secret        # object types: secret, key or cert. For Key Vault certificates, refer to https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/docs/getting-certs-and-keys.md for the object type to use
    tenantId: "<tenantID>"                 # the tenant ID of the KeyVault
```

Logs from the provider container:
``
kubectl logs csi-secrets-store-provider-azure-secrets-store-csi-driver-zjj5n -n key-vault-csi secrets-store
``
```
time="2020-10-02T02:28:03Z" level=debug msg="GRPC response: {\"ready\":{\"value\":true}}"
time="2020-10-02T02:28:13Z" level=debug msg="GRPC call: /csi.v1.Node/NodePublishVolume"
time="2020-10-02T02:28:13Z" level=debug msg="GRPC request: {\"readonly\":true,\"target_path\":\"c:\\\\var\\\\lib\\\\kubelet\\\\pods\\\\a97e278a-8883-40f6-90f8-98b7c98ef489\\\\volumes\\\\kubernetes.io~csi\\\\secrets-store-inline\\\\mount\",\"volume_capability\":{\"AccessType\":{\"Mount\":{}},\"access_mode\":{\"mode\":1}},\"volume_context\":{\"csi.storage.k8s.io/ephemeral\":\"true\",\"csi.storage.k8s.io/pod.name\":\"publicapi-686586cc46-w9c9x\",\"csi.storage.k8s.io/pod.namespace\":\"testing\",\"csi.storage.k8s.io/pod.uid\":\"a97e278a-8883-40f6-90f8-98b7c98ef489\",\"csi.storage.k8s.io/serviceAccount.name\":\"default\",\"secretProviderClass\":\"azure-phippy-app-aks\"},\"volume_id\":\"csi-500e797b81a256f9255eb826270755309ac32977a82e8fc1ffa20bf1e60baee7\"}"
time="2020-10-02T02:28:13Z" level=debug msg="target c:\\var\\lib\\kubelet\\pods\\a97e278a-8883-40f6-90f8-98b7c98ef489\\volumes\\kubernetes.io~csi\\secrets-store-inline\\mount, volumeId csi-500e797b81a256f9255eb826270755309ac32977a82e8fc1ffa20bf1e60baee7, attributes map[csi.storage.k8s.io/ephemeral:true csi.storage.k8s.io/pod.name:publicapi-686586cc46-w9c9x csi.storage.k8s.io/pod.namespace:testing csi.storage.k8s.io/pod.uid:a97e278a-8883-40f6-90f8-98b7c98ef489 csi.storage.k8s.io/serviceAccount.name:default secretProviderClass:azure-phippy-app-aks], mountflags []"
time="2020-10-02T02:28:13Z" level=debug msg="Calling provider: azure for pod: testing/publicapi-686586cc46-w9c9x"
time="2020-10-02T02:28:13Z" level=warning msg="minimum compatible azure provider version not set for pod: a97e278a-8883-40f6-90f8-98b7c98ef489, ns: testing"
time="2020-10-02T02:28:13Z" level=info msg="provider command invoked: C:\\k\\secrets-store-csi-providers\\azure\\provider-azure.exe --attributes [REDACTED] --secrets [REDACTED] [--targetPath c:\\var\\lib\\kubelet\\pods\\a97e278a-8883-40f6-90f8-98b7c98ef489\\volumes\\kubernetes.io~csi\\secrets-store-inline\\mount --permission 420]"
time="2020-10-02T02:28:15Z" level=info msg="time=\"2020-10-02T02:28:13Z\" level=info msg=\"using pod identity to access keyvault\"\ntime=\"2020-10-02T02:28:13Z\" level=info msg=\"mounting secrets store object content for testing/publicapi-686586cc46-w9c9x\"\ntime=\"2020-10-02T02:28:13Z\" level=info msg=\"objects: array:\\n  - |\\n    objectName: csi-test-secret\\n    objectAlias: TESTSECRET     # [OPTIONAL available for version > 0.0.4] object alias\\n    objectType: secret        # object types: secret, key or cert. For Key Vault certificates, refer to https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/docs/getting-certs-and-keys.md for the object type to use\\n\"\ntime=\"2020-10-02T02:28:13Z\" level=info msg=\"unmarshaled keyVaultObjects: [{csi-test-secret TESTSECRET  secret }]\"\ntime=\"2020-10-02T02:28:13Z\" level=info msg=\"keyVaultObjects len: 1\"\ntime=\"2020-10-02T02:28:13Z\" level=info msg=\"fetching object: csi-test-secret, type: secret from key vault\"\ntime=\"2020-10-02T02:28:13Z\" level=info msg=\"azure: using pod identity to retrieve token\"\n"
time="2020-10-02T02:28:15Z" level=error msg="error invoking provider, err: exit status 1, output: time=\"2020-10-02T02:28:15Z\" level=fatal msg=\"[error] : failed to get keyvaultClient: failed to get key vault token: Get \\\"http://localhost:2579/host/token/?resource=https://vault.azure.net\\\": dial tcp [::1]:2579: connectex: No connection could be made because the target machine actively refused it.\"\n for pod: testing/publicapi-686586cc46-w9c9x"
time="2020-10-02T02:28:15Z" level=info msg="unmounting target path c:\\var\\lib\\kubelet\\pods\\a97e278a-8883-40f6-90f8-98b7c98ef489\\volumes\\kubernetes.io~csi\\secrets-store-inline\\mount as node publish volume failed"
E1002 02:28:15.212094     836 mount_windows.go:158] rmdir failed: exec: "cmd": executable file not found in %PATH%, output: ""
time="2020-10-02T02:28:15Z" level=error msg="GRPC error: error mounting secret time=\"2020-10-02T02:28:15Z\" level=fatal msg=\"[error] : failed to get keyvaultClient: failed to get key vault token: Get \\\"http://localhost:2579/host/token/?resource=https://vault.azure.net\\\": dial tcp [::1]:2579: connectex: No connection could be made because the target machine actively refused it.\"\n for pod: testing/publicapi-686586cc46-w9c9x"
```

**Which access mode did you use to access the Azure Key Vault instance:**
Pod Identity

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): mcr.microsoft.com/oss/kubernetes-csi/csi-node-driver-registrar:v1.2.1-alpha.1-windows-1809-amd64
- Azure Key Vault provider version: (use the image tag): mcr.microsoft.com/k8s/csi/secrets-store/driver:v0.0.13
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`): control plane and nodes on 1.18.8
- Cluster type: (e.g. AKS, aks-engine, etc): AKS with both linux and windows node pools
