### ISSUE TITLE
flux errors out when trying to read csi/secret-store/driver image tags

### ISSUE THREAD

**Issue by tuxfight3r** [Azure/secrets-store-csi-driver-provider-azure#252]
**What steps did you take and what happened:**
We are using flux and helm operator to deploy azure CSI driver to our AKS clusters. when deployed using helmreleases everything works except for the part the flux complains that its not able to read all the available tags for the csi driver. The image in question is ```mcr.microsoft.com/k8s/csi/secrets-store/driver``` for which I'm unable to browse the mcr.microsoft.com repo for all the available image tags. but for the other images used in the chart I'm able to browse the available tags.

**Flux Error**
```
ts=2020-10-05T17:19:42.305830098Z caller=warming.go:180 component=warmer canonical_name=mcr.microsoft.com/k8s/csi/secrets-store/driver auth={map[]} err="requesting tags: error parsing HTTP 404 response body: invalid character 'ï' looking for beginning of value: \"\\ufeff<?xml version=\\\"1.0\\\" encoding=\\\"utf-8\\\"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.\\nRequestId:0ee469c9-801e-009b-453b-9b188c000000\\nTime:2020-10-05T17:19:42.2386658Z</Message></Error>\""
```

**Helm Release:**
```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    flux.weave.works/automated: "false"
    flux.weave.works/ignore: "true"
  name: csi-secrets-store-provider-azure
  namespace: admin
spec:
  chart:
    name: csi-secrets-store-provider-azure
    repository: https://raw.githubusercontent.com/Azure/secrets-store-csi-driver-provider-azure/master/charts/
    version: 0.0.11
  releaseName: csi-secrets-store-provider-azure
  values:
    secrets-store-csi-driver:
      linux:
        metricsAddr: :8090

```

**What did you expect to happen:**
Flux should not complain about reading the available tags for the driver image. When I update the helm release to use the same image available from the [kubernete-sigs azure csi driver repo](https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/charts/secrets-store-csi-driver/README.md) it works fine. 

```
# same image available in gcr repo
us.gcr.io/k8s-artifacts-prod/csi-secrets-store/driver:v0.0.14
```

**Anything else you would like to add:**
Everything works fine, I'm able to fetch the secrets properly. its just that flux keeps complaining about unable to read the all the available tags for that image.

**Which access mode did you use to access the Azure Key Vault instance:**
[Pod Identity]

**Environment:**

- Secrets Store CSI Driver version: (`mcr.microsoft.com/k8s/csi/secrets-store/driver:v0.0.14`):
- Azure Key Vault provider version: (` mcr.microsoft.com/oss/azure/secrets-store/provider-azure:0.0.9`):
- Kubernetes version: (`Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9", GitCommit:"e3808385c7b3a3b86db714d67bdd266dc2b6ab62", GitTreeState:"clean", BuildDate:"2020-07-15T20:50:36Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
`):
- Cluster type: (e.g. AKS):
