### ISSUE TITLE
Failed to mount: 'failed to yaml unmarshal objects'

### ISSUE THREAD

**Issue by sireza** [Azure/secrets-store-csi-driver-provider-azure#290]
**What steps did you take and what happened:**
Followed the steps to sync TLS certificate stored in a Key Vault for the nginx ingress controller. The certificate would be used a the default SSL certificate.

Here's the relevant error message:

```
secrets-store time="2020-10-29T02:22:54Z" level=debug msg="GRPC request: {\"readonly\":true,\"target_path\":\"/var/lib/kubelet/pods/b3006015-d5a3-4f51-a782-2d7f910322a1/volumes/kubernetes.io~csi/secrets-store-inline/mount\",\"volume_capability\":{\"AccessType\":{\"Mount\":{}},\"access_mode\":{\"mode\":1}},\"volume_context\":{\"csi.storage.k8s.io/ephemeral\":\"true\",\"csi.storage.k8s.io/pod.name\":\"nginx-ingress-ingress-nginx-controller-84dc984cbd-shdr9\",\"csi.storage.k8s.io/pod.namespace\":\"ingress-control\",\"csi.storage.k8s.io/pod.uid\":\"b3006015-d5a3-4f51-a782-2d7f910322a1\",\"csi.storage.k8s.io/serviceAccount.name\":\"nginx-ingress-ingress-nginx\",\"secretProviderClass\":\"azure-tls\"},\"volume_id\":\"csi-1dca1627b46554ae313e66cfe7bd7fa2fef706a9afdb137699b982b9860b283f\"}"
secrets-store time="2020-10-29T02:22:54Z" level=debug msg="target /var/lib/kubelet/pods/b3006015-d5a3-4f51-a782-2d7f910322a1/volumes/kubernetes.io~csi/secrets-store-inline/mount, volumeId csi-1dca1627b46554ae313e66cfe7bd7fa2fef706a9afdb137699b982b9860b283f, attributes map[csi.storage.k8s.io/ephemeral:true csi.storage.k8s.io/pod.name:nginx-ingress-ingress-nginx-controller-84dc984cbd-shdr9 csi.storage.k8s.io/pod.namespace:ingress-control csi.storage.k8s.io/pod.uid:b3006015-d5a3-4f51-a782-2d7f910322a1 csi.storage.k8s.io/serviceAccount.name:nginx-ingress-ingress-nginx secretProviderClass:azure-tls], mountflags []"
secrets-store time="2020-10-29T02:22:54Z" level=info msg="Using grpc client for provider: azure"
secrets-store time="2020-10-29T02:22:54Z" level=info msg="unmounting target path /var/lib/kubelet/pods/b3006015-d5a3-4f51-a782-2d7f910322a1/volumes/kubernetes.io~csi/secrets-store-inline/mount as node publish volume failed"
secrets-store time="2020-10-29T02:22:54Z" level=error msg="GRPC error: failed to mount secrets store objects for pod ingress-control/nginx-ingress-ingress-nginx-controller-84dc984cbd-shdr9, err: rpc error: code = Unknown desc = failed to mount objects, error: failed to yaml unmarshal objects, error: yaml: line 2: did not find expected '-' indicator"
```
ServiceProviderClass (Sanitized)
```
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
    name: azure-tls
    namespace: ingress-control
spec:
    provider: azure
    secretObjects:                              
      - secretName: aks-ingress-csi
        type: kubernetes.io/tls
        data:
        - objectName: aks-ingress-tls
          key: tls.key
        - objectName: aks-ingress-tls
          key: tls.crt
    parameters:
      usePodIdentity: "false"
      useVMManagedIdentity: "true"
      keyvaultName: kvxxxx  # the name of the KeyVault
      objects: |
        array:
          - |
          objectName: aks-ingress-tls
          objectType: secret
      tenantId: xxxxxxxx-xxxx-4650-ad17-xxxxx
```
Finally here were added to the values when installing nginx ingress with Helm

```
extraVolumes:
   - name: secrets-store-inline
     csi:
       driver: secrets-store.csi.k8s.io
       readOnly: true
       volumeAttributes:
       secretProviderClass: "azure-tls"
extraVolumeMounts:
  - name: secrets-store-inline
    mountPath: "/mnt/secrets-store"
     eadOnly: true
```

**What did you expect to happen:**
Successfully mount the certificate to '/mnt/secret-store' which then sync with a Secret object named 'aks-ingress-csi'

**Anything else you would like to add:**
The AKS VMSS identity have been given 'get' and 'list' access policies for both Secret and Certificate on the Key Vault

**Which access mode did you use to access the Azure Key Vault instance:**
System Assigned Managed Identity.

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): 0.0.16
- Azure Key Vault provider version: (use the image tag): 0.0.9
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`): 1.18.8
- Cluster type: (e.g. AKS, aks-engine, etc): AKS
