### ISSUE TITLE
Azure Key Vault not being successfully mounted on pod

### ISSUE THREAD

**Issue by JuanFryS** [Azure/secrets-store-csi-driver-provider-azure#292]
**What steps did you take and what happened:**
Followed MS guide to mount Azure Key Vault Secrets into pods: [MS Guide](https://docs.microsoft.com/en-us/azure/key-vault/general/key-vault-integrate-kubernetes).

- Created Service Principal and key vault instance and granted permissions for SP to access the key vault and retrieve secrets

- Installed the Secrets Store CSI driver and the Azure Key Vault provider for the driver with:

```
helm repo add csi-secrets-store-provider-azure https://raw.githubusercontent.com/Azure/secrets-store-csi-driver-provider-azure/master/charts
helm install csi-secrets-store-provider-azure/csi-secrets-store-provider-azure --generate-name
```

- Created the following SecretProviderClass object:

```
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: "keyvault"
spec:
  provider: azure
  parameters:
    keyvaultName: "dev1-keyvault"
    objects:  |
      array:
        - |
          objectName: example
          objectType: secret
          objectVersion: ""
        - |
          objectName: secret1
          objectType: secret
          objectVersion: ""
    tenantId: "X-X-X-X-X"
```
- Deployed following single pod where secrets should be mounted:
```
kind: Pod
apiVersion: v1
metadata:
  name: busybox-keyvault
spec:
  imagePullSecrets:
   - name: <credentials_repo>
  containers:
   - name: busybox
     image: <private_repo>
     command:
       - sleep
       - "3600"
     volumeMounts:
      - name: secrets
        mountPath: "/mnt/secrets"
        readOnly: true
  volumes:
    - name: secrets
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "keyvault"
        nodePublishSecretRef:
          name: secrets-store-creds
```

**What did you expect to happen:**
Secrets mounted into pod under the '/mnt/secrets' folder

**Anything else you would like to add:**
Pod seems stuck into 'ContainerCreating' Status.
By describing the pod following messages can be seen:

```
Events:
  Type     Reason       Age    From               Message
  ----     ------       ----   ----               -------
 Normal   Scheduled    8m7s                default-scheduler  Successfully assigned keyvault-test/busybox-keyvault to aks-workflow-69744767-vmss000001
  Warning  FailedMount  91s (x3 over 6m4s)  kubelet            Unable to attach or mount volumes: unmounted volumes=[secrets], unattached volumes=[secrets default-token-lp5kh]: timed out waiting for the condition
  Warning  FailedMount  3s (x4 over 6m7s)   kubelet            MountVolume.SetUp failed for volume "secrets" : kubernetes.io/csi: mounter.SetupAt failed: rpc error: code = DeadlineExceeded desc = context deadline exceeded
```

- A ticket was created directly with the Azure technical support from Microsoft. Given this is an open source project not supported by them, we were advised to create an issue.
- Cluster was created after March 2020.
- Most of the time, after hours, they eventually get created and secrets are mounted. Sometimes it can take 2 hours, sometimes 12 and, sometimes, even 24 hours later, secrets are not mounted.

**Which access mode did you use to access the Azure Key Vault instance:**
Service Principal

**Environment:**

- Kubernetes version: v1.16.10
- Cluster type: AKS
