### ISSUE TITLE
unable to deploy the 2 apps

### ISSUE THREAD

**Issue by kanukhosla** [Azure/secrets-store-csi-driver-provider-azure#322]
Got this error while deploying app1 and app2
![image](https://user-images.githubusercontent.com/57665232/99916358-b78fe000-2cbe-11eb-8e9a-9e7674bb14b6.png)

This my secret 
![image](https://user-images.githubusercontent.com/57665232/99916384-dd1ce980-2cbe-11eb-8134-e6685cb1810a.png)

This is my SecretProviderClass file:
```
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: spc-tls-test1
spec:
  provider: azure
  secretObjects:                              
  - secretName: secrets-store-driver-test1          
    type: kubernetes.io/tls
    data:
    - objectName: ingress-tls-test1
      key: tls.key
    - objectName: ingress-tls-test1
      key: tls.crt
  parameters:
    usePodIdentity: "false"
    keyvaultName: ingress-tls-vault-test1                      
    objects: |
      array:
        - |
          objectName: ingress-tls-test1
          objectType: secret
    tenantId: <directory id of my key vault >
```

Not sure here if my object type should be secret or certificate or something else. 

and I also granted the service principal permissions to get secrets:
az keyvault set-policy -n $KV_NAME --certificate-permissions get --spn <YOUR SPN CLIENT ID>

Can you please help me resolve my issue . 
thanks in advance.

**Comment by kanukhosla** [comment]
This is my SecretProviderClass file:
```
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: spc-tls-test1
spec:
  provider: azure
  secretObjects:                              
  - secretName: secrets-store-driver-test1          
    type: kubernetes.io/tls
    data:
    - objectName: ingress-tls-test1
      key: tls.key
    - objectName: ingress-tls-test1
      key: tls.crt
  parameters:
    usePodIdentity: "false"
    keyvaultName: ingress-tls-vault-test1                      
    objects: |
      array:
        - |
          objectName: ingress-tls-test1
          objectType: secret
    tenantId: <directory id of my key vault >
```


Not sure here if my object type should be secret or certificate or something else.

**Comment by aramase** [comment]
@kanukhosla Could you please provide more info on the versions being used and also the auth method? If not using service principal mode, remove the following snippet from the deployment yamls as noted in the documentation:
```
            nodePublishSecretRef:
              name: secrets-store-creds
```

**Comment by kanukhosla** [comment]
I revisited my steps and I guess my ingress controller never got deployed. 

```
$ helm install ingress-nginx/ingress-nginx --generate-name \
>     --namespace ingress-tls-test1 \
>     --set controller.replicaCount=2 \
>     --set controller.nodeSelector."beta\.kubernetes\.io/os"=linux \
>     --set defaultBackend.nodeSelector."beta\.kubernetes\.io/os"=linux
Error: failed to download "ingress-nginx/ingress-nginx" (hint: running `helm repo update` may help)
```

I don't think this should however prevent me from deploying the application. 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-app-one
  labels:
    app: ingress-app-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress-app-one
  template:
    metadata:
      labels:
        app: ingress-app-one
    spec:
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
        - name: secrets-store-inline-vol1
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
        - name: secrets-store-inline-vol1
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "spc-tls-test1"
            nodePublishSecretRef:
              name: secrets-store-driver-test1
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-app-one
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: ingress-app-one
```

and I am using service principal in this demo. 

Thanks for your time.
