### ISSUE TITLE
Possibility to add annotation to secretObjects

### ISSUE THREAD

**Issue by g14como** [Azure/secrets-store-csi-driver-provider-azure#341]
**Describe the solution you'd like**
i didn't found any documentation so im opening this issue, i'd like to have the possibility to annotate the secret object directly from the secret provider class: 
e.g

```
spec:
  provider: azure
  secretObjects:
  - secretName: nginx-cert
    type: kubernetes.io/tls
    annotations:
     annotations1: "MY ANNOTATION"
    data:
    - objectName: nginx
      key: tls.key
    - objectName: nginx
      key: tls.crt
  parameters:
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "CLIENTID YOU OBTAINED ABOVE" 
    keyvaultName: "gebakv"         
    objects:  |
      array:
        - |
          objectName: nginx
          objectType: secret        
    tenantId: "ID OF YOUR AZURE AD TENANT"
```
expected result when i describe the created secret:

```
Name:         nginx-cert
Namespace:    default
Labels:       <none>
Annotations:  annotations1: MY ANNOTATION


Type:  kubernetes.io/tls

Data
====
tls.crt:  0 bytes
tls.key:  0 bytes
```

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):latest
- Azure Key Vault provider version: (use the image tag):latest
- Kubernetes version: (use `kubectl version`):latest
- Cluster type: (e.g. AKS, aks-engine, etc):AKS
