### ISSUE TITLE
Rotation not working

### ISSUE THREAD

**Issue by sousadax12** [Azure/secrets-store-csi-driver-provider-azure#351]
Hello, I am using this project for 6 months this project in production and now I was trying to upgrade my chart a start using the auto-rotation feature. That feature is not working for me, it seems that the helm chart does not recognize the value enableSecretRotation.

```
helm repo add csi-secrets-store-provider-azure https://raw.githubusercontent.com/Azure/secrets-store-csi-driver-provider-azure/master/charts;
	helm upgrade --install csi-secrets-store-provider-azure csi-secrets-store-provider-azure/csi-secrets-store-provider-azure --set logVerbosity=2 --set enableSecretRotation=true --set rotationPollInterval=2m --namespace csi-secrets --create-namespace;

```
I also tried this:
```
helm upgrade --install csi-secrets-store-provider-azure csi-secrets-store-provider-azure/csi-secrets-store-provider-azure --set logVerbosity=2 --set secrets-store-csi-driver.logVerbosity=2 --set secrets-store-csi-driver.enableSecretRotation=true --set secrets-store-csi-driver.rotationPollInterval=2m --namespace csi-secrets --create-namespace;

```

I did not change anything in SecretProviderClass and secrets are being injected:

```
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretClassName }}
spec:
  provider: azure
  secretObjects:
    {{- range $.Values.secretObjects }}
    - secretName: {{ .secretName }}
      type: Opaque
      data:
        {{- range .data }}
        - objectName: {{ .objectName }}
          key: {{ .key }}
        {{- end }}
    {{- end }}
  parameters:
    usePodIdentity: {{ .Values.usePodIdentity | quote }}
    useVMManagedIdentity: "false"
    keyvaultName: {{ .Values.keyvaultName  }}
    cloudName: AzurePublicCloud
    objects: |
      array:
        {{- range $.Values.objects }}
        - |
          objectName: {{  .objectName  }}
          objectType: {{  .objectType  }}
          objectAlias: {{  .objectAlias  }}
        {{- end }}
    tenantId: {{ .Values.tenantId  }}
    resourceGroup: {{ .Values.resourceGroupName }}
    subscriptionId: {{ .Values.subscriptionId  }}
```

These are the logs from the csi driver:
```
I1228 18:36:59.281841       1 main.go:112] Version: v2.0.1-0-g1aaa13aeI1228 18:36:59.281900       1 main.go:122] Attempting to open a gRPC connection with: "/csi/csi.sock"I1228 18:36:59.281935       1 connection.go:151] Connecting to unix:///csi/csi.sockI1228 18:37:02.263485       1 main.go:129] Calling CSI driver to discover driver nameI1228 18:37:02.263542       1 connection.go:180] GRPC call: /csi.v1.Identity/GetPluginInfoI1228 18:37:02.263555       1 connection.go:181] GRPC request: {}I1228 18:37:02.267636       1 connection.go:183] GRPC response: {"name":"secrets-store.csi.k8s.io","vendor_version":"v0.0.18"}I1228 18:37:02.267721       1 connection.go:184] GRPC error: <nil>I1228 18:37:02.267729       1 main.go:139] CSI driver name: "secrets-store.csi.k8s.io"I1228 18:37:02.267761       1 node_register.go:55] Starting Registration Server at: /registration/secrets-store.csi.k8s.io-reg.sockI1228 18:37:02.268067       1 node_register.go:64] Registration Server started at: /registration/secrets-store.csi.k8s.io-reg.sockI1228 18:37:02.268184       1 node_register.go:86] Skipping healthz server because port set to: 0I1228 18:37:02.408996       1 main.go:79] Received GetInfo call: &InfoRequest{}I1228 18:37:02.433730       1 main.go:89] Received NotifyRegistrationStatus call: &RegistrationStatus{PluginRegistered:true,Error:,}
```

I was expecting that the secrets were updated every 2 minutes but nothing happened .... Am I missing something?
