### ISSUE TITLE
failed to get key vault token: nmi response failed with status code: 404

### ISSUE THREAD

**Issue by deepakcse87** [Azure/secrets-store-csi-driver-provider-azure#352]
I am trying to access secrets from azure keyVault in my pod as this article specifies - https://docs.microsoft.com/en-us/azure/key-vault/general/key-vault-integrate-kubernetes.
I am using managed identity path for this purpose.
My configuration templates are:

```
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvname
  namespace: xyzapp
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"                    # using managed identities
    userAssignedIdentityID: ""
    keyvaultName: "msxyz-service-kv"
    objects:  |
      array:
        - |
          objectName: test-sec
          objectType: secret
    objectVersion: ""
    resourceGroup: "xyz-rg"
    subscriptionId: "<my-sub-id>"
    tenantId: "<my-tanent-id>"
  secretObjects:
  - data:
    - key: testkey
      objectName: test-sec
    secretName: testsecname
    type: Opaque

```
```

apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
    name: "xyz-pod-identity"
    namespace: "xyzapp"
spec:
    type: 0
    resourceID: /subscriptions/<id>/resourcegroups/xyz-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/xyz-pod-identity
    clientID: "<...>"
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
    name: azure-pod-identity-binding
    namespace: "xyzapp"
spec:
    azureIdentity: "xyz-pod-identity"
    selector: azure-pod-identity-binding-selector

```
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xyz-serv
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: xyz-serv
  template:
    metadata:
      labels:
        app: xyz-serv # the label for the pods and the deployments
        aadpodidbinding: azure-pod-identity-binding-selector
    spec:
      containers:
      - name: xyz-serv
        image: acrxyz.azurecr.io/xyz-serv:v1
        imagePullPolicy: Always
        volumeMounts:
          - name: secrets-store-inline
            mountPath: "/mnt/secrets-store"
            readOnly: true
        ports:
        - containerPort: 1234 # the application listens to this port
        resources:
          requests: # minimum resources required
            cpu: 500m
            memory: 256Mi
        readinessProbe: # is the container ready to receive traffic?
          httpGet:
            port: 1234
            path: /healthz
        livenessProbe: # is the container healthy?
          httpGet:
            port: 1234
            path: /healthz
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname"

```
Error that I am recieving:

```
Events:
  Type     Reason       Age    From               Message
  ----     ------       ----   ----               -------
  Normal   Scheduled    2m54s  default-scheduler  Successfully assigned xyzapp/xyz-serv-866666cf97-mf9nw to aks-nodepool1-2123
  Warning  FailedMount  74s    kubelet            MountVolume.SetUp failed for volume "secrets-store-inline" : kubernetes.io/csi: mounter.SetupAt failed: rpc error: code = Unknown desc = failed to mount secrets store objects for pod xyzapp/xyz-serv-866666cf97-mf9nw, err: rpc error: code = Unknown desc = failed to mount objects, error: failed to get keyvault client: failed to get key vault token: nmi response failed with status code: 404, err: <nil>
  Warning  FailedMount  51s    kubelet            Unable to attach or mount volumes: unmounted volumes=[secrets-store-inline], unattached volumes=[default-token-5fdks secrets-store-inline]: timed out waiting for the condition
```
