### ISSUE TITLE
Pod Env Vars from SecretProviderClass (envFrom+secretRef) not updated upon deployment

### ISSUE THREAD

**Issue by deyanp** [Azure/secrets-store-csi-driver-provider-azure#368]
**What steps did you take and what happened:**
I am using SecretProviderClass with objectName and objectAlias, with the objectAlias gets mapped to secretObject (objectName), and the latter's (key from yaml and value from azure key vault) gets injected as env vars using envFrom/secretRef. 

I have automatic secretRotation enabled.

I have noticed that if I change the secretObjects.key for example and apply the yaml, then the newly created pod still has an env var with the old key. Only after I redeploy arfter 10 minutes for example the new key is used as env var name ...

**What did you expect to happen:**
New key must be used for the env var name

**Anything else you would like to add:**
I have the feeling this working before I enabled automatic secret rotation, but not sure.

If I apply the same yaml file without any changes a few minutes later, then the env var has the correct name.

**Which access mode did you use to access the Azure Key Vault instance:**
Pod Identity

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): v0.0.17
- Azure Key Vault provider version: (use the image tag): 0.0.10
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`): v1.20.1/v1.19.3
- Cluster type: (e.g. AKS, aks-engine, etc): AKS

```
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: csi-key-vault-func-secrets-svc-xxx-yyy-zzz
spec:
  provider: azure                   
  parameters:
    usePodIdentity: "true"
    keyvaultName: "xxx-yyy-kkk"          # the name of the KeyVault
    objects:  |
      array:
        - |
          objectName: IivvvSvcEventHubConnectionString
          objectAlias: IiVvvSvc_EventHub_ConnectionString
          objectType: secret
    tenantId: "11111111-1111-1111-1111-111111111111"              # the tenant ID of the KeyVault
  secretObjects:                              # [OPTIONAL] SecretObject defines the desired state of synced K8s secret objects
    - secretName: csi-func-secrets-svc-xxx-yyy-zzz                     # name of the Kubernetes Secret object
      type: Opaque                              # type of the Kubernetes Secret object e.g. Opaque, kubernetes.io/tls  
      data: 
      - objectName: IiVvvSvc_EventHub_ConnectionString
        key: IiVvvSvc_EventHub_ConnectionString
---
apiVersion: v1
kind: Service
metadata:
  name: ccc-xxx-yyy-zzz-http
  namespace: default
  annotations:
    osiris.deislabs.io/enabled: "true"
    osiris.deislabs.io/deployment: ccc-xxx-yyy-zzz-http
spec:
  selector:
    app: ccc-xxx-yyy-zzz
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccc-xxx-yyy-zzz
  namespace: default
  labels:
    app: ccc-xxx-yyy-zzz
  annotations:
    osiris.deislabs.io/enabled: "true"
    osiris.deislabs.io/minReplicas: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ccc-xxx-yyy-zzz
  template:
    metadata:
      labels:
        app: ccc-xxx-yyy-zzz
        aadpodidbinding: ccc-pppp-aks-mi
    spec:
      volumes:
        - name: csi-key-vault-func-secrets-svc-xxx-yyy-zzz
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "csi-key-vault-func-secrets-svc-xxx-yyy-zzz"    
      containers:
      - name: ccc-xxx-yyy-zzz
        image: aaaaaaaa.azurecr.io/ccc-xxx-yyy-zzz:999999999999999999999999999
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
<REMOVED>
        envFrom:
        - secretRef:
            name: csi-func-secrets-svc-xxx-yyy-zzz
        env:
<REMOVED>
```
