### ISSUE TITLE
Azure virtual node - ACI support

### ISSUE THREAD

**Issue by Shaked** [Azure/secrets-store-csi-driver-provider-azure#369]
Is it possible to use the CSI driver when using Azure virtual nodes (ACI / virtual kublet)? 

I have tried to install it with helm using the following values.yaml which should allow the daemon to be loaded on the ACI: 

```
linux:
  tolerations:
  - key: virtual-kubelet.io/provider
    operator: Equal
    value: azure
    effect: NoSchedule
enableSecretRotation: true
``` 

However, this fails: 

> csi-secrets-store-provider-azure-1609593758-5n8nc                 0/1     ProviderFailed   0          6m47s

>   Warning  ProviderCreateFailed  2m2s (x15 over 4m47s)  virtual-node-aci-linux/pod-controller  ACI does not support providing args without specifying the command. Please supply both command and args to the pod spec.

I assume that either it's not supported or that I'm doing something completely wrong.

Shaked
