### ISSUE TITLE
Unable to apply ConstructPEMChain feature

### ISSUE THREAD

**Issue by dancs85** [Azure/secrets-store-csi-driver-provider-azure#370]
**What steps did you take and what happened:**
I've deployed a fresh version of the CSI driver + provider using Helm, and cannot get the optional feature ConstructPEMChain to apply.
```
helm repo add csi-secrets-store-provider-azure https://raw.githubusercontent.com/Azure/secrets-store-csi-driver-provider-azure/master/charts
helm install csi-secrets-store-provider-azure/csi-secrets-store-provider-azure --generate-name --namespace csi-secrets-store --set provider.ConstructPEMChain=true
```
I've also tried:
```
helm repo add csi-secrets-store-provider-azure https://raw.githubusercontent.com/Azure/secrets-store-csi-driver-provider-azure/master/charts
helm install csi-secrets-store-provider-azure/csi-secrets-store-provider-azure --generate-name --namespace csi-secrets-store --set ConstructPEMChain=true
```
and I've tried installing the CSI Driver (using Helm) and provider (using kubectl manifest separately):
```
helm repo add secrets-store-csi-driver https://raw.githubusercontent.com/kubernetes-sigs/secrets-store-csi-driver/master/charts
helm install csi-secrets-store secrets-store-csi-driver/secrets-store-csi-driver --namespace csi-secrets-store
kubectl -n csi-secrets-store apply -f csi-secrets-store-provider-azure.yml
```
where the csi-secrets-store-provider-azure.yml contents were:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-secrets-store-provider-azure
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: csi-secrets-store-provider-azure
  name: csi-secrets-store-provider-azure
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: csi-secrets-store-provider-azure
  template:
    metadata:
      labels:
        app: csi-secrets-store-provider-azure
    spec:
      serviceAccountName: csi-secrets-store-provider-azure
      hostNetwork: true
      containers:
        - name: provider-azure-installer
          image: mcr.microsoft.com/oss/azure/secrets-store/provider-azure:0.0.11
          imagePullPolicy: IfNotPresent
          args:
            - --endpoint=unix:///provider/azure.sock
            - --construct-pem-chain=true
          lifecycle:
            preStop:
              exec:
                command:
                  - "rm /provider/azure.sock"
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 50m
              memory: 100Mi
          volumeMounts:
            - mountPath: "/provider"
              name: providervol
            - name: mountpoint-dir
              mountPath: /var/lib/kubelet/pods
              mountPropagation: HostToContainer
      volumes:
        - name: providervol
          hostPath:
            path: "/etc/kubernetes/secrets-store-csi-providers"
        - name: mountpoint-dir
          hostPath:
            path: /var/lib/kubelet/pods
      nodeSelector:
        kubernetes.io/os: linux
```

**What did you expect to happen:**
I expect to see a message in the logs stating ""
The logs do not show this message:
```
I0119 04:35:28.147327       1 main.go:46] Starting Azure Key Vault Provider version: 0.0.11
I0119 04:35:28.148601       1 main.go:91] Listening for connections on address: //provider/azure.sock
```
And the certificate order is incorrect (INTERMEDIATE is first, expecting the matching of the PRIVATE KEY)

**Anything else you would like to add:**
#332 is the PR for the feature

**Which access mode did you use to access the Azure Key Vault instance:**
System Assigned Managed Identity

**Environment:**

- Secrets Store CSI Driver version: 0.0.18
- Azure Key Vault provider version: 0.0.11
- Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:26:42Z", GoVersion:"go1.15", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-16T20:43:08Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Cluster type: AKS
