### ISSUE TITLE
where is the kubernetes secret?

### ISSUE THREAD

**Issue by williamohara** [Azure/secrets-store-csi-driver-provider-azure#384]
**What steps did you take and what happened:**
I followed these instructions https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/docs/ingress-tls.md
I opted NOT to use the ADD podidentity

1. I first installed csi driver:
helm install vault-link csi-secrets-store-provider-azure/csi-secrets-store-provider-azure

2. I created a SecretProviderClass using this:

```
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: my-dev-vault-spc
spec:
  provider: azure
  secretObjects: 
    - secretName: mytls
      type: kubernetes.io/tls
      data:
      - objectName: mycertnamefromvault
        key: tls.key
      - objectName: mycertnamefromvault
        key: tls.crt
  parameters:
    usePodIdentity: "false"                   
    useVMManagedIdentity: "false"             
    userAssignedIdentityID: "my managed identity client id" #Managed identity client id with an access policy set up in my-dev-vault
                                                         
    keyvaultName: "my-dev-vault"          
    cloudName: ""                                
    objects:  |
      array:
        - |
          objectName: mycertnamefromvault
          objectType: secret
          

        
    resourceGroup: "my-dev-vault-rg"     
    subscriptionId: "<my-sub-id>"          
    tenantId: "<my-tennant-id>"   
```                   

Then I install ingress-nginx (using helm with the following pod mounts defined in my values.yaml)

```
extraVolumeMounts: 
    - name: azv-cert-mount
      mountPath: /mnt/secrets-store
      readOnly: true

extraVolumes: 
    - name: azv-cert-mount
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: my-dev-vault-spc
        nodePublishSecretRef:
              name: secrets-store-creds
```

**What did you expect to happen:**
I expect to see a kubernetes secret generated named "mytls"
I do not see the secret

**Anything else you would like to add:**
When i look into the pod created by the ingress-nginx install it does have a mount on it in `/mnt/secrets-store` that does have `mycertnamefromvault` inside of it

**Which access mode did you use to access the Azure Key Vault instance:**
Service Principal (the one with `my managed identity client id`)

**Environment:**

- Secrets Store CSI Driver version: 0.0.12
- Azure Key Vault provider version: 
- Kubernetes version: client version v1.19.3 server version 1.18.14
- Cluster type: aks
