### ISSUE TITLE
Problems with log configurations 

### ISSUE THREAD

**Issue by pierluigilenoci** [Azure/secrets-store-csi-driver-provider-azure#387]
**What steps did you take and what happened:**

* We have configured the pod to generate logs at verbosity 1 (WARNING) but still log type 0 (INFO)

**What did you expect to happen:**

* No more logs are generated for level 0 (INFO) if the level is 1 (WARNING) 

**Anything else you would like to add:**

Chart configuration:
```yaml
logVerbosity: 1
logFormatJSON: true
secrets-store-csi-driver:
  logLevel:
    debug: false
  logVerbosity: 1
  logFormatJSON: true
  livenessProbe:
    logLevel: 1
  enableSecretRotation: true
  rotationPollInterval: 2m
```

Log with verbosity 1 (WARNING) in JSON format
```json
{"ts":1612521013516.2664,"msg":"fetching object from key vault","v":0,"objectName":"[redacted]","objectType":"secret","keyvault":"[redacted]","pod":"[redacted]/[redacted]"}
{"ts":1612521013516.3215,"msg":"using pod identity to retrieve token","v":0,"pod":"[redacted]/[redacted]"}
{"ts":1612521013526.9822,"msg":"successfully acquired access token","v":0,"accessToken":"eyJ0##### REDACTED #####7sQw","clientID":"7cbd##### REDACTED #####5d53","pod":"[redacted]/[redacted]"}
{"ts":1612521013549.5703,"msg":"successfully wrote file","v":0,"file":"[redacted]","pod":"[redacted]/[redacted]"}
```

`verbosity` is `0`

Ref: https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/442

**Which access mode did you use to access the Azure Key Vault instance:**

Pod Identity https://github.com/Azure/aad-pod-identity

**Environment:**

- Secrets Store CSI Driver version: `0.0.19`
- Azure Key Vault provider version: `0.0.12`
- Kubernetes version: `Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"c86ad89b8715ed17fd55b87cbb2888ccc6fa9878", GitTreeState:"clean", BuildDate:"2020-09-25T01:53:27Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}`
- Cluster type: AKS

**Comment by pierluigilenoci** [comment]
@aramase could you please take a look?

**Comment by pierluigilenoci** [comment]
I also tried to set level 2 (ERROR):

Chart configuration:
```yaml
logVerbosity: 2
logFormatJSON: true
secrets-store-csi-driver:
  logLevel:
    debug: false
  logVerbosity: 2
  logFormatJSON: true
  livenessProbe:
    logLevel: 2
  enableSecretRotation: true
  rotationPollInterval: 2m
```

`provider-azure-installer` logs with verbosity 2 (ERROR) in JSON format
```json
{"ts":1612524964758.1375,"msg":"fetching object from key vault","v":0,"objectName":"[redacted]","objectType":"secret","keyvault":"[redacted]","pod":"[redacted]/[redacted]"}
{"ts":1612524964758.1567,"msg":"vaultName: [redacted]\n","v":2}
{"ts":1612524964758.2212,"msg":"using pod identity to retrieve token","v":0,"pod":"[redacted]/[redacted]"}
{"ts":1612524964767.8184,"msg":"successfully acquired access token","v":0,"accessToken":"eyJ0##### REDACTED #####pyAw","clientID":"132a##### REDACTED #####fdc1","pod":"[redacted]/[redacted]"}
{"ts":1612524965008.1086,"msg":"successfully wrote file","v":0,"file":"[redacted]","pod":"[redacted]/[redacted]"}
```

With `verbosity` at level `2` (ERROR), other messages appeared that did not appear before, those of level `2`. It seems that the filter is implemented backward.
