### ISSUE TITLE
Client does not have permission to perform action 'Microsoft.ManagedIdentity/userAssignedIdentities/assign/action'

### ISSUE THREAD

**Issue by vanpyrzericj** [Azure/secrets-store-csi-driver-provider-azure#418]
**What steps did you take and what happened:**
I referenced #66 which appeared to be very similar in nature, however, I am still struggling here since as far as I can tell, the cluster service principal (`cluster_name_agentpool`) **does** have `Managed Identity Operator` assigned to it. The portal's UI for managed identities seems to be inconsistent with showing role permissions. I'm not entirely sure how to confirm this via the cli.

Additionally, I created my custom user-managed identity (which has permissions to access the key vault) in the same resource group as the cluster service principal (RG prefixed with `MC_`).

``
E0301 02:03:27.851395       1 mic.go:1112] failed to apply binding my-namespace/azure-pod-identity-binding-keyvault-cert node aks-systempool-17746234-vmss000001 for pod my-namespace/mydeployment-app-7c6f7656b-l4r7m, error: failed to update identities for aks-systempool-17746234-vmss in MC_myRG_myCluster_eastus, error: compute.VirtualMachineScaleSetsClient#Update: Failure sending request: StatusCode=403 -- Original Error: Code="LinkedAuthorizationFailed" Message="The client 'xxxxx-304' with object id 'xxxxx-304' has permission to perform action 'Microsoft.Compute/virtualMachineScaleSets/write' on scope '/subscriptions/mysubscriptionid/resourceGroups/MC_myRG_myCluster_eastus/providers/Microsoft.Compute/virtualMachineScaleSets/aks-systempool-17746234-vmss'; however, it does not have permission to perform action 'Microsoft.ManagedIdentity/userAssignedIdentities/assign/action' on the linked scope(s) '/subscriptions/mysubscriptionid/overview/resourcegroups/mc_myrg_mycluster_eastus/providers/microsoft.managedidentity/userassignedidentities/myusermanagedidentity or the linked scope(s) are invalid."
``

**Anything else you would like to add:**
Result of running `az aks show -g myRG -n myClusterName --query servicePrincipalProfile.clientId -o tsv` as suggested in #66 is: `msi`

Running this gives me:
`az aks show -g myRG -n myClusterName`

```
"id": "/subscriptions/mySubscriptionId/resourcegroups/myRG/providers/Microsoft.ContainerService/managedClusters/myClusterName",
  "identity": {
    "principalId": "xxxxx-30fa",
    "tenantId": "xxxxx-97",
    "type": "SystemAssigned",
    "userAssignedIdentities": null
  },
  "identityProfile": {
    "kubeletidentity": {
      "clientId": "xxxxx-2fcb",
      "objectId": "xxxxx-304", //this is what is mentioned above in the error logs
      "resourceId": "/subscriptions/mySubscriptionId/resourcegroups/MC_myRG_myCluster_eastus/providers/Microsoft.ManagedIdentity/userAssignedIdentities/myClusterName-agentpool"
    }
  },
  "kubernetesVersion": "1.18.10"
```

**Environment:**
- Cluster type: (e.g. AKS, aks-engine, etc): AKS

**Comment by aramase** [comment]
@vanpyrzericj This is the doc on how to find the cluster identity/service principal that'll be used by pod identity for performing identity assignment/un-assignments in the cluster: https://azure.github.io/aad-pod-identity/docs/getting-started/role-assignment/. Based on the cluster type, you can get the correct clientID and assign it the required permissions as mentioned in the doc. After performing the role assignments, you would need to restart the pod identity components for the changes to take effect. 

From the snippet you posted above, the AKS cluster is using managed identity instead of SP. So all the required role assignments for pod identity are to be performed for that managed identity client id.

**Comment by vanpyrzericj** [comment]
@aramase Running the identity assignment script yielded this error message:
`Failed to connect to MSI. Please make sure MSI is configured correctly.
Get Token request returned: <Response [400]>`

**Comment by aramase** [comment]
@vanpyrzericj Could you post the AzureIdentity yaml that you're applying in the cluster? In the error message the resource id for the user-assigned managed identity is `/subscriptions/mysubscriptionid/overview/resourcegroups/mc_myrg_mycluster_eastus/providers/microsoft.managedidentity/userassignedidentities/myusermanagedidentity`.

However user-assigned managed identity resourceID format is /subscriptions/mysubscriptionid/~overview~/resourcegroups/mc_myrg_mycluster_eastus/providers/microsoft.managedidentity/userassignedidentities/myusermanagedidentity

It looks like the configure resourceID in the `AzureIdentity` is wrong.

**Comment by vanpyrzericj** [comment]
Ah, yes, removing "overview" from the resourceId solved this. However, now its unable to find the secret provider:
```
message: 'Error: secret "azure-sync" not found'
```

Despite the fact that both the secret provider as well as the secret provider pod status (matching the name of the pod) are both there, and exist in the same namespace as the secret provider "azure-sync":

```
PS C:\Users\evanp> kubectl get Secretproviderclasspodstatus --namespace stagehub-development
NAME                                                            AGE
stagehub-app-5f87bf7577-bxzkm-stagehub-development-azure-sync   29s
PS C:\Users\evanp> kubectl get secretproviderclass --namespace stagehub-development
NAME         AGE
azure-sync   2m9s
```

**Comment by aramase** [comment]
@vanpyrzericj Where is that error? Can you post the `SecretProviderClass` and pod yaml that's being applied to the cluster? I see the `Secretproviderclasspodstatus` has been created for the pod `stagehub-app-5f87bf7577-bxzkm` in `stagehub-development` namespace which means there was no error in the mount.

**Comment by vanpyrzericj** [comment]
@aramase So all the secrets in my keyvault are accessible via the KeyVault provider in my ASP.NET Core application. (Fixing the `/overview/` resolved that).

However, one of my secrets (`firebaseconfig`) is the **contents** of a json file. What I'd like to do is mount _just that secret_ in a folder accessible to my application. This is because Google Firebase requires me to reference a file with their json config in the file (they don't allow just adding the contents to a environmental variable, for example). Its a known bug in their framework.

Is this possible? The file extension doesn't have to me `.json` I think - as long as its a file it can read, I think it will accept it.

Deployment YAML:
```yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: stagehub-app
  namespace: myNamespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: my-app
      app.kubernetes.io/name: my-app
  template:
    metadata:
      labels:
        aadpodidbinding: azure-pod-identity-binding-selector-keyvault-cert
        app.kubernetes.io/instance: my-app
        app.kubernetes.io/name: my-app
    spec:
      volumes:
        - name: firebase-secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: azure-sync
            nodePublishSecretRef:
              name: firebaseconfig
      containers:
        - name: stagehub-app
          image: '----'
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
          resources: {}
          volumeMounts:
            - name: firebase-secrets-store-inline
              readOnly: true
              mountPath: /app/firebasekv
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
```

SecretProdiverClass YAML:
```yaml
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-sync
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: "xxxx-194"
    keyvaultName:
      "myKVName"
    objects: |
      array:
        - |
          objectName: firebaseconfig
          objectType: secret
    resourceGroup: "myKeyVaultRG"
    subscriptionId: "xxxx-c32"
    tenantId: "xxxx-c97"
```

Message from Pod:
```
MountVolume.SetUp failed for volume "firebase-secrets-store-inline" : fetching
NodePublishSecretRef myNamespace/firebaseconfig failed:
kubernetes.io/csi: failed to find the secret firebaseconfig in the namespace
myNamespace with error: secrets "firebaseconfig" not found
```
