### ISSUE TITLE
K8S secrets are not created from Azure Key Vault

### ISSUE THREAD

**Issue by mchudinov** [Azure/secrets-store-csi-driver-provider-azure#419]
Kubernetes secrets are not created after deployment of SecretProviderClass.
manifest:
```
kind: SecretProviderClass
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
metadata:
  name: azure-tlscsi
spec:
  provider: azure
  secretObjects:                                
  - secretName: certificate-nginx-ingress
    type: kubernetes.io/tls
    data: 
    - objectName: EIKPLATFORM-IO-KEY
      key: tls.key
    - objectName: EIKPLATFORM-IO-CRT
      key: tls.crt
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"          
    userAssignedIdentityID: "....."           
    keyvaultName: "kv-healthcheck"                         
    objects:  |
      array:
        - |
          objectName: EIKPLATFORM-IO-CRT
          objectType: secret                  
        - |
          objectName: EIKPLATFORM-IO-KEY
          objectType: secret          
    resourceGroup: "rg-healthcheck"                            
    subscriptionId: "....." 
    tenantId: "......"      
```

**What did you expect to happen:**
Secret **certificate-nginx-ingress** expected to be created after deployment of a manifest file.

**Which access mode did you use to access the Azure Key Vault instance:**
[e.g. Service Principal, Pod Identity, User Assigned Managed Identity, System Assigned Managed Identity]
userAssignedIdentityID
Guaranteed it has a proper access to Key Vault as it is used in other oprations.

- Secrets Store CSI Driver version: How to find it?
- Azure Key Vault provider version: How to find it?
- Kubernetes version: 1.17.9
- Cluster type: AKS
