### ISSUE TITLE
Unable to mount a secret yaml file uploaded to Azure Key Vault

### ISSUE THREAD

**Issue by dhananjaya-senanayake** [Azure/secrets-store-csi-driver-provider-azure#428]
**Have you**

- [x] Read [Troubleshooting Guide](https://azure.github.io/secrets-store-csi-driver-provider-azure/troubleshooting/)
- [x] Searched on [GitHub issues](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues) and [Discussions](https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions)

**What steps did you take and what happened:**
- Upload a Kubernetes service account yaml to Azure Key Vault
```
az keyvault secret set --name sample-K8S-SERVICE-ACCOUNT --vault-name test  --file sa.yaml
```
- Secret provider class
```
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: secret-apps-k8s-service-account
spec:
  parameters:
    objects:  |
      array:
        - |
          objectName: sample-K8S-SERVICE-ACCOUNT
          objectType: secret
          objectAlias: APPS_K8S_SERVICE_ACCOUNT
          objectVersion: "e7c93567d639418a9d39988ec1a4d28b"
```
- Deployment yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      component: nginx
  template:
    metadata:
      labels:
        component: nginx
    spec:
     containers:
      - image: nginx
        name: nginx
        volumeMounts:
        - mountPath: /service-account.yaml
          name: secret-apps-k8s-service-account
          readOnly: true
          subPath: APPS_K8S_SERVICE_ACCOUNT
     volumes:
     - name: secret-apps-k8s-service-account
       csi:
         driver: secrets-store.csi.k8s.io
         readOnly: true
         volumeAttributes:
           secretProviderClass: secret-apps-k8s-service-account
         nodePublishSecretRef:
           name: csi-secret-store-azure
     serviceAccountName: default
```
- The pod is in container creating state.
```
nginx-66d755fcb6-8v9w2                              0/1     ContainerCreating   0          23m
```
- Events
```
Events:
  Type     Reason       Age                   From               Message
  ----     ------       ----                  ----               -------
  Normal   Scheduled    24m                   default-scheduler  Successfully assigned default/nginx-66d755fcb6-8v9w2 to aks-defaultnp-49312751-vmss00006u
  Warning  FailedMount  7m8s (x2 over 22m)    kubelet            Unable to attach or mount volumes: unmounted volumes=[secret-apps-k8s-service-account], unattached volumes=[default-token-jcf4b secret-apps-k8s-service-account]: timed out waiting for the condition
  Warning  FailedMount  2m34s (x8 over 20m)   kubelet            Unable to attach or mount volumes: unmounted volumes=[secret-apps-k8s-service-account], unattached volumes=[secret-apps-k8s-service-account default-token-jcf4b]: timed out waiting for the condition
  Warning  FailedMount  2m27s (x19 over 24m)  kubelet            MountVolume.SetUp failed for volume "secret-apps-k8s-service-account" : rpc error: code = Unknown desc = provider not set in default/secret-apps-k8s-service-account
```

- When another secret is pointed out to the secret provider class ( which is not a file ), no issue is encountered.

**What did you expect to happen:**
CSI to mount the secret file in the key vault to the Pod.

**Anything else you would like to add:**
N/A

**Which access mode did you use to access the Azure Key Vault instance:**
Service Principal

**Environment:**

- Secrets Store CSI Driver version: `mcr.microsoft.com/oss/kubernetes-csi/secrets-store/driver:v0.0.19`
- Azure Key Vault provider version: `mcr.microsoft.com/oss/azure/secrets-store/provider-azure:0.0.12`
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`):
```
❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T18:49:28Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.14", GitCommit:"5de7fd1f9555368a86eb0f8f664dc58055c17269", GitTreeState:"clean", BuildDate:"2021-01-18T09:31:01Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
```
❯ kubectl get nodes -owide
NAME                                STATUS   ROLES   AGE    VERSION    INTERNAL-IP    EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
aks-defaultnp-49312751-vmss00003b   Ready    agent   164d   v1.18.14   172.20.0.4     <none>        Ubuntu 18.04.5 LTS   5.4.0-1036-azure   docker://19.3.14
aks-defaultnp-49312751-vmss00004o   Ready    agent   138d   v1.18.14   172.20.1.114   <none>        Ubuntu 18.04.5 LTS   5.4.0-1036-azure   docker://19.3.14
aks-defaultnp-49312751-vmss00005j   Ready    agent   115d   v1.18.14   172.20.0.6     <none>        Ubuntu 18.04.5 LTS   5.4.0-1036-azure   docker://19.3.14
aks-defaultnp-49312751-vmss000069   Ready    agent   76d    v1.18.14   172.20.0.126   <none>        Ubuntu 18.04.5 LTS   5.4.0-1036-azure   docker://19.3.14
aks-defaultnp-49312751-vmss00006a   Ready    agent   76d    v1.18.14   172.20.0.248   <none>        Ubuntu 18.04.5 LTS   5.4.0-1036-azure   docker://19.3.14
aks-defaultnp-49312751-vmss00006k   Ready    agent   52d    v1.18.14   172.20.1.175   <none>        Ubuntu 18.04.5 LTS   5.4.0-1036-azure   docker://19.3.14
aks-defaultnp-49312751-vmss00006r   Ready    agent   23d    v1.18.14   172.20.1.236   <none>        Ubuntu 18.04.5 LTS   5.4.0-1036-azure   docker://19.3.14
aks-defaultnp-49312751-vmss00006s   Ready    agent   11d    v1.18.14   172.20.3.151   <none>        Ubuntu 18.04.5 LTS   5.4.0-1036-azure   docker://19.3.14
aks-defaultnp-49312751-vmss00006u   Ready    agent   11d    v1.18.14   172.20.0.187   <none>        Ubuntu 18.04.5 LTS   5.4.0-1040-azure   docker://19.3.14
aks-defaultnp-49312751-vmss00006v   Ready    agent   11d    v1.18.14   172.20.1.53    <none>        Ubuntu 18.04.5 LTS   5.4.0-1036-azure   docker://19.3.14
```
- Cluster type: `AKS`
