### ISSUE TITLE
Secret from store refuses to pull latest version

### ISSUE THREAD

**Issue by connor4312** [Azure/secrets-store-csi-driver-provider-azure#437]
**Have you**

- [x] Read [Troubleshooting Guide](https://azure.github.io/secrets-store-csi-driver-provider-azure/troubleshooting/)
- [x] Searched on [GitHub issues](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues) and [Discussions](https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions)

**What steps did you take and what happened:**

1. Updated the value of an existing secret in the keyvault
2. `kubectl delete secret <secret>`, when it recreated it used the old value.

I tried several things that I've had to do before to 'kick it' to get it working

1. I tried deleting the secrets-store-provider-azure and secrets-store-csi-driver pods, then deleting the secret. It still pulled the old value.
2. I tried disabling the old version of the secret in the azure portal, then doing 1. It still pulled the old value.
3. I tried explicitly updating the SecretProviderClass to point `objectVersion` to the new secret version, then doing 1. It still pulled the old value.
4. I [upgraded](https://azure.github.io/secrets-store-csi-driver-provider-azure/upgrading/) to make sure I wasn't out of date.
5. I tried going to bed and doing all this again 9 hours later, no luck.

**What did you expect to happen:**

I expected eventually for the secret value to update.

**Anything else you would like to add:**

No suspicious error logs, only "reconcile started" and "reconcile completed" in the driver. If it matters at all, the old and the new secret values are precisely the same length.

Config subset:

```yaml
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: <name>
spec:
  provider: azure
  secretObjects:
    - data:
      - key: mySecret
        objectName: mySecret
      secretName: apisecrets
      type: Opaque
  parameters:
    resourceGroup: "<name>"
    subscriptionId: "<guid>"
    tenantId: "<guid>"
    keyvaultName: "<name>"  
    userAssignedIdentityID: "<guid>"
    
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    cloudName: ""
    cloudEnvFileName: ""
    objects:  |
      array:
        - |
          objectName: mySecret
          objectType: secret
          objectVersion: "91a53ae..."
```

**Which access mode did you use to access the Azure Key Vault instance:**

User Assigned Managed Identity

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): v0.0.20
- Azure Key Vault provider version: (use the image tag): 0.0.13
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`): v1.18.14
- Cluster type: (e.g. AKS, aks-engine, etc): AKS

**Comment by aramase** [comment]
@connor4312 I see you have the objectVersion defined
```yaml
          objectVersion: "91a53ae..."
```

Is that the old object version? If object version is defined, then the provider will only pull that version. If you want to always get the latest, then the version should be empty.

https://azure.github.io/secrets-store-csi-driver-provider-azure/getting-started/usage/#create-your-own-secretproviderclass-object

objectVersion | no | version of a Key Vault object, if not provided, will use latest | ""
-- | -- | -- | --

**Comment by connor4312** [comment]
No, that's the new object version. It was previously empty and I tried specifying the new version to get it to pull explicitly.

**Comment by aramase** [comment]
@connor4312 The Kubernetes secret is a mirror of the pod mount (https://secrets-store-csi-driver.sigs.k8s.io/topics/sync-as-kubernetes-secret.html). So until the pod mount has the old value, that's what will be used for the Kubernetes secret. You'll need to restart the pod after deleting the Kubernetes secret. 

Or you can use the secret autorotation feature and the CSI driver will automatically update the mount and Kubernetes secret with the new version periodically: https://secrets-store-csi-driver.sigs.k8s.io/topics/secret-auto-rotation.html

**Comment by aramase** [comment]
If you're not using the autorotation feature, the steps are documented here: https://secrets-store-csi-driver.sigs.k8s.io/known-limitations.html#how-to-fetch-the-latest-content-with-release-v0014-and-earlier-or-without-auto-rotation-feature-enabled

**Comment by connor4312** [comment]
Thanks, autorotation did the trick!

It'll be great once that becomes the default, it'll save a lot of pain for others 😄

**Comment by Shaked** [comment]
@aramase 

> Or you can use the secret autorotation feature and the CSI driver will automatically update the mount and Kubernetes secret with the new version periodically: https://secrets-store-csi-driver.sigs.k8s.io/topics/secret-auto-rotation.html

Do I need to do anything special regarding this? 

I have installed the chart as explained: 

```
╰─$  helm -n devops ls | grep csi-secret
csi-secrets-store-provider-azure     	devops   	11      	2021-05-11 09:11:24.859690406 +0000 UTC	deployed	csi-secrets-store-provider-azure-0.0.18                                                                     	0.0.14
``` 

```
─$ helm -n devops get values csi-secrets-store-provider-azure
USER-SUPPLIED VALUES:
enableSecretRotation: true
rotationPollInterval: 2m
```

But it seems like secrets are not being updated: 

```
kubectl get secretProviderClass clearml-agent-spc -o yaml
...
    objects: |
      array:
        - |
          objectAlias: clearml.conf
          objectName: hosted-clearml-conf
          objectType: secret
...
 provider: azure
  secretObjects:
  - data:
    - key: clearml.conf
      objectName: clearml.conf
    secretName: hosted-clearml-conf
...
```

```
status:
  mounted: true
  objects:
  - id: secret/hosted-clearml-conf
    version: a954692d5d864af0a3007f20310cc50e
```

While: 

```
$ az keyvault secret list-versions --vault-name ourvault --name hosted-clearml-conf | jq -r ".[].id"
https://ourvault.vault.azure.net/secrets/hosted-clearml-conf/87fe67f39f1b46abb00d5e36112f8b6f
https://ourvault.vault.azure.net/secrets/hosted-clearml-conf/a954692d5d864af0a3007f20310cc50e
```

The newest version is different.

Checking the logs from the controller shows only

> reconcile started
> reconcile complete

of different pods. 

Any idea what am I doing wrong? 

Thank you
Shaked
