### ISSUE TITLE
secret sync to kubernetes.io/dockercfg and kubernetes.io/dockerconfigjson not working

### ISSUE THREAD

**Issue by WilfriedWeidner** [Azure/secrets-store-csi-driver-provider-azure#450]
Hi all,

**What steps did you take and what happened:**
I'm currently using the TLS secret sync with our key vault and this is working well.   
Now I want use the sync feature with the secret type kubernetes.io/dockerconfigjson or kubernetes.io/dockercfg  
I found this [docuemtation](https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/e8bd366889bb160e148a87a6ed891798a52caf4e/website/content/en/configurations/sync-with-k8-secretes.md) but no example.

I setup the secret in the key vault and it will be mounted in my test pod but the secret will be not synced.
(Or must it setup in an other section as secret? The certificate does also not working if it in secrets)

here the SecretProviderClass is:
````yaml
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: my-kv
spec:
  provider: azure
  secretObjects:                            # secretObjects defines the desired state of synced K8s secret objects
  - secretName: acr-secret
    type: kubernetes.io/dockercfg
    data: 
    - objectName: acr-secret
      key: "dockercfg"
  parameters:
    usePodIdentity: "true"                   # [OPTIONAL] if not provided, will default to "false"
    keyvaultName: "my-kv"  # the name of the KeyVault
    objects: |
      array:
        - |
          objectName: acr-secret
          objectType: secret
          objectVersion: ""
    resourceGroup: "my-rg"
    subscriptionId: "<id>"
    tenantId: "<id>"                 # the tenant ID of the KeyVault
````

In the pod: csi-secret-provider-secrets-store-csi-driver (secrets-store) I found this errors:

with type: kubernetes.io/dockercfg
````
E0316 06:10:27.774953       1 secretproviderclasspodstatus_controller.go:304] "failed to create Kubernetes secret" err="Secret \"my-secret\" is invalid: data[.dockercfg]: Required value" spc="my-kv" pod="my-pod-7c878b8fd5-q74qx" secret="my-secret" spcps="...."
````

with type: kubernetes.io/dockerconfigjson
````
E0315 17:17:03.328111       1 secretproviderclasspodstatus_controller.go:304] "failed to create Kubernetes secret" err="Secret \"my-secret\" is invalid: data[.dockerconfigjson]: Required value" spc="my-kv" pod="my-pod-7c878b8fd5-6j7ts" secret="my-secret" spcps="...."
````
I try all combinations for the secret value but I get always this errors.

**What did you expect to happen:**

I expect a kubernetes secret type: kubernetes.io/dockerconfigjson or kubernetes.io/dockercfg like the tls secret. :-)

**Anything else you would like to add:**

**Which access mode did you use to access the Azure Key Vault instance:**
[e.g. Service Principal, Pod Identity, User Assigned Managed Identity, System Assigned Managed Identity]
I'm using the managed identity which also used by the certificate.

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): secrets-store/driver:v0.0.20 csi-node-driver-registrar:v2.1.0
- Azure Key Vault provider version: (use the image tag): provider-azure:0.0.13
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`): 
````
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", 
GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"14f897abdc7b57f0850da68bd5959c9ee14ce2fe", GitTreeState:"clean", BuildDate:"2021-01-22T17:29:38Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

NAME                                STATUS   ROLES   AGE     VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE                         KERNEL-VERSION     CONTAINER-RUNTIME
aks-nodepool1-30980134-vmss000000   Ready    agent   3d14h   v1.19.7   10.240.0.4     <none>        Ubuntu 18.04.5 LTS               5.4.0-1040-azure   containerd://1.4.3+azure
aksnpwin000000                      Ready    agent   3d14h   v1.19.7   10.240.0.255   <none>        Windows Server 2019 Datacenter   10.0.17763.1757    docker://19.3.14
````

- Cluster type: (e.g. AKS, aks-engine, etc): AKS

best regards,

Wilfried

**Comment by aramase** [comment]
@WilfriedWeidner For secret of type `kubernetes.io/dockercfg`, the kubernetes secret key required is `.dockercfg` and for `kubernetes.io/dockercfgjson` it is `.dockercfgjson`. 

More info on the data key name here: 
https://kubernetes.io/docs/concepts/configuration/secret/#docker-config-secrets

You can store the json blob with the credentials in keyvault. For example, I uploaded this blob as a secret in keyvault: 
```json
{"auths":{"https://index.docker.io/v1/":{"username":"tiger","password":"pass113","email":"tiger@acme.com","auth":"dGlnZXI6cGFzczExMw=="}}}
```

this is my secret provider class yaml:
```yaml
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-linux
  # namespace: dev
spec:
  provider: azure
  secretObjects:
  - data:
    - key: .dockerconfigjson <--- the key here needs to match the required data key for the secret type as mentioned in kubernetes docs
      objectName: dockerconfigjson
    secretName: dockerconfig
    type: kubernetes.io/dockerconfigjson
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    keyvaultName: "kindkv"
    objects: |
      array:
        - |
          objectName: dockerconfigjson
          objectType: secret
          objectVersion: ""
    tenantId: "<tenant id>"
```
