### ISSUE TITLE
Add nodeaffinity to prevent scheduling on virtual-kubelet nodes

### ISSUE THREAD

**Issue by aramase** [Azure/secrets-store-csi-driver-provider-azure#472]
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Add nodeaffinity to prevent the CSI driver pods from being scheduled on [virtual-kubelet](https://github.com/virtual-kubelet/virtual-kubelet) nodes.

Using [type: virtual-kubelet](https://github.com/virtual-kubelet/virtual-kubelet/blob/master/cmd/virtual-kubelet/internal/commands/root/node.go#L43) label.

```yaml
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - key: type
          operator: NotIn
          values:
          - virtual-kubelet
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
We should approach this by adding an `affinity` field in the values.yaml and then setting this affinity by default in the values file. 

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
- Azure Key Vault provider version: (use the image tag):
- Kubernetes version: (use `kubectl version`):
- Cluster type: (e.g. AKS, aks-engine, etc):
