### ISSUE TITLE
Pods in ContainerCreating state

### ISSUE THREAD

**Issue by ShubhasisMathur** [Azure/secrets-store-csi-driver-provider-azure#474]
Our application pods are not coming up, and are in ContainerCreating state, we tried:
- Re-installed the CSI driver and the SecretProviderClass
-   Re-created the secret needed for connecting to the azure keyvault.
but of no help. Here are the errors we see from kubectl get events:

"Apr 14 11:06:27 aks-mcpdrs1-35797989-1 kubelet[1274]: E0414 11:06:27.642477    1274 nestedpendingoperations.go:301] Operation for "{volumeName:kubernetes.io/csi/492c6f1d-0039-43f0-837b-edc0de3d8715-keyvault podName:492c6f1d-0039-43f0-837b-edc0de3d8715 nodeName:}" failed. No retries permitted until 2021-04-14 11:08:29.642436006 +0000 UTC m=+91700.052184206 (durationBeforeRetry 2m2s). Error: "MountVolume.SetUp failed for volume \"keyvault\" (UniqueName: \"kubernetes.io/csi/492c6f1d-0039-43f0-837b-edc0de3d8715-keyvault\") pod \"yolt3-drs-57764c754d-w6swx\" (UID: \"492c6f1d-0039-43f0-837b-edc0de3d8715\") : rpc error: code = Unknown desc = mount failed: exit status 32\nMounting command: mount\nMounting arguments: -t tmpfs tmpfs /var/lib/kubelet/pods/492c6f1d-0039-43f0-837b-edc0de3d8715/volumes/kubernetes.io~csi/keyvault/mount\nOutput: mount: /var/lib/kubelet/pods/492c6f1d-0039-43f0-837b-edc0de3d8715/volumes/kubernetes.io~csi/keyvault/mount: mount point does not exist.\n"
Apr 14 11:06:34 aks-mcpdrs1-35797989-1 kubelet[1274]: E0414 11:06:34.732293    1274 kubelet.go:1656] Unable to attach or mount volumes for pod "yolt3-drs-57764c754d-w6swx_yolt3-drs(492c6f1d-0039-43f0-837b-edc0de3d8715)": unmounted volumes=[keyvault], unattached volumes=[tls-yolt3drsslvmcp default-token-rbqmz keyvault shared1]: timed out waiting for the condition; skipping pod
Apr 14 11:06:34 aks-mcpdrs1-35797989-1 kubelet[1274]: E0414 11:06:34.732345    1274 pod_workers.go:191] Error syncing pod 492c6f1d-0039-43f0-837b-edc0de3d8715 ("yolt3-drs-57764c754d-w6swx_yolt3-drs(492c6f1d-0039-43f0-837b-edc0de3d8715)"), skipping: unmounted volumes=[keyvault], unattached volumes=[tls-yolt3drsslvmcp default-token-rbqmz keyvault shared1]: timed out waiting for the condition
Apr 14 11:08:29 aks-mcpdrs1-35797989-1 kubelet[1274]: E0414 11:08:29.729849    1274 nestedpendingoperations.go:301] Operation for "{volumeName:kubernetes.io/csi/492c6f1d-0039-43f0-837b-edc0de3d8715-keyvault podName:492c6f1d-0039-43f0-837b-edc0de3d8715 nodeName:}" failed. No retries permitted until 2021-04-14 11:10:31.729815887 +0000 UTC m=+91822.139564087 (durationBeforeRetry 2m2s). Error: "MountVolume.SetUp failed for volume \"keyvault\" (UniqueName: \"kubernetes.io/csi/492c6f1d-0039-43f0-837b-edc0de3d8715-keyvault\") pod \"yolt3-drs-57764c754d-w6swx\" (UID: \"492c6f1d-0039-43f0-837b-edc0de3d8715\") : rpc error: code = Unknown desc = mount failed: exit status 32\nMounting command: mount\nMounting arguments: -t tmpfs tmpfs /var/lib/kubelet/pods/492c6f1d-0039-43f0-837b-edc0de3d8715/volumes/kubernetes.io~csi/keyvault/mount\nOutput: mount: /var/lib/kubelet/pods/492c6f1d-0039-43f0-837b-edc0de3d8715/volumes/kubernetes.io~csi/keyvault/mount: mount point does not exist.\n"
Apr 14 11:08:49 aks-mcpdrs1-35797989-1 kubelet[1274]: E0414 11:08:49.731882    1274 kubelet.go:1656] Unable to attach or mount volumes for pod "yolt3-drs-57764c754d-w6swx_yolt3-drs(492c6f1d-0039-43f0-837b-edc0de3d8715)": unmounted volumes=[keyvault], unattached volumes=[tls-yolt3drsslvmcp default-token-rbqmz keyvault shared1]: timed out waiting for the condition; skipping pod
Apr 14 11:08:49 aks-mcpdrs1-35797989-1 kubelet[1274]: E0414 11:08:49.731929    1274 pod_workers.go:191] Error syncing pod 492c6f1d-0039-43f0-837b-edc0de3d8715 ("yolt3-drs-57764c754d-w6swx_yolt3-drs(492c6f1d-0039-43f0-837b-edc0de3d8715)"), skipping: unmounted volumes=[keyvault], unattached volumes=[tls-yolt3drsslvmcp default-token-rbqmz keyvault shared1]: timed out waiting for the condition
"
I am also attaching pod describe logs for your reference.
[kubectl describe pod.txt](https://github.com/Azure/secrets-store-csi-driver-provider-azure/files/6311300/kubectl.describe.pod.txt)

Please help us!

Thanks in Advance!
Shubhasis

**Comment by ShubhasisMathur** [comment]
@aramase to check.

**Comment by aramase** [comment]
@ShubhasisMathur How is this related to the CSI driver? In the `kubectl describe pod` output I don't see any CSI volume:

```yaml
Volumes:
  keyvault:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
  shared1:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  yolt3shared
    ReadOnly:   false
  tls-yolt3drsslvmcp:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  tls-yolt3drsslvmcp
    Optional:    false
  default-token-rbqmz:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-rbqmz
    Optional:    false
```

The keyvault volume is an `EmptyDir`.

**Comment by ShubhasisMathur** [comment]
@aramase Thanks, I understand that it does show from the pod describe output but we are trying to access our secrets from Azure Keyvault . Here is the kubectl get events which you would like to have a look at:

Mounting arguments: -t tmpfs tmpfs /var/lib/kubelet/pods/492c6f1d-0039-43f0-837b-edc0de36662ggxxx/volumes/kubernetes.io~csi/keyvault/mount
Output: mount: /var/lib/kubelet/pods/492c6f1d-0039-43f0-837b-edc0de3d8715/volumes/kubernetes.io~csi/keyvault/mount: mount point does not exist.
109s    Warning   FailedMount   pod/xxxxxxxx   Unable to attach or mount volumes: unmounted volumes=[keyvault], unattached volumes=[tls-xxxxdrsslvmcp default-token-rxxxxz keyvault shared1]: timed out waiting for the condition

I think this is something related to keyvault connection too but I am not sure. Please advise. 

The cluster in question has the same set up as the other cluster where it works fine.

**Comment by ShubhasisMathur** [comment]
@aramase We could solve the issue after we completely cleaned everything related to the CSI driver on the cluster.
Then installed the provider and driver fresh from this link: https://azure.github.io/secrets-store-csi-driver-provider-azure/getting-started/installation/  

This issue appeared after the cluster was upgraded from 1.19.3. AKS to 1.19.7 version, but strange part is the issue did not appear in the other cluster with similar set up and version upgrade i.e.  from 1.19.3 to 1.19.7 AKS version. 
So the question is, do we need to upgrade CSI driver everytime? are there any best practices that we need to follow so that the issue is not surfaced again ?

**Comment by aramase** [comment]
> @aramase Thanks, I understand that it does show from the pod describe output but we are trying to access our secrets from Azure Keyvault . Here is the kubectl get events which you would like to have a look at:

> Mounting arguments: -t tmpfs tmpfs /var/lib/kubelet/pods/492c6f1d-0039-43f0-837b-edc0de36662ggxxx/volumes/kubernetes.iocsi/keyvault/mount
Output: mount: /var/lib/kubelet/pods/492c6f1d-0039-43f0-837b-edc0de3d8715/volumes/kubernetes.iocsi/keyvault/mount: mount point does not exist.

@ShubhasisMathur Is there any log for this pod in the CSI driver with that error? From the describe output the pod is using an `EmptyDir` for that volume. So in this case the CSI driver wouldn't even be called because that's a non CSI volume.

For example, [this](https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/test/bats/tests/azure/pod-secrets-store-inline-volume-crd.yaml#L18-L21) is what tells the kubelet to call the CSI driver for mount but in the above example you posted, there is no CSI volume in the pod definition. 

```
  keyvault:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime) <---- It's an EmptyDir volume
    Medium:
```

This is a `kubectl describe` output for my pod using the CSI volume:
```yaml
➜ kubectl describe pod busybox-linux-5f479855f7-jn6c4
...
Volumes:
  secrets-store-inline:
    Type:              CSI (a Container Storage Interface (CSI) volume source) <--- volume source is CSI. So only now the CSI driver will be called
    Driver:            secrets-store.csi.k8s.io
    FSType:
    ReadOnly:          true
    VolumeAttributes:      secretProviderClass=azure-linux
  default-token-htlq2:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-htlq2
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  kubernetes.io/os=linux
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
```
