### ISSUE TITLE
Helm installer: Tolerations and node selectors should be propagated to the daemon nodes

### ISSUE THREAD

**Issue by alsastre** [Azure/secrets-store-csi-driver-provider-azure#487]
**Have you**

- [x] Read [Troubleshooting Guide](https://azure.github.io/secrets-store-csi-driver-provider-azure/troubleshooting/)
- [x] Searched on [GitHub issues](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues) and [Discussions](https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions)

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
When deploying to a cluster where a set of nodes has tolerations, we can configure node tolerations for the controller but not for the daemon set that this controller installs (`DaemonSet/csi-secrets-store-csi-driver`). I had to manually edit this daemonset to include the `tolerations:`.

I installed with:
`helm install -f secrets-helm-config.yaml csi csi-secrets-store-provider-azure/csi-secrets-store-provider-azure`
Where the config file contains:
```
linux:
  nodeSelector:
    agentpool: scfnodes
  tolerations:
    - key: "version"
      operator: "Equal"
      value: "1.18"
      effect: "NoSchedule"
```

And the controller nodes were correctly installed in the matching nodes but the `csi-secrets-store-provider-azure` were only installed in the nodes that did not have tolerations.

**What did you expect to happen:**
I was expecting the tolerations to be applied to the `csi-secrets-store-provider-azure` daemonset or have another option on the helm to define them.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Which access mode did you use to access the Azure Key Vault instance:**
[e.g. Service Principal, Pod Identity, User Assigned Managed Identity, System Assigned Managed Identity]
Pod identity but not related to the issue

**Environment:**
Latest helm tag.
- Secrets Store CSI Driver version: (use the image tag):`secrets-store-csi-driver-0.0.21`
- Azure Key Vault provider version: (use the image tag): `csi-secrets-store-provider-azure-0.0.18`
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`): `v1.17.16 & v1.18.17`
- Cluster type: (e.g. AKS, aks-engine, etc): AKS

**Comment by nilekhc** [comment]
Hi @alsastre helm chart of provider has driver chart as dependency. You can provide those override in values.yaml file under `secrets-store-csi-driver` section.

Here is an example override for driver:
```
secrets-store-csi-driver:
  install: true
  linux:
    enabled: true
    nodeSelector:
      agentpool: scfnodes
    tolerations:
      - key: "version"
        operator: "Equal"
        value: "1.18"
        effect: "NoSchedule"
    kubeletRootDir: /var/lib/kubelet
    metricsAddr: ":8080"
    image:
      repository: mcr.microsoft.com/oss/kubernetes-csi/secrets-store/driver
      tag: v0.0.21
      pullPolicy: IfNotPresent
    registrarImage:
      repository: mcr.microsoft.com/oss/kubernetes-csi/csi-node-driver-registrar
      tag: v2.1.0
      pullPolicy: IfNotPresent
    livenessProbeImage:
      repository: mcr.microsoft.com/oss/kubernetes-csi/livenessprobe
      tag: v2.2.0
      pullPolicy: IfNotPresent
```
