### ISSUE TITLE
Error of SecretProviderClass not found on initial resource deployment

### ISSUE THREAD

**Issue by WillooWisp** [Azure/secrets-store-csi-driver-provider-azure#491]
Using latest version 0.0.18 of helm chart.

Why do I always get the following error event of FailedMount when first syncing up the deployment spec below for the first time. The mount works when I check the file contents. Deleting the pod or replicaset and letting it be auto recreated by the deployment does not give the error.

Error:
using MountVolume.SetUp failed for volume "secrets-store-inline" : rpc error: code = Unknown desc = failed to get secretproviderclass csi/azure-keyvault, error: SecretProviderClass.secrets-store.csi.x-k8s.io "azure-keyvault" not found

![image](https://user-images.githubusercontent.com/3296485/116573441-16602200-a90d-11eb-894c-ee9d94d8eaf3.png)

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: create-secrets-from-akv
  labels:
    app: alpine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      labels:
        app: alpine
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: alpine
          image: alpine
          # Just spin & wait forever
          command: [ "/bin/sh", "-c", "--" ]
          args: [ "trap : TERM INT; sleep 9999999999d & wait" ]
          env:
          - name: SECRET
            valueFrom:
              secretKeyRef:
                name: kv-test-secret
                key: password
          volumeMounts:
          - name: secrets-store-inline
            mountPath: "/mnt/secrets-store"
            readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-keyvault"
```
