### ISSUE TITLE
Problem creating secrets in a recreated provider class object 

### ISSUE THREAD

**Issue by assaf-grth** [Azure/secrets-store-csi-driver-provider-azure#506]
I am using the csi helm installation on my AKS cluster
After moving the installation to kube-system namespace the SecretProviderClass object and related secrets were deleted as well

Now when I create a pod mounting the provider, secrets which were supposed to be created based on the secretObjects property are not created

The volume is mounted in the new pod so to my understanding the secrets should be created.

How can I troubleshoot such behavior?

Thanks

**Comment by assaf-grth** [comment]
Yes I did,
However all existing pods using the old secrets are still running
Is it related? I fear that if I'll delete them the system might stop working

I searched for errors in the pods logs and didnt find anything, is there a log to search for related to secrets creation specifcally?

**Comment by aramase** [comment]
> After moving the installation to kube-system namespace the SecretProviderClass object and related secrets were deleted as well

Could you provide more details on this?

> Now when I create a pod mounting the provider, secrets which were supposed to be created based on the secretObjects property are not created

Could you share the following:
1. SecretProviderClass yaml
2. Pod yaml
3. `kubectl describe pod <pod name>` output for the events

Uninstalling the helm charts and redeploying in another namespace will delete the `SecretProviderClass` instances because the crds in the template dir in helm (which we're planning to move to crds folder in the future).

**Comment by assaf-grth** [comment]
Details of the pods:
![image](https://user-images.githubusercontent.com/52287325/118156888-8b118100-b422-11eb-8056-1a290dbe7b15.png)

I'm putting here a sample of what's defined so you can verify I understand how to define this:

```
kind: SecretProviderClass
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
metadata:
  name: my-class
  namespace: application
spec:
  provider: azure
  secretObjects:
  - secretName: new-secret
    type: Opaque
    data: 
    - objectName: db-host
      key: DB_HOST
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "11111111"
    keyvaultName: "azure-kv"
    objects: |
      array:
        - |
          objectName: db-host
          objectType: secret
    subscriptionId: "222222222"
    tenantId: "333333"
```
Pod yaml:
```
apiVersion: v1
kind: Pod
metadata:
  name: my-app
  namespace: application
spec:
  containers:
  - env:
    - name: DB_HOST
      valueFrom:
        secretKeyRef:
          key: DB_HOST
          name: new-secret
    image: someimage
    imagePullPolicy: IfNotPresent
    name: my-app
    ports:
    - containerPort: 4100
      protocol: TCP
    volumeMounts:
    - mountPath: /etc/some-secret
      name: some-secret
      readOnly: true
  volumes:
  - csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
          secretProviderClass: my-class
    name: some-secret
```

Pod describe events:
```
Events:
  Type     Reason     Age              From               Message
  ----     ------     ----             ----               -------
  Normal   Scheduled  15s              default-scheduler  Successfully assigned application/api-gateway-svc111 to aks-agentpool-22428647-vmss000001
  Normal   Pulled     7s (x3 over 9s)  kubelet            Container image "afconregistry.azurecr.io/afconsws-cloud-app/cloud/api-gateway-service:0.0.36" already present on machine
  Warning  Failed     7s (x3 over 9s)  kubelet            Error: secret "new-secret" not found
```

Is there a place I can search for some logs describing what is done related to creating secrets?
I can tell that secrets did get created and seen when using kubectl get secrets -n application
It looks like the part of secretObjects in the SecretProviderClass is ignored somehow...

**Comment by assaf-grth** [comment]
Details of the pods:
image

I'm putting here a sample of what's defined so you can verify I understand how to define this:

```
kind: SecretProviderClass
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
metadata:
  name: my-class
  namespace: application
spec:
  provider: azure
  secretObjects:
  - secretName: new-secret
    type: Opaque
    data: 
    - objectName: db-host
      key: DB_HOST
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "11111111"
    keyvaultName: "azure-kv"
    objects: |
      array:
        - |
          objectName: db-host
          objectType: secret
    subscriptionId: "222222222"
    tenantId: "333333"
```

Pod yaml:
```
apiVersion: v1
kind: Pod
metadata:
  name: my-app
  namespace: application
spec:
  containers:
  - env:
    - name: DB_HOST
      valueFrom:
        secretKeyRef:
          key: DB_HOST
          name: new-secret
    image: someimage
    imagePullPolicy: IfNotPresent
    name: my-app
    ports:
    - containerPort: 4100
      protocol: TCP
    volumeMounts:
    - mountPath: /etc/some-secret
      name: some-secret
      readOnly: true
  volumes:
  - csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
          secretProviderClass: my-class
    name: some-secret
```
Pod describe events:
```
Events:
  Type     Reason     Age              From               Message
  ----     ------     ----             ----               -------
  Normal   Scheduled  15s              default-scheduler  Successfully assigned application/apimy-app to aks-agentpool-11111
  Normal   Pulled     7s (x3 over 9s)  kubelet            Container image "someimage" already present on machine
  Warning  Failed     7s (x3 over 9s)  kubelet            Error: secret "new-secret" not found
```

Is there a place I can search for some logs describing what is done related to creating secrets?
I can tell that secrets did get created and seen when using kubectl get secrets -n application
It looks like the part of secretObjects in the SecretProviderClass is ignored somehow...
