### ISSUE TITLE
Warning SecretRotationFailed failed to patch secret xxx-xxxx-xxxxxx with new data, err: timed out waiting for the condition

### ISSUE THREAD

**Issue by deyanp** [Azure/secrets-store-csi-driver-provider-azure#510]
**What steps did you take and what happened:**
Getting errors

**Warning SecretRotationFailed failed to patch secret xxx-xxxx-xxxxxx with new data, err: timed out waiting for the condition**

after upgrading CSI Secrets Store/Azure to versions 0.0.21/0.0.14

**Anything else you would like to add:**
After deleting the secret and recreating the corresponding pod (+secret) the error seems to disappear.

**Which access mode did you use to access the Azure Key Vault instance:**
Pod Identity

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): k8s.gcr.io/csi-secrets-store/driver:v0.0.21
- Azure Key Vault provider version: (use the image tag): mcr.microsoft.com/oss/azure/secrets-store/provider-azure:0.0.14
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`): 1.20.5
- Cluster type: (e.g. AKS, aks-engine, etc): AKS

**Comment by deyanp** [comment]
In the logs of csi-secrets-store pod I see the following:

`E0518 07:03:19.362727       1 reconciler.go:372] "failed to patch secret data" err="secrets \"default/xxx-xxxxx-xxxxxxx\" not found" secret="default/xxx-xxxxx-xxxxxxx" spc="default/xxx-yyyyy-xxxxx-xxxxxxx" controller="rotation"`

where `xxx-xxxxx-xxxxxxx` seems to be the secret name
and `xxx-yyyyy-xxxxx-xxxxxxx` the secretproviderclass name

**Comment by nilekhc** [comment]
Hello @deyanp! Thanks for opening the issue. Could you please let us know what version of `driver` & `provider` you were using before this upgrade? Also the configuration of SPC and pod using the secret will help.

**Comment by deyanp** [comment]
@nilekhc I migrated from

```
k8s.gcr.io/csi-secrets-store/driver:v0.0.20
mcr.microsoft.com/oss/azure/secrets-store/provider-azure:0.0.13
```


SCP and pod def:

```

apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: ccc-kkk-vvvvv-ffff-sssssss-sss-ttt-qqqq
spec:
  provider: azure                   
  parameters:
    usePodIdentity: "true"
    keyvaultName: "ccc-pppp-kk"          # the name of the KeyVault
    objects:  |
      array:
        - |
          objectName: AA-AaaaaWwwJjjjSssssss-sss-ttt
          objectAlias: AaaaaWwwJjjjSssssss
          objectType: secret
        - |
          objectName: AAA-hhhh-jjjj-sss-ttt
          objectAlias: file.json
          objectType: secret
    tenantId: "33333333-3333-4444-9999-eeeeeeeeeeee"              # the tenant ID of the KeyVault
  secretObjects:                              # [OPTIONAL] SecretObject defines the desired state of synced K8s secret objects
    - secretName: ccc-ffff-sssssss-sss-ttt-qqqq                     # name of the Kubernetes Secret object
      type: Opaque                              # type of the Kubernetes Secret object e.g. Opaque, kubernetes.io/tls  
      data: 
      - objectName: AaaaaWwwJjjjSssssss
        key: AaaaaWwwJjjjSssssss
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccc-ttt-qqqq
  namespace: default
  labels:
    app: ccc-ttt-qqqq
  annotations:
    osiris.deislabs.io/enabled: "true"
    osiris.deislabs.io/minReplicas: "1"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ccc-ttt-qqqq
  template:
    metadata:
      labels:
        app: ccc-ttt-qqqq
        aadpodidbinding: ccc-pppp-aaa-mm-sss-ttt
    spec:
      volumes:
        - name: ccc-kkk-vvvvv-ffff-sssssss-sss-ttt-qqqq
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "ccc-kkk-vvvvv-ffff-sssssss-sss-ttt-qqqq"    
      containers:
      - name: ccc-ttt-qqqq
        image: ccccccccccccccc.azurecr.io/ccc-ttt-qqqq:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /api/v1/readiness
            port: 80
          periodSeconds: 15
          timeoutSeconds: 30
        volumeMounts:
        - name: ccc-kkk-vvvvv-ffff-sssssss-sss-ttt-qqqq
          mountPath: "/aaaaa-fffffffff-hhhh/Sssssss/file.json"
          subPath: file.json
          readOnly: true        
        envFrom:
        - secretRef:
            name: ccc-ffff-sssssss-sss-ttt-qqqq
        env:
...

```

Error for this pod once again:

`Warning  SecretRotationFailed  5m28s (x314 over 10h)  csi-secrets-store-rotation  failed to patch ssssss ccc-ffff-sssssss-sss-ttt-qqqq with new data, err: timed out waiting for the condition`

Let me know if you need anything else, I deliberately *not* fixed 3-4 pods/SPC so that I can provide logs/errors ...
