### ISSUE TITLE
pod has unbound immediate PersistentVolumeClaims 

### ISSUE THREAD

**Issue by ibattat** [Azure/secrets-store-csi-driver-provider-azure#53]
Same issue as in k8s v1.15,
As I've seen in the open incident the solution was to upgrade k8s version.
still with the same issue.

Pod events:
pod has unbound immediate PersistentVolumeClaims (repeated 4 times)

PVC in status Pending

This is the configuration

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-secrets-store
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: secrets-store.csi.k8s.io
    readOnly: true
    volumeHandle: kv
    volumeAttributes:
      providerName: "azure"
      keyvaultName: <kv_name>
      objects:  |
        array:                                        
          - |
            objectName: <secret_name>
            objectType: cert                 
            objectVersion: ""                
          - |
            objectName: <secret_name>
            objectType: secret
            objectVersion: ""
      resourceGroup: <resource_grp>
      subscriptionId: <subscription_id> 
      tenantId: <tenant-id>    
    nodePublishSecretRef:
      name: secrets-store-creds
      namespace: <ns_name>
```

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-secrets-store
  namespace: <ns_name>
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Ki
  volumeName: pv-secrets-store
  storageClassName: ""

```---
```
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-deployment
  namespace: <ns_name>
spec:
  replicas: 2
  strategy:
    type: RollingUpdate 
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      deploy: example
  template:
    metadata:
      labels:
        deploy: example
    spec:
      containers:
        - name: nginx
          image: nginx:1.7.9
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https
          volumeMounts:
          - name: config-volume
            mountPath: /etc/nginx
      volumes:
         - name: kv-store
           persistentVolumeClaim:
                claimName: pvc-secrets-store
         - name: config-volume
           configMap:
                name: nginx-config

```---
```
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: <ns_name>
  annotations:
     service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    deploy: example
  ports:
   - port: 80
     name: http
   - port: 443
     name: https

```
