### ISSUE TITLE
unexpected error creating SSL Cert: certificate and private key does not have a matching public key

### ISSUE THREAD

**Issue by johnri** [Azure/secrets-store-csi-driver-provider-azure#561]
## Repro
The "ingress-nginx" container (version 0.47.0) reports the following error

```txt
I0629 00:21:48.488739       7 backend_ssl.go:41] "Syncing Secret" name="codesp/ssl-cert-codesp"
W0629 00:21:48.489084       7 backend_ssl.go:46] Error obtaining X.509 certificate: unexpected error creating SSL Cert: certificate and private key does not have a matching public key: tls: private key does not match public key
```

The SecretProviderClass below creates the k8s secret object codesp/ssl-cert-codesp. 

```yaml
kind: SecretProviderClass
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
metadata:
  name: ssl-cert-codesp-tls-secrets-provider
  namespace: codesp
spec:
  provider: azure
  # https://azure.github.io/secrets-store-csi-driver-provider-azure/configurations/sync-with-k8s-secrets/
  secretObjects:
  - secretName: ssl-cert-codesp
    type: kubernetes.io/tls
    data: 
    - objectName: ssl-cert-codesp
      key: tls.crt
    - objectName: ssl-cert-codesp
      key: tls.key
  parameters:
    usePodIdentity: "true"  # assumes consumer has configured pod identity with Key Vault Secrets User role
    resourceGroup: ****-online-dev 
    keyvaultName: ****-online-dev-kv
    tenantId: 72f988bf-****
    # https://azure.github.io/secrets-store-csi-driver-provider-azure/configurations/getting-certs-and-keys/
    objects: |
      array:
        - |
          objectName: ssl-cert-codesp
          objectAlias: ssl-cert-codesp
          objectType: secret
```

I have downloaded the generated secret from k8s and validated it with openssl and, sure enough, it says they don't match.
What gives?

**Have you**

- [x] Read [Troubleshooting Guide](https://azure.github.io/secrets-store-csi-driver-provider-azure/troubleshooting/)
- [x] Searched on [GitHub issues](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues) and [Discussions](https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions)

**What steps did you take and what happened:**

I tried a variety of combinations in the SecretProviderClass with objectType secret, cert, and key. None produced a valid kubernetes.io/tls. In particular, using objectType "key" resulted in a valid key file mounted on disk, but an empty value in the tls.key. So I revert back to the sample, using type "secret' only for both tls.key and tls.crt.

**What did you expect to happen:**

The k8s secret ssl-cert-codesp should be valid, and the NGINX ingress controller should recognize it as valid.

**Which access mode did you use to access the Azure Key Vault instance:**
Pod Identity / User Assigned

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): mcr.microsoft.com/oss/kubernetes-csi/secrets-store/driver:v0.0.21
- Azure Key Vault provider version: (use the image tag): 
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`):

>Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", >GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", >GoVersion:"go1.15.5", Compiler:"gc", Platform:"windows/amd64"}
>Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", >GitCommit:"6b3f9b283463c1d5a2455df301182805e65c7145", GitTreeState:"clean", BuildDate:"2021-05-19T22:28:47Z", >GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}

>NAME                                 STATUS   ROLES   AGE   VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
>aks-systempool-12603227-vmss000000   Ready    agent   12d   v1.20.7   10.240.0.4     <none>        Ubuntu 18.04.5 LTS   5.4.0-1051-azure   containerd://1.4.4+azure
>aks-systempool-12603227-vmss000001   Ready    agent   12d   v1.20.7   10.240.0.115   <none>        Ubuntu 18.04.5 LTS   5.4.0-1051-azure   containerd://1.4.4+azure
>aks-systempool-12603227-vmss000002   Ready    agent   12d   v1.20.7   10.240.0.226   <none>        Ubuntu 18.04.5 LTS   5.4.0-1051-azure   containerd://1.4.4+azure

- Cluster type: (e.g. AKS, aks-engine, etc): AKS

**Comment by aramase** [comment]
@johnri Thank you for reporting the issue.

Is this a certificate chain? AKV provider for Secrets Store CSI Driver will fetch the certificates and write as is to the mount and sync as K8s secret. In case of chain of certs, the entire chain is written to the mount in the same order as they were uploaded to Key Vault. To have the provider reconstruct the chain in the correct order leaf, intermediate, root you can enable the construct pem chain feature flag as part of the provider: https://azure.github.io/secrets-store-csi-driver-provider-azure/configurations/feature-flags/#construct-pem-chain-feature-flag

**Comment by johnri** [comment]
I'm following [Use the Secrets Store CSI Driver for Kubernetes in an Azure Kubernetes Service (AKS) cluster (preview)](https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver). The json below is from my ARM template. But the AKS RP didn't seem to honoring that (yet), so I also used the Az Cli `az aks addon azure-keyvault-secrets-provider`.

I can try adding "constructPEMChain": "true" to the config section.

```json
{
"addonProfiles":
{
  "azureKeyvaultSecretsProvider": {
    "config": {
      "enableSecretRotation": "false"
    },
    "enabled": true,
    "identity": {
      "clientId": "6ff75455-***",
      "objectId": "38d6b4cc-***",
      "resourceId": "/subscriptions/***/resourcegroups/***/providers/Microsoft.ManagedIdentity/userAssignedIdentities/azurekeyvaultsecretsprovider-***"
    }
  }
}
}
```

**Comment by aramase** [comment]
Synced up with @johnri offline and suggested using the helm charts from this repo to try out the [constructPEMChain](https://azure.github.io/secrets-store-csi-driver-provider-azure/configurations/feature-flags/#construct-pem-chain-feature-flag) feature.

@johnri did you get a chance to try it out?

**Comment by johnri** [comment]
I did not. I ended up installing the Secrets Store Provider manually (via my own helm chart) so that I could better control the outcome. I believe the non-standard option I set were

```yaml
constructPEMChain: true
syncSecret:
    enabled: true
 ```
and even then, I'm not relying on the synch functionality just yet.
