### ISSUE TITLE
Suggestion : Add below YAML to documentation - this would help for users who want to create multiple secrets, which is missing in docs page 

### ISSUE THREAD

**Issue by karthi-s-n** [Azure/secrets-store-csi-driver-provider-azure#565]
```yaml
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-test1
  namespace: test1
spec:
  provider: azure
  secretObjects:
  - data:
    - key: foo
      objectName: secret1
    - key: bar
      objectName: secret2
    - key: key
      objectName: key1
    secretName: foosecret-1
    type: Opaque
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    keyvaultName: "kindkv"
    objects: |
      array:
        - |
          objectName: secret1
          objectType: secret
          objectVersion: ""
        - |
          objectName: secret2
          objectType: secret
          objectVersion: ""
        - |
          objectName: ingress-tls-pfx
          objectType: secret
          objectVersion: ""
          objectFormat: pfx
    tenantId: "72f988bf-86f1-41af-91ab-2d7cd011db47"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: test1
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        # aadpodidbinding: demo
    spec:
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: nginx
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
        env:
          - name: FOO_SECRET1
            valueFrom:
              secretKeyRef:
                name: foosecret-1
                key: bar
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-test1"
            nodePublishSecretRef:
              name: secrets-store-creds
---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-test2
  namespace: test2
spec:
  provider: azure
  secretObjects:
  - data:
    - key: foo
      objectName: secret1
    - key: bar
      objectName: secret2
    - key: key
      objectName: key1
    secretName: foosecret-2
    type: Opaque
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    keyvaultName: "kindkv"
    objects: |
      array:
        - |
          objectName: secret1
          objectType: secret
          objectVersion: ""
        - |
          objectName: secret2
          objectType: secret
          objectVersion: ""
        - |
          objectName: ingress-tls-pfx
          objectType: secret
          objectVersion: ""
          objectFormat: pfx
    tenantId: "72f988bf-86f1-41af-91ab-2d7cd011db47"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: test2
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        # aadpodidbinding: demo
    spec:
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: nginx
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
        env:
          - name: FOO_SECRET1
            valueFrom:
              secretKeyRef:
                name: foosecret-2
                key: bar
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-test2"
            nodePublishSecretRef:
              name: secrets-store-creds
```

_Originally posted by @aramase in https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/216#issuecomment-686275309_
