### ISSUE TITLE
Volume Mounted Configuration Tree

### ISSUE THREAD

**Issue by dkirrane** [Azure/secrets-store-csi-driver-provider-azure#569]
**Describe the solution you'd like**

Is it possible to mount secrets into the container file system like the following
```
mnt/
 +- secrets-store/
     +- redis/
     |  +- hostname
     |  +- port
     |  +- primary-key
```

Currently, I have this
```
kubectl exec $POD_NAME -- ls /mnt/secrets-store
redis-hostname
redis-port
redis-primary-key
```

The reason I want a tree is to use `spring.config.import=configtree:/mnt/secrets-store` which would map to `redis.hostname`, `redis.port` and `redis.primary-key` properties in Spring.

**SecretProviderClass.yaml**
```yaml
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: foo
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"
    keyvaultName: XXXXXXXXXX
    tenantId: XXXXXXXXXXXXX
    objects:  |
      array:
        - |
          objectName: redis-hostname
          objectType: secret
        - |
          objectName: redis-port
          objectType: secret
        - |
          objectName: redis-primary-key
          objectType: secret
        - |
          objectName: redis-secondary-key
          objectType: secret
```

**Anything else you would like to add:**
Helm Chart: `csi-secrets-store-provider-azure-0.0.20`

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): `mcr.microsoft.com/oss/kubernetes-csi/secrets-store/driver:v0.0.23`
- Azure Key Vault provider version: (use the image tag): `mcr.microsoft.com/oss/azure/secrets-store/provider-azure:0.0.16`
- Kubernetes version: (use `kubectl version`): `1.19.11`
- Cluster type: (e.g. AKS, aks-engine, etc): `AKS`

**Comment by nilekhc** [comment]
Hello  @dkirrane You can simply update the volume [mountPath](https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/715d9f045610c2d3f76c02cc18968e08981d362a/examples/service-principal/pod-inline-volume-service-principal.yaml#L15) of your workload and update your secretproviderclass to desired secret name. You can also use [alias](https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/715d9f045610c2d3f76c02cc18968e08981d362a/examples/sync-as-kubernetes-secret/synck8s_v1alpha1_secretproviderclass.yaml#L23) to name the secret being mounted. HTH.

**Comment by dkirrane** [comment]
@nilekhc yip your solution would work for one set of secrets but if I needed a few it means multiple volume mounts and `SecretProviderClass`s I believe. e.g. If I wanted to have one volume `/mnt/secrets-store` with a structure like below:
```
mnt
└── secrets-store
    ├── postgres
    │   ├── hostname
    │   ├── password
    │   ├── port
    │   └── username
    └── redis
        ├── hostname
        ├── port
        ├── primary-key
        └── secondary-key
    ├── etc...        
```

**Comment by nilekhc** [comment]
@dkirrane With latest release, secret store CSI driver is now by default writing secret content to mount instead of provider. With this enabled you can use `objectAlias` in `SecretProviderClasss` and manage the path of your secrets. You can do something like :

```yaml
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: foo
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"
    keyvaultName: XXXXXXXXXX
    tenantId: XXXXXXXXXXXXX
    objects:  |
      array:
        - |
          objectName: redis-hostname
          objectType: secret
          objectAlias: redis/hostname
        - |
          objectName: redis-port
          objectType: secret
          objectAlias: redis/port
        - |
          objectName: redis-primary-key
          objectType: secret
          objectAlias: postgres/hostname
        - |
          objectName: redis-secondary-key
          objectType: secret
          objectAlias: postgres/password
```

Note: `objectName` must be same as secret name configured in KeyVault. Also I would recommend using latest `v0.2.0` for both driver and provider.
