### ISSUE TITLE
File matching objectName not found in the pod

### ISSUE THREAD

**Issue by pierluigilenoci** [Azure/secrets-store-csi-driver-provider-azure#580]
**Have you**

- [x] Read [Troubleshooting Guide](https://azure.github.io/secrets-store-csi-driver-provider-azure/troubleshooting/)
- [x] Searched on [GitHub issues](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues) and [Discussions](https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions)

**What steps did you take and what happened:**

We have installed the software in this way:

Secret Provider Class:
```yaml
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: docker-config
  namespace: [REDACTED]
spec:
  secretObjects:
  - data:
    - key: docker-config
      objectName: DOCKER-CONFIG
    secretName: docker-config
    type: Opaque
  provider: azure
  parameters:
    usePodIdentity: "true"
    keyvaultName:  [REDACTED]
    objects:  |
      array:
        - |
          objectName: DOCKER-CONFIG
          objectType: secret
          objectAlias: "config.json"
          objectVersion: ""
    tenantId: [REDACTED]
```

Pod:
```yaml
[..]
    volumeMounts:
    - mountPath: /root/.docker/
      name: docker-config
      readOnly: true
    volumes:
    - csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: docker-config
        name: docker-config
[..]
```

In this way, the pod starts and inside the `/root/.docker/` folder we find the secret `config.json`.
So far everything is fine but the `describe` of the pod give these error messages:

```shell
Warning  SecretRotationFailed  4m2s (x33 over 9m5s)    csi-secrets-store-rotation    failed to get data in spc [REDACTED]/docker-config for secret docker-config, err: file matching objectName DOCKER-CONFIG not found in the pod
Warning  FailedToCreateSecret  3m57s (x17 over 9m25s)  csi-secrets-store-controller  failed to get data in spc [REDACTED]/docker-config for secret docker-config, err: file matching objectName DOCKER-CONFIG not found in the pod
```

It seems that the procedure of rotation and creation of the secret does not take into account the configured alias.

**What did you expect to happen:**

I expect to have the secret properly valued and rotated. Without any error message. 

**Anything else you would like to add:**

Nothing

**Which access mode did you use to access the Azure Key Vault instance:**

We use AAD Pod Identity https://github.com/Azure/aad-pod-identity

In the specific case, however, integration with Azure is not the problem. 

**Environment:**

- Secrets Store CSI Driver version: 0.0.23 (Helm Chart Version 0.0.20)
- Azure Key Vault provider version: 0.0.16 (Helm Chart Version 0.0.20)
- Kubernetes version: v1.20.5
- Cluster type: AKS
