### ISSUE TITLE
Create secret for usage in other resources than pods

### ISSUE THREAD

**Issue by twendt** [Azure/secrets-store-csi-driver-provider-azure#593]
The secret-store-driver works great for mounting secrets in Pods, but sometimes we use other resources like GitRepository from the flux2 project. Within the GitRepository we can reference a secret for the authentication.

Here is an example:
```
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  gitImplementation: libgit2
  interval: 1m0s
  ref:
    branch:  main
  secretRef:
    name: flux-system
  timeout: 20s
 url: https://dev.azure.com/.....
```

Currently I don't see a way how I could create a Kubernetes secret from a Key Vault secret without using a Pod. Is this somehow already possible or planed in a future release?
