### ISSUE TITLE
Multiple user assigned identities exist, please specify the clientId / resourceId of the identity in the token request

### ISSUE THREAD

**Issue by lucianoviola** [Azure/secrets-store-csi-driver-provider-azure#598]
**Have you**

- [ x] Read [Troubleshooting Guide](https://azure.github.io/secrets-store-csi-driver-provider-azure/troubleshooting/)
- [ x] Searched on [GitHub issues](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues) and [Discussions](https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions)

**What steps did you take and what happened:**
Out of the blue, I'm getting issues mounting secrets store objects: 

> I0730 23:25:44.028872       1 nodeserver.go:300] "Using grpc client" provider="azure" pod="scentid-api-6867bbbd4-pkwmd"
> I0730 23:25:44.105899       1 nodeserver.go:73] "unmounting target path as node publish volume failed" targetPath="/var/lib/kubelet/pods/1dbf181a-990c-4e1a-9bcd-c9c2c97761e0/volumes/kubernetes.io~csi/secrets/mount" pod="default/scentid-api-6867bbbd4-pkwmd"
> E0730 23:25:44.109576       1 utils.go:79] GRPC error: failed to mount secrets store objects for pod default/scentid-api-6867bbbd4-pkwmd, err: rpc error: code = Unknown desc = failed to mount objects, error: failed to get objectType:secret, objectName:databasePassword, objectVersion:: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://aromyxkvdev.vault.azure.net/secrets/databasePassword/?api-version=2016-10-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"**Multiple user assigned identities exist, please specify the clientId / resourceId of the identity in the token request"}**
> 

**Which access mode did you use to access the Azure Key Vault instance:**
System Assigned Managed Identity 

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):  k8s.gcr.io/csi-secrets-store/driver:v0.0.23
- Azure Key Vault provider version: (use the image tag):  mcr.microsoft.com/oss/azure/secrets-store/provider-azure:0.0.16
- Kubernetes version: v1.19.7
- Cluster type: AKS

**Comment by caseyzhang123** [comment]
I am having the same issue, where I am using the system assigned identity to retrieve secrets from key vault.  Here is some info from our cluster:

1. I believe we have no user assigned identities on our cluster.
2. We have one system assigned identity on our cluster.

3. Output from az aks show -g <resourceGroupName> -n <aksName> --query "identity":
```
{
  "principalId": "4866b61c-....",
  "tenantId": "72f988bf-86f1-...",
  "type": "SystemAssigned",
  "userAssignedIdentities": null
}
```

4. SecretProviderClass.yaml:
```
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: csi-provider
spec:
  provider: azure
  secretObjects:
    - secretName: ssl-certificate
      type: kubernetes.io/tls
      data:
        - objectName: sslPublicKey
          key: tls.crt
        - objectName: sslPrivateKey
          key: tls.key
  parameters:
    keyvaultName: {{ .Values.keyVault | quote }}       # The name of the Azure Key Vault
    usePodIdentity: "false"
    useVMManagedIdentity: "true"         
    userAssignedIdentityID: "" # When userAssignedIdentityID is not provided, we default to the system assigned identity.
    cloudName: "AzurePublicCloud"                         # [OPTIONAL for Azure] if not provided, Azure environment will default to AzurePublicCloud 
    objects:  |
      array:
        - |
          objectName: ssl      # In this example, 'ExampleSecret' 
          objectAlias: sslPrivateKey     # [OPTIONAL] specify the filename of the object when written to disk - defaults to objectName if not provided
          objectType: secret              # Object types: secret (private key), key (public key) or cert (certificate)
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty 
        - |
          objectName: ssl      # In this example, 'ExampleSecret' 
          objectAlias: sslPublicKey     # [OPTIONAL] specify the filename of the object when written to disk - defaults to objectName if not provided
          objectType: cert              # Object types: secret (private key), key (public key) or cert (certificate)
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
    tenantId: "72f988bf-...."               # the tenant ID containing the Azure Key Vault instance
```

5. I do not believe there was any change in identity assignment on the cluster.
