### ISSUE TITLE
Update documentation and examples for CSI user assigned managed identity

### ISSUE THREAD

**Issue by viktoriiakarpova-TomTom** [Azure/secrets-store-csi-driver-provider-azure#610]
**Have you**

- [x] Read [Troubleshooting Guide](https://azure.github.io/secrets-store-csi-driver-provider-azure/troubleshooting/)
- [x] Searched on [GitHub issues](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues) and [Discussions](https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions)

**What steps did you take and what happened:**
I followed [this](https://azure.github.io/secrets-store-csi-driver-provider-azure/configurations/identity-access-modes/user-assigned-msi-mode/) tutorial and it wasn't working for me until the `useVMManagedIdentity` and `userAssignedIdentityID` were updated directly for deployment. Maybe it's worth to change your example [here](https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/examples/user-assigned-managed-identity/pod-inline-volume-user-assigned-identity.yaml) to something like:

```yaml
  volumes:
    - name: secrets-store01-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "azure-kvname-user-msi"
          useVMManagedIdentity: "true"
          userAssignedIdentityID: "IDENTITY"
```
?

**What did you expect to happen:**
The steps inside tutorial work.

**Anything else you would like to add:**
Example [here](https://azure.github.io/secrets-store-csi-driver-provider-azure/configurations/identity-access-modes/user-assigned-msi-mode/) also could be extended with the deployment yaml example.

**Which access mode did you use to access the Azure Key Vault instance:**
User Assigned Managed Identity, System Assigned Managed Identity

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): mcr.microsoft.com/oss/kubernetes-csi/secrets-store/driver:v0.1.0, mcr.microsoft.com/oss/kubernetes-csi/csi-node-driver-registrar:v2.2.0
- Azure Key Vault provider version: (use the image tag): mcr.microsoft.com/oss/azure/secrets-store/provider-azure@sha256:f7a36ab3b6fc58dfd87438a831908aee77cae3587d98a66e551f25f95992a744
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`): v1.19.11
- Cluster type: (e.g. AKS, aks-engine, etc): AKS
