### ISSUE TITLE
Create secret of type 'azure/blobfuse'

### ISSUE THREAD

**Issue by ddskit** [Azure/secrets-store-csi-driver-provider-azure#611]
**What steps did you take and what happened:**
I am using following azure [blobfuse](https://github.com/Azure/kubernetes-volume-drivers/tree/master/flexvolume/blobfuse) to create the persistent Volume and pvc. This driver needs a secret to be created which has storageaccount access details. This secret is of type 'azure/blodfuse'

I am putting the storageaccount access key in azure key vault and using this csi driver to created the secret via secretproviderclass. 

```
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: wordpress-demo-spc
spec:
  provider: azure
  secretObjects:
  - secretName: wordpress-demo
    data:
    - key: authKey
      objectName: wp-demo-authKey
    type: opaque
  - secretName: wordpress-demo-siteupload-creds
    data:
    - key: accountkey
      objectName: wp-demo-siteupload-storage-accesskey
    - key: accountname
      objectName: wp-demo-siteupload-storage-name
    type: azure/blobfuse
  - secretName: wordpress-demo-initdb-creds
    data:
    - key: accountkey
      objectName: wp-demo-initdb-storage-accesskey
    - key: accountname
      objectName: wp-demo-initdb-storage-name
    type: azure/blobfuse
  parameters:
    usePodIdentity: "true"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    keyvaultName: "aks-key-vault"
    cloudName: ""
    objects:  |
      array:
        - |
          objectName: wp-demo-authKey
          objectType: secret
          objectVersion: ""
        - |
          objectName: wp-demo-siteupload-storage-accesskey
          objectType: secret
          objectVersion: ""
        - |
          objectName: wp-demo-siteupload-storage-name
          objectType: secret
          objectVersion: ""
        - |
          objectName: wp-demo-initdb-storage-accesskey
          objectType: secret
          objectVersion: ""
        - |
          objectName: wp-demo-initdb-storage-name
          objectType: secret
          objectVersion: ""
    resourceGroup: "aks-rg"
    subscriptionId: ""
    tenantId: ""
```
secrets 'wordpress-demo-initdb-creds' and 'wordpress-demo-siteupload-creds' should be created of type azure/blobfuse but created of type 'opaque' . 

**What did you expect to happen:**
I expected that secrets 'wordpress-demo-initdb-creds' and 'wordpress-demo-siteupload-creds' will be created of type azure/blobfuse 

**Anything else you would like to add:**
'azure/blobfuse' secretType is not handled in the code. 

**Which access mode did you use to access the Azure Key Vault instance:**
 Pod Identity

**Environment:**
- Cluster type: AKS
