### ISSUE TITLE
SecretObject not created when using pod identity

### ISSUE THREAD

**Issue by flisak-robert** [Azure/secrets-store-csi-driver-provider-azure#614]
Not sure if this is a bug or if I am doing something incorrectly - I'm trying to inject my keyvault secrets to a pod as environment variables. The pod identity and permissions are working fine - the secrets are correctly mounted as files and I can display them in a pod. The problem occurs when I try to use them as env variables. Here is my `secretprovidersclass.yml`:

```apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvname
spec:
  provider: azure
  secretObjects:
  - secretName: test-secret
    type: Opaque
    data:
    - objectName: test-db-user
      key: dbuser
    - objectName: test-db-pass
      key: dbpassword
  parameters:
    usePodIdentity: "true"
    keyvaultName: "test-keyvault"      
    cloudName: ""               
    objects:  |
      array:
        - |
          objectName: test-db-user
          objectType: secret
          objectVersion: ""
        - |
          objectName: test-db-pass
          objectType: secret
          objectVersion: ""
    tenantId: "<tenantID>"
```
And my `deployment.yml`:

```
apiVersion: v1
kind: Pod
metadata:
  name: nginx-secrets-store-inline
  labels:
    aadpodidbinding: aadpodidbinding
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: test-secret
              key: dbuser
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: test-secret
              key: dbpassword
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: azure-kvname
```
When I run these files, I get the `CreateContainerConfigError`. In the k8s event logs, I can see the following message: `Error: secret "test-secret" not found`. What could be the issue here? Is it a bug?

I've investigated a little bit more and I found this in the secrets-store-csi-driver logs:
`E0820 14:24:02.014875       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.1/tools/cache/reflector.go:167: Failed to watch *v1.Secret: failed to list *v1.Secret: secrets is forbidden: User "system:serviceaccount:kube-system:secrets-store-csi-driver" cannot list resource "secrets" in API group "" at the cluster scope`

What am I missing in my config?
