### ISSUE TITLE
Failed to pull image "mcr.microsoft.com/oss/kubernetes-csi/csi-node-driver-registrar:v2.2.0": rpc error: code = Unknown desc = no matching manifest for linux/arm64/v8 in the manifest list entries

### ISSUE THREAD

**Issue by cheslijones** [Azure/secrets-store-csi-driver-provider-azure#616]
**Have you**

- [x] Read [Troubleshooting Guide](https://azure.github.io/secrets-store-csi-driver-provider-azure/troubleshooting/)
- [x] Searched on [GitHub issues](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues) and [Discussions](https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions)

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I have CSI running fine in production. Thought I'd try to use it in my local dev environment just to cut a few steps out of my setup scripts. I get this error when it comes to deploying the CSI pods:

```
Failed to pull image "mcr.microsoft.com/oss/kubernetes-csi/csi-node-driver-registrar:v2.2.0": rpc error: code = Unknown desc = no matching manifest for linux/arm64/v8 in the manifest list entries
```
This is more than likely related to being on an Apple Silicon M1 Mac.

The Pod statuses:
```
$ kubectl get pods -n dev
NAME                                         READY   STATUS             RESTARTS   AGE
aad-pod-identity-mic-fdc8fdd46-lfg5h         0/1     CrashLoopBackOff   8          19m
aad-pod-identity-mic-fdc8fdd46-n9j76         0/1     CrashLoopBackOff   8          19m
aad-pod-identity-nmi-xjlln                   1/1     Running            0          19m
csi-csi-secrets-store-provider-azure-2w7p2   1/1     Running            0          20m
secrets-store-csi-driver-pm9l6               0/3     ImagePullBackOff   7          20m
```

**What did you expect to happen:**

I thought there would be a 50/50 chance it would deploy seamlessly like it does in my production environment, but it  did not.

Ultimately, I'm pretty sure this is related to `arm64` so I'm curious if that support will be added.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Here is a portion of my setup script:

```
akvIntegration() {
  # # create the necessary namespaces
  kubectl create ns dev

  # assign variables
  subscriptionId=$(az account show --query id -otsv)
  aksClientId=$(az aks show -n ${resourcePrefix}aks -g $resourceGroupName --query identityProfile.kubeletidentity.clientId -otsv)
  aksResourceGroup=$(az aks show -n ${resourcePrefix}aks -g ${resourceGroupName} --query nodeResourceGroup -otsv)
  scope="/subscriptions/${subscriptionId}/resourcegroups/${aksResourceGroup}"
  tenantId=$(az account show --query tenantId -otsv)

  # Add the helm charts for csi
  helm repo add csi-secrets-store-provider-azure https://raw.githubusercontent.com/Azure/secrets-store-csi-driver-provider-azure/master/charts

  # Install the helm charts
  helm install csi csi-secrets-store-provider-azure/csi-secrets-store-provider-azure -n dev

  # Add the helm charts for aad-pod-identity
  helm repo add aad-pod-identity https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts

  # Install the helm charts
  helm install pod-identity aad-pod-identity/aad-pod-identity -n dev

  # pause to give time the identity to be created and query it
  sleep 10

  # Get the clientid for the new identity
  identityClientId=$(az identity show -g $aksResourceGroup -n AksAkvIntegrationIdentity --query clientId -otsv)
  identityResourceId=$(az identity show -g $aksResourceGroup -n AksAkvIntegrationIdentity --query id -otsv)

  echo "${GREEN}Create the link and storage for the keys...${NC}"
cat <<EOF | kubectl apply -n dev -f -
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: aks-akv-identity
  namespace: dev
spec:
  type: 0                                 
  resourceID: $identityResourceId
  clientID: $identityClientId
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: aks-akv-identity-binding
  namespace: dev
spec:
  azureIdentity: aks-akv-identity
  selector: aks-akv-identity-binding-selector
EOF

cat <<EOF | kubectl apply -n dev -f -
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aks-akv-secret-provider
  namespace: dev
spec:
  provider: azure
  secretObjects:
  - secretName: ${resourcePrefix}-dev-secrets
    type: Opaque
    data:
    - objectName: CRMBASE
      key: CRM_BASE
    - objectName: CRMUSERNAME
      key: CRM_USERNAME
    - objectName: CRMPASSWORD
      key: CRM_PASSWORD
    - objectName: TENANTID
      key: CRM_TENANT_ID
    - objectName: DEV-CRMCLIENTID
      key: CRM_CLIENT_ID
    - objectName: DEV-CRMCLIENTSECRET
      key: CRM_CLIENT_SECRET
    - objectName: DEV-DJANGODEBUG
      key: DJANGO_DEBUG
    - objectName: DEV-DJANGOSECRETKEY
      key: DJANGO_SECRET_KEY
    - objectName: DEV-DOMAIN
      key: DOMAIN
    - objectName: DEV-EMAILAPIKEY
      key: EMAIL_API_KEY
    - objectName: DEV-PGDATABASE
      key: PGDATABASE
    - objectName: DEV-PGDATABASEV2
      key: PGDATABASEV2
    - objectName: DEV-PGHOST
      key: PGHOST
    - objectName: DEV-PGPORT
      key: PGPORT
    - objectName: DEV-PGUSER
      key: PGUSER
    - objectName: DEV-PGPASSWORD
      key: PGPASSWORD
  parameters:
    usePodIdentity: "true"                                        
    keyvaultName: ${resourceGroupName}akv
    cloudName: ""                               
    objects: |
      array:
        - |
            objectName: CRMBASE             
            objectType: secret                 
            objectVersion: ""
        - |
            objectName: CRMUSERNAME             
            objectType: secret                 
            objectVersion: "" 
        - |
            objectName: CRMPASSWORD             
            objectType: secret                 
            objectVersion: ""
        - |
            objectName: TENANTID             
            objectType: secret                 
            objectVersion: ""
        - |
            objectName: DEV-CRMCLIENTID             
            objectType: secret                 
            objectVersion: "" 
        - |
            objectName: DEV-CRMCLIENTSECRET             
            objectType: secret                 
            objectVersion: ""   
        - |
            objectName: DEV-DJANGODEBUG             
            objectType: secret                 
            objectVersion: ""  
        - |
            objectName: DEV-DJANGOSECRETKEY             
            objectType: secret                 
            objectVersion: ""
        - |
            objectName: DEV-DOMAIN             
            objectType: secret                 
            objectVersion: ""
        - |
            objectName: DEV-EMAILAPIKEY             
            objectType: secret                 
            objectVersion: ""  
        - |
            objectName: DEV-PGDATABASE             
            objectType: secret                 
            objectVersion: ""
        - |
            objectName: DEV-PGDATABASEV2     
            objectType: secret                 
            objectVersion: ""
        - |
            objectName: DEV-PGHOST             
            objectType: secret                 
            objectVersion: ""
        - |
            objectName: DEV-PGPORT             
            objectType: secret                 
            objectVersion: ""
        - |
            objectName: DEV-PGUSER             
            objectType: secret                 
            objectVersion: ""
        - |
            objectName: DEV-PGPASSWORD             
            objectType: secret                 
            objectVersion: ""
    tenantId: $tenantId
EOF
```

**Which access mode did you use to access the Azure Key Vault instance:**
[e.g. Service Principal, Pod Identity, User Assigned Managed Identity, System Assigned Managed Identity]

AAD Pod Identity

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): `v0.2.0`
- Azure Key Vault provider version: (use the image tag): `not sure`
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`): `v1.21.2`
- Cluster type: (e.g. AKS, aks-engine, etc): `minikube`
