### ISSUE TITLE
azure-keyvault-secrets-provider (preview) fails on windows nodes

### ISSUE THREAD

**Issue by johannordincab** [Azure/secrets-store-csi-driver-provider-azure#619]
**Have you**

- [ x ] Read [Troubleshooting Guide](https://azure.github.io/secrets-store-csi-driver-provider-azure/troubleshooting/)
- [ x ] Searched on [GitHub issues](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues) and [Discussions](https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions)

**What steps did you take and what happened:**
* created a cluster with 
```
az aks create -rg mycluster -n mycluster --node-count 2 --enable-managed-identity --generate-ssh-keys --windows-admin-username [...] --vm-set-type VirtualMachineScaleSets --kubernetes-version 1.21.2 --network-plugin azure
az aks nodepool add -g mycluster --cluster-name mycluster --os-type Windows --name npwin --node-count 1
az aks enable-addons --addons azure-keyvault-secrets-provider --name mycluster --resource-group mycluster
az keyvault create -n mycluster-kv -g mycluster -l westeurope
az keyvault secret set --vault-name mycluster-kv -n ExampleSecret --value MyAksExampleSecret
az keyvault set-policy -n mycluster-kv --secret-permissions get --spn [...]
```
* applied yaml:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample
  labels:
    app: sample
spec:
  replicas: 1
  template:
    metadata:
      name: sample
      labels:
        app: sample
    spec:
      nodeSelector:
        "kubernetes.io/os": windows
      containers:
      - name: sample
        image: mcr.microsoft.com/dotnet/framework/samples:aspnetapp
        ports:
          - containerPort: 80
        volumeMounts:
          - name: mycluster-kv
            mountPath: 'C:\test'
            readOnly: true
      volumes:
        - name: mycluster-kv
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: mycluster-kv
            nodePublishSecretRef:
              name: secrets-store-creds
  selector:
    matchLabels:
      app: sample
---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: mycluster-kv
spec:
  provider: azure
  parameters:
    keyvaultName: "mycluster-kv"       # The name of the Azure Key Vault
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "..." # The clientId of the addon-created managed identity
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, Azure environment will default to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: ExampleSecret       # In this example, 'ExampleSecret'
          objectType: secret              # Object types: secret, key or cert
    tenantId: "..."               # the tenant ID containing the Azure Key Vault instance
```
* windows fails with message 
```
MountVolume.SetUp failed for volume "aks-issue-repro-kv" : kubernetes.io/csi: mounter.SetUpAt failed to get CSI client: driver name secrets-store.csi.k8s.io not found in the list of registered CSI drivers
```
compared to our previous cluster when we installed the csi-driver using helm we are also missing the "csi-driver"-pod on the windows node:
```
NAME                                             READY   STATUS    RESTARTS   AGE    IP            NODE                                NOMINATED NODE   READINESS GATES
aks-secrets-store-csi-driver-qstkz               3/3     Running   0          11m    10.240.0.4    aks-nodepool1-31868097-vmss000000   <none>           <none>
aks-secrets-store-csi-driver-xqtnd               3/3     Running   0          11m    10.240.0.35   aks-nodepool1-31868097-vmss000001   <none>           <none>
aks-secrets-store-provider-azure-4rs5l           1/1     Running   0          11m    10.240.0.4    aks-nodepool1-31868097-vmss000000   <none>           <none>
aks-secrets-store-provider-azure-qqpkv           1/1     Running   0          11m    10.240.0.35   aks-nodepool1-31868097-vmss000001   <none>           <none>
aks-secrets-store-provider-azure-windows-v249n   1/1     Running   0          11m    10.240.0.93   aksnpwin000000                      <none>           <none>
```

steps used are from here:
https://docs.microsoft.com/en-us/azure/aks/windows-container-cli
https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver

**What did you expect to happen:**
secrets to be mounted.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
when installing using helm we specified some options to get windows to work , perhaps that is what is missing? i tried a linux pod which worked as it should.

**Which access mode did you use to access the Azure Key Vault instance:**
uami, as stated in the link

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):v2.1.0
- Azure Key Vault provider version: (use the image tag): - dont know, where do i find it?
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`):1.21.2
- Cluster type: (e.g. AKS, aks-engine, etc):AKS
