### ISSUE TITLE
FailedToCreateSecret: file matching objectName ... not found in the pod

### ISSUE THREAD

**Issue by Xitric** [Azure/secrets-store-csi-driver-provider-azure#673]
**Have you**
- [x] Read [Troubleshooting Guide](https://azure.github.io/secrets-store-csi-driver-provider-azure/troubleshooting/)
- [x] Searched on [GitHub issues](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues) and [Discussions](https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions)

I am aware of the existence of similar issues, however I have been unable to solve my problem by investigating the resolutions to those.

**What steps did you take and what happened:**
First I installed the secrets store CSI driver provider for Azure via your Helm chart with:

```
helm repo add csi-secrets-store-provider-azure https://raw.githubusercontent.com/Azure/secrets-store-csi-driver-provider-azure/master/charts
helm install csi-secrets-store-provider-azure/csi-secrets-store-provider-azure --generate-name --set secrets-store-csi-driver.syncSecret.enabled=true --namespace kube-system
```

I have verified that `syncSecret` is enabled:

```
> helm get values csi-secrets-store-provider-azure-1634031378 -n kube-system
USER-SUPPLIED VALUES:
secrets-store-csi-driver:
  syncSecret:
    enabled: true
```

And that the clusterrole and its binding are running:

```
> kubectl get clusterrole -n kube-system
NAME                                                                   CREATED AT
secretproviderclasses-role                                             2021-10-12T09:36:26Z
secretprovidersyncing-role                                             2021-10-12T09:36:26Z

> kubectl get clusterrolebinding -n kube-system
NAME                                                   ROLE                                                               AGE
secretproviderclasses-rolebinding                      ClusterRole/secretproviderclasses-role                             4h13m
secretprovidersyncing-rolebinding                      ClusterRole/secretprovidersyncing-role                             4h13m
```

I have then created a `SecretProviderClass` with the following definition:

```
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: auth-secret-provider
  namespace: mynamespace
spec:
  provider: azure
  secretObjects:
    - secretName: csi-secret
      type: Opaque
      data:
        - objectName: upmscid
          key: upstreammsclientid
        - objectName: umscs
          key: upstreammsclientsecret
        - objectName: uacid
          key: upstreamauthclientid
        - objectName: uacs
          key: upstreamauthclientsecret
  parameters:
    usePodIdentity: "true"
    keyvaultName: kv-[REDACTED]
    objects: |
      array:
        - |
          objectName: upstream-microsoftAccounts-clientId
          objectAlias: upmscid
          objectType: secret
      array:
        - |
          objectName: upstream-microsoftAccounts-clientSecret
          objectAlias: umscs
          objectType: secret
      array:
        - |
          objectName: upstream-auth0Accounts-clientId
          objectAlias: uacid
          objectType: secret
      array:
        - |
          objectName: upstream-auth0Accounts-clientSecret
          objectAlias: uacs
          objectType: secret
    resourceGroup: rg-[REDACTED]
    subscriptionId: [REDACTED]
    tenantId: [REDACTED]
```

As well as assigned a managed identity that enables access to the key vault:

```
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: podmi-bum-auth-identity
  namespace: mynamespace
spec:
  type: 0
  resourceID: [REDACTED]
  clientID: [REDACTED]
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: podmi-bum-auth-binding
  namespace: mynamespace
spec:
  azureIdentity: podmi-bum-auth-identity
  selector: podmi-bum-auth
```

My deployment looks like this:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bum-auth
  namespace: mynamespace
  labels:
    aadpodidbinding: podmi-bum-auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bum-auth
  template:
    metadata:
      labels:
        app: bum-auth
        aadpodidbinding: podmi-bum-auth
    spec:
      containers:
      - name: bum-auth
        image: [REDACTED]/bum_auth:21.9
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
          - name: Upstream__MicrosoftAccounts__0__ClientId
            valueFrom:
              secretKeyRef:
                name: csi-secret
                key: upstreammsclientid
          - name: Upstream__MicrosoftAccounts__0__ClientSecret
            valueFrom:
              secretKeyRef:
                name: csi-secret
                key: upstreammsclientsecret
          - name: Upstream__Auth0Accounts__0__ClientId
            valueFrom:
              secretKeyRef:
                name: csi-secret
                key: upstreamauthclientid
          - name: Upstream__Auth0Accounts__0__ClientSecret
            valueFrom:
              secretKeyRef:
                name: csi-secret
                key: upstreamauthclientsecret
        volumeMounts:
          - name: csi-mount
            mountPath: "/mnt/secrets-store"
            readOnly: true
      volumes:
        - name: csi-mount
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "auth-secret-provider"
      nodeSelector:
       agentpool: npuser01
```

We have used odd names for our keys and object names for traceability of issues, but in the end we would like to just use a common name throughout since all the aliasing/renaming does not make sense for our use case. Regardless, the issue below persists:

```
Name:         bum-auth-784fd8bd69-qtm8j
Namespace:    mynamespace
Priority:     0
Node:         aks-npuser01-23849687-vmss000001/10.240.0.38
Start Time:   Tue, 12 Oct 2021 15:47:31 +0200
Labels:       aadpodidbinding=podmi-bum-auth
              app=bum-auth
              pod-template-hash=784fd8bd69
Annotations:  <none>
Status:       Pending
IP:           10.240.0.67
IPs:
  IP:           10.240.0.67
Controlled By:  ReplicaSet/bum-auth-784fd8bd69
Containers:
  bum-auth:
    Container ID:   
    Image:          [REDACTED]/bum_auth:21.9
    Image ID:       
    Port:           80/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       CreateContainerConfigError
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     500m
      memory:  128Mi
    Requests:
      cpu:     500m
      memory:  128Mi
    Environment Variables from:
      auth-config  ConfigMap  Optional: false
    Environment:
      Upstream__MicrosoftAccounts__0__ClientId:      <set to the key 'upstreammsclientid' in secret 'csi-secret'>        Optional: false
      Upstream__MicrosoftAccounts__0__ClientSecret:  <set to the key 'upstreammsclientsecret' in secret 'csi-secret'>    Optional: false
      Upstream__Auth0Accounts__0__ClientId:          <set to the key 'upstreamauthclientid' in secret 'csi-secret'>      Optional: false
      Upstream__Auth0Accounts__0__ClientSecret:      <set to the key 'upstreamauthclientsecret' in secret 'csi-secret'>  Optional: false
    Mounts:
      /mnt/secrets-store from csi-mount (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-58b6z (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  csi-mount:
    Type:              CSI (a Container Storage Interface (CSI) volume source)
    Driver:            secrets-store.csi.k8s.io
    FSType:            
    ReadOnly:          true
    VolumeAttributes:      secretProviderClass=auth-secret-provider
  kube-api-access-58b6z:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Guaranteed
Node-Selectors:              agentpool=npuser01
Tolerations:                 node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason                Age                    From                          Message
  ----     ------                ----                   ----                          -------
  Normal   Scheduled             6m57s                  default-scheduler             Successfully assigned mynamespace/bum-auth-784fd8bd69-qtm8j to aks-npuser01-23849687-vmss000001
  Normal   Pulled                5m41s                  kubelet                       Successfully pulled image "[REDACTED]/bum_auth:21.9" in 72.019814ms
  Normal   Pulled                5m41s                  kubelet                       Successfully pulled image "[REDACTED]/bum_auth:21.9" in 86.233338ms
  Normal   Pulled                5m25s                  kubelet                       Successfully pulled image "[REDACTED]/bum_auth:21.9" in 109.464791ms
  Normal   Pulled                5m11s                  kubelet                       Successfully pulled image "[REDACTED]/bum_auth:21.9" in 69.292058ms
  Normal   Pulled                4m59s                  kubelet                       Successfully pulled image "[REDACTED]/bum_auth:21.9" in 172.237632ms
  Normal   Pulled                4m47s                  kubelet                       Successfully pulled image "[REDACTED]/bum_auth:21.9" in 63.800747ms
  Normal   Pulled                4m33s                  kubelet                       Successfully pulled image "[REDACTED]/bum_auth:21.9" in 144.588977ms
  Warning  Failed                4m21s (x8 over 5m41s)  kubelet                       Error: secret "csi-secret" not found
  Normal   Pulled                4m21s                  kubelet                       Successfully pulled image "[REDACTED]/bum_auth:21.9" in 64.097275ms
  Normal   Pulling               37s (x25 over 5m41s)   kubelet                       Pulling image "[REDACTED]/bum_auth:21.9"
  Warning  FailedToCreateSecret  14s (x17 over 5m42s)   csi-secrets-store-controller  failed to get data in spc mynamespace/auth-secret-provider for secret csi-secret, err: file matching objectName upmscid not found in the pod
```

**What did you expect to happen:**
I expected the secret to be created, allowing us to use place secrets from key vault into our environment variables.

I fear that this is simply a misconfiguration from my side - but I have spent too many hours for this now, and would really appreciate some guidance. In any event, I see a lot of similar issues, so perhaps this type of issue is something that should be added to the troubleshooting page as well.

**Anything else you would like to add:**
None beyond what I have already provided. If you wish to see specific logs, please let me know.

**Which access mode did you use to access the Azure Key Vault instance:**
User Assigned Managed Identity

**Environment:**
- Secrets Store CSI Driver version: 0.3.0
- Azure Key Vault provider version: 0.2.0
- Kubernetes version: 1.21.2
- Cluster type: AKS

**Comment by Xitric** [comment]
Luckily this turned out to be just a misconfiguration from my side. I had repeated the `array` keyword in my `SecretsProviderClass`. The correct definition should look like this:

```yaml
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: auth-secret-provider
  namespace: mynamespace
spec:
  provider: azure
  secretObjects:
    - secretName: csi-secret
      type: Opaque
      data:
        - objectName: upmscid
          key: upstreammsclientid
        - objectName: umscs
          key: upstreammsclientsecret
        - objectName: uacid
          key: upstreamauthclientid
        - objectName: uacs
          key: upstreamauthclientsecret
  parameters:
    usePodIdentity: "true"
    keyvaultName: kv-[REDACTED]
    objects: |
      array:
        - |
          objectName: upstream-microsoftAccounts-clientId
          objectAlias: upmscid
          objectType: secret
        - |
          objectName: upstream-microsoftAccounts-clientSecret
          objectAlias: umscs
          objectType: secret
        - |
          objectName: upstream-auth0Accounts-clientId
          objectAlias: uacid
          objectType: secret
        - |
          objectName: upstream-auth0Accounts-clientSecret
          objectAlias: uacs
          objectType: secret
    resourceGroup: rg-[REDACTED]
    subscriptionId: [REDACTED]
    tenantId: [REDACTED]
```
