### ISSUE TITLE
Not able to mount EC Key in application pod

### ISSUE THREAD

**Issue by chintanr97** [Azure/secrets-store-csi-driver-provider-azure#71]
Hi, when I am trying to deploy my app, I wish to mount an "Elliptic Curve" Key in the application pod. But I am getting this error for that:

```
Events:
  Type     Reason       Age   From                                        Message
  ----     ------       ----  ----                                        -------
  Normal   Scheduled    40s   default-scheduler                           Successfully assigned default/certs-store to aks-agentpool-19909641-vmss000001
  Warning  FailedMount  38s   kubelet, aks-agentpool-19909641-vmss000001  MountVolume.SetUp failed for volume "secrets-store-inline" : kubernetes.io/csi: mounter.SetupAt failed: rpc error: code = Unknown desc = error mounting secret panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x6e4b08]

goroutine 1 [running]:
github.com/Azure/secrets-store-csi-driver-provider-azure/pkg/azure.(*Provider).GetKeyVaultObjectContent(0xc0003b7eb8, 0x831620, 0xc00001a018, 0xc00001ab88, 0x3, 0xc00001ab50, 0xc, 0x0, 0x0, 0xc0003eec00, ...)
  /go/src/github.com/Azure/secrets-store-csi-driver-provider-azure/pkg/azure/provider.go:431 +0x13f8
github.com/Azure/secrets-store-csi-driver-provider-azure/pkg/azure.(*Provider).MountSecretsStoreObjectContent(0xc0003b7eb8, 0x831620, 0xc00001a018, 0xc00005f260, 0xc00005f290, 0x7ffc950fdd55, 0x6f, 0xc0000001a4, 0x7b21b9, 0x7)
  /go/src/github.com/Azure/secrets-store-csi-driver-provider-azure/pkg/azure/provider.go:387 +0xa6d
main.main()
           /go/src/github.com/Azure/secrets-store-csi-driver-provider-azure/cmd/main.go:67 +0x42b
  Warning  FailedMount  36s  kubelet, aks-agentpool-19909641-vmss000001  MountVolume.SetUp failed for volume "secrets-store-inline" : kubernetes.io/csi: mounter.SetupAt failed: rpc error: code = Unknown desc = error mounting secret panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x6e4b08]
```

I was getting some error with the Flex Volume too. I switched my testing to "secrets-store-csi-driver" for that. But again facing a similar issue.

**Comment by aramase** [comment]
We're currently only returning RSA Modulus content of key - https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/pkg/azure/provider.go#L430-L431

I think we need to check the key type and return the appropriate key.

**Comment by aramase** [comment]
@chintanr97 Currently, the azure keyvault provider only supports RSA keys.  It writes the RSA modulus to the file. Can you provide more info on what format you expect the EC key to be written in?

I've added a fix - https://github.com/Azure/secrets-store-csi-driver-provider-azure/pull/74 to ensure there there are panics for currently non-supported key types.

**Comment by chintanr97** [comment]
Currently, I am doing the following from Azure Portal UX:

1. Creating an EC key of P-256 curve type.
2. Creating a secret provider class as follows:

```
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvname
spec:
  provider: azure                   # accepted provider options: azure or vault
  parameters:
    usePodIdentity: "false"         # [OPTIONAL for Azure] if not provided, will default to "false"
    keyvaultName: "<keyvaultname>"          # the name of the KeyVault
    objects:  |
      array:
        - |
          objectName: external1
          objectAlias: e1     # [OPTIONAL available for version > 0.0.4] object alias
          objectType: cert        # object types: secret, key or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: selfsigned1
          objectAlias: "ss1"
          objectType: cert
          objectVersion: ""
        - |
          objectName: internalkey1
          objectAlias: "ik1"
          objectType: key
          objectVersion: ""
    resourceGroup: "<rGName>"            # [REQUIRED for version < 0.0.4] the resource group of the KeyVault
    subscriptionId: "<subsId>"         # [REQUIRED for version < 0.0.4] the subscription ID of the KeyVault
    tenantId: "<tId>"                 # the tenant ID of the KeyVault
```
The `internalkey1` object is that key. I tried this today again with a completely new AKS cluster (v 1.16.7). What I expect is, if I am creating an exportable EC key, I would like to mount it in the pod, preferably in PEM format.
