### ISSUE TITLE
secrets-store secret not found when pod tries to start

### ISSUE THREAD

**Issue by Gmanweb** [Azure/secrets-store-csi-driver-provider-azure#714]
**Have you**

- [yes] Read [Troubleshooting Guide](https://azure.github.io/secrets-store-csi-driver-provider-azure/troubleshooting/)
- [ yes] Searched on [GitHub issues](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues) and [Discussions](https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions)

**What steps did you take and what happened:**
I have an Nginx deployment in a test namespace called `csi-driver` where I have deployed everything to do with SCI
My secret provider calss

```
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kv-provider
  namespace: csi-driver
spec:
  provider: azure
  secretObjects: # [OPTIONAL] SecretObject defines the desired state of synced K8s secret objects
    - secretName: sqlserver
      type: Opaque
      data:
        - objectName: secret-1 # name of the mounted content to sync. this could be the object name or object alias
          key: dbpassword
  parameters:
    usePodIdentity: "false" # We will not use pod identity for this example. We will use SP
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "XYXYXU99-833FGSREAD-520sgrea"
    keyvaultName: "My-Test-Dev-KV" # This is the name of KeyVault resource that we created in previous step
    cloudName: "AzurePublicCloud"
    objects: |
      array:
        - |
          objectName: foosecret
          objectType: secret      # object types: secret, key or cert
          objectAlias: secret-1
          objectVersion: ""
    resourceGroup: "My-Test-Dev-Workload-rg" # Resource goup that you have used to create KeyVault
    subscriptionId: "XXXXXX_XXX_XXX_XXXXXX___XXXX"
    tenantId: "XXXXXX_XXX_XXX_XXXXXX___XXXX"
```

My Deployment that works

```
kind: Pod
apiVersion: v1
metadata:
  name: nginx-secrets-store
  namespace: csi-driver
spec:
  containers:
    - name: nginx
      image: nginx:latest
      volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: azure-kv-provider
```

when I exec into pod I can see the secret

```
root@nginx-secrets-store:/# ls /mnt/secrets-store/secret-1 
/mnt/secrets-store/secret-1
root@nginx-secrets-store:/# 
```
but not secret was created from the mount.

Even when I add the env to the deployment like so.

```
......
      volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      env:
        - name: dbpassword
          valueFrom:
            secretKeyRef:
              name: secret-1
              key: dbpassword
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
......
```

**What did you expect to happen:**
I expected a secret to be created from mount secret store

Instead, I get secret not found
**Error: secret "secret-1" not found**

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
- Azure Key Vault provider version: (use the image tag):

**Comment by aramase** [comment]
@Gmanweb To sync the mounted content as Kubernetes secret, you need to additionally define the `secretObjects` field in the `SecretProviderClass`. Please refer to https://azure.github.io/secrets-store-csi-driver-provider-azure/configurations/sync-with-k8s-secrets/ for more details.

Here are some examples: https://github.com/Azure/secrets-store-csi-driver-provider-azure/tree/master/examples/sync-as-kubernetes-secret

**Comment by Gmanweb** [comment]
Hi @aramase 

I do have it or I thought I did, see code block above and snip below. Am I missing something else?


```
...
secretObjects: # [OPTIONAL] SecretObject defines the desired state of synced K8s secret objects
    - secretName: sqlserver
      type: Opaque
      data:
        - objectName: secret-1 # name of the mounted content to sync. this could be the object name or object alias
          key: dbpassword
....

```
