### ISSUE TITLE
Multiple user assigned identities exist, please specify the clientId / resourceId of the identity in the token request

### ISSUE THREAD

**Issue by caseyzhang123** [Azure/secrets-store-csi-driver-provider-azure#725]
Same issue as #598, but I can't reopen it so here's a new one.

**Have you**

- [x] Read [Troubleshooting Guide](https://azure.github.io/secrets-store-csi-driver-provider-azure/troubleshooting/)
- [x] Searched on [GitHub issues](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues) and [Discussions](https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions)

**What steps did you take and what happened:**
We are trying to set up the azure provider to retrieve a cert from KeyVault via system assigned managed identity.  When the pods attempt to retrieve the cert, we see these errors:
```
I1125 00:58:29.146162   18304 provider.go:257] "unmarshaled key vault objects" keyVaultObjects=[{ObjectName:ssl ObjectAlias:sslPrivateKey ObjectVersion: ObjectType:secret ObjectFormat: ObjectEncoding:} {ObjectName:ssl ObjectAlias:sslPublicKey ObjectVersion: ObjectType:cert ObjectFormat: ObjectEncoding:}] count=2 pod="default/sync-service-75b78fc48b-ds98n"
I1125 00:58:29.146244   18304 auth.go:138] "using system-assigned managed identity to retrieve access token" pod="default/sync-service-75b78fc48b-ds98n"
I1125 00:58:29.151857   18304 provider.go:278] "fetching object from key vault" objectName="ssl" objectType="secret" keyvault=<keyVaultName> pod="default/sync-service-75b78fc48b-ds98n"
E1125 00:58:29.217143   18304 server.go:58] "failed to process mount request" err="failed to get objectType:secret, objectName:ssl, objectVersion:: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://<keyVaultName>.vault.azure.net/secrets/ssl/?api-version=2016-10-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {\"error\":\"invalid_request\",\"error_description\":\"Multiple user assigned identities exist, please specify the clientId / resourceId of the identity in the token request\"} Endpoint http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fvault.azure.net"
```

**What did you expect to happen:**
We expected the authentication to succeed and to get the secret successfully.

**Anything else you would like to add:**
I am having the same issue, where I am using the system assigned identity to retrieve secrets from key vault. Here is some info from our cluster:

1. I believe we have no user assigned identities on our cluster.

2. We have one system assigned identity on our cluster.

3. Output from az aks show -g -n --query "identity":
```
{
  "principalId": "4866b61c-....",
  "tenantId": "72f988bf-86f1-...",
  "type": "SystemAssigned",
  "userAssignedIdentities": null
}
```
4. SecretProviderClass.yaml:
```
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: csi-provider
spec:
  provider: azure
  secretObjects:
    - secretName: ssl-certificate
      type: kubernetes.io/tls
      data:
        - objectName: sslPublicKey
          key: tls.crt
        - objectName: sslPrivateKey
          key: tls.key
  parameters:
    keyvaultName: {{ .Values.keyVault | quote }}       # The name of the Azure Key Vault
    usePodIdentity: "false"
    useVMManagedIdentity: "true"         
    userAssignedIdentityID: "" # When userAssignedIdentityID is not provided, we default to the system assigned identity.
    cloudName: "AzurePublicCloud"                         # [OPTIONAL for Azure] if not provided, Azure environment will default to AzurePublicCloud 
    objects:  |
      array:
        - |
          objectName: ssl      # In this example, 'ExampleSecret' 
          objectAlias: sslPrivateKey     # [OPTIONAL] specify the filename of the object when written to disk - defaults to objectName if not provided
          objectType: secret              # Object types: secret (private key), key (public key) or cert (certificate)
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty 
        - |
          objectName: ssl      # In this example, 'ExampleSecret' 
          objectAlias: sslPublicKey     # [OPTIONAL] specify the filename of the object when written to disk - defaults to objectName if not provided
          objectType: cert              # Object types: secret (private key), key (public key) or cert (certificate)
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
    tenantId: "72f988bf-...."               # the tenant ID containing the Azure Key Vault instance
```
5. I do not believe there was any change in identity assignment on the cluster.

**Which access mode did you use to access the Azure Key Vault instance:**
System Assigned Managed Identity

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): 1.0.0
- Azure Key Vault provider version: (use the image tag): 1.0.0
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`):
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"c612f9dcf9cf5f6fda3ba3cd1c53b118c897f6c7", GitTreeState:"clean", BuildDate:"2021-10-21T03:30:46Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
```
- Cluster type: (e.g. AKS, aks-engine, etc): AKS

**Comment by aramase** [comment]
Hello 👋🏻 

Could you share the output for `az vmss identity show -g <rg> -n <vmss name>`?

**Comment by caseyzhang123** [comment]
We have two scale sets, each with the following output showing 2 user assigned identities:
```
{
  "principalId": null,
  "tenantId": null,
  "type": "UserAssigned",
  "userAssignedIdentities": {
    "/subscriptions/70b6.../resourceGroups/MC_w4-casey-..._aks-casey-.../providers/Microsoft.ManagedIdentity/userAssignedIdentities/aks-casey-...-agentpool": {
      "clientId": "b2f78597-...",
      "principalId": "fce8b491-"
    },
    "/subscriptions/70b6f77d-6421-474b-8be8-45376b6d6d67/resourcegroups/MC_w4-casey-..._aks-casey-.../providers/Microsoft.ManagedIdentity/userAssignedIdentities/omsagent-aks-casey-...": {
      "clientId": "4c10305d-...",
      "principalId": "8a7c9958-..."
    }
  }
}
```

**Comment by aramase** [comment]
There is no `SystemAssiged` identity in the output. The error message is valid. To use system-assigned managed identity, please refer to https://azure.github.io/secrets-store-csi-driver-provider-azure/configurations/identity-access-modes/system-assigned-msi-mode/

**Comment by miwithro** [comment]
Adding in @zeromagic to comment.

**Comment by caseyzhang123** [comment]
Commenting to keep thread alive.  The core issue is that the system assigned identity I'm trying to use is the AKS system assigned identity, which is distinct from vmss system-assigned identities.  This seems poorly documented to me, but at least I can find a workaround now - likely I will switch to user-assigned identities.

**Comment by miwithro** [comment]
@caseyzhang123 I updated the AKS documentation to walk you through the use cases.

**Comment by joseph-flinn** [comment]
I'm having the same (or similar) issue. When creating an AKS cluster, we select the `System Assigned` managed identity which is assigned to the AKS cluster and not the VMSS. AKS instead automatically creates a `User Assigned` managed identity on the VMSS. We can use this managed identity to connect to the needed KV via this manifest:

```yaml
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
spec:
  provider: azure
  parameters:
    useVMManagedIdentity: "true"
    keyvaultName: keyvault-name
    cloudName: "AzurePublicCloud"
    ...
```

This works just great if there is only that one user assigned managed identity (which was assigned by AKS and not a custom one). However, it breaks as soon we turn on any feature in AKS that requires another user assigned managed identity (AKS creates one on the VMSS for the OMS agent). This is a concern moving to a production environment if we decide to turn on a feature in the future. I would be somewhat ok accepting this risk if it was reversible. However, for some reason, if we add a second user assigned managed identity and then remove it, the secrets-store-csi-driver still sees multiple and error out preventing pods from starting up. If this happens, the cluster is unusable for any pods that need access to Key Vault and a new one has be built and everything has to be migrated over to that one.

Any advice on how to mitigate this and not have to `userAssignedIdentityID` on the `SecretProviderClass` (this isn't flexible enough for quick disaster recovery exercises where we need to stand up a brand new cluster with a new user assigned managed identity)?
