### ISSUE TITLE
Using ServicePrincipal 

### ISSUE THREAD

**Issue by deepakpachauri** [Azure/secrets-store-csi-driver-provider-azure#813]
Hello,

I'm trying to get a secret into an AKS cluster using ServicePrincipal but the pod isn't able to pull the secret, i'm receiving the below error;
MountVolume.SetUp failed for volume "keyvault-secrets-mount" : rpc error: code = DeadlineExceeded desc = context deadline exceeded

Below is what I did;
I created an AKS cluster

Created ServicePrincipal in AD assigned Contributor role to it.

assigned the idntity permissions on my keyvault using portal

created  secrets-store-creds
kubectl create secret generic secrets-store-creds --from-literal clientid=$client-id --from-literal clientsecret=$client-secret

created the SecretProviderClass
```
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: my-keyvault-secret
spec:
  provider: azure
  secretObjects:
  - data:
    - objectName: secret-1
      key: secret.1
    secretName: my-keyvault-secret
    type: Opaque
  parameters:
    usePodIdentity: "false"
    keyvaultName: "my-keyvault-1"
    cloudName: ""
    objects: |
      array:
        - |
          objectName: secret-1
          objectType: secret
          objectVersion: ""
    tenantId: "tenant_id"
```
Created Deployment
```
deployment:
  extraVolumeMounts:
    - name: keyvault-secrets-mount
      mountPath: "/mnt/secrets-store"
      readOnly: true
  extraVolumes:
    - name: keyvault-secrets-mount
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "my-keyvault-secret"
        nodePublishSecretRef:
          name: secrets-store-creds
```
