### ISSUE TITLE
Environment Variable and Volume Mount

### ISSUE THREAD

**Issue by ai038911** [Azure/secrets-store-csi-driver-provider-azure#850]
What I am trying to achieve: read a value from the KV, present it as an environment variable for the deployment, via a Kubernetes secret. The two secrets are a username & password

Exactly Similar to : https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/133

Where In  I am using 
1. A cluster with Managed Identity & enabled with Pod Identity
2. Azure AD pod identity - Managed Mode

What works:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "2048-deployment"
  namespace: my-app
  labels:
    aadpodidbinding: my-pod-identity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "2048"
  template:
    metadata:
      labels:
        app: "2048"
        aadpodidbinding: my-pod-identity
        version: v1
    spec:
      containers:
      - image: *****
        imagePullPolicy: Always
        name: "2048"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
        - name: config-volume
          mountPath: /app/appsettings.json
          subPath: appsettings.json
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-csi-sample"
        - name: config-volume
          configMap:
            name: azkv-csi-int-test-configmap
      imagePullSecrets:
      - name: acrsecret
```

With this i can see the secrets Mounted on Pod
**********************************************************************

What does not work :
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx0
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        aadpodidbinding: my-pod-identity
    spec:
      containers:
      - name: nginx
        image: *****
        env:
         - name: SQL_USER
           valueFrom:
             secretKeyRef:
               name: loginsecret1
               key: sql-user-id
        volumeMounts:
          - name: secrets-store-inline
            mountPath: "/mnt/secrets-store"
            readOnly: true        
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-csi-sample"                        
      imagePullSecrets:
      - name: acrsecret
```
SecretproviderClass
```
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-csi-sample
spec:
  provider: azure
  secretObjects:                                 # [OPTIONAL] SecretObject defines the desired state of synced K8s secret objects
  - secretName: loginsecret1
    type: Opaque
    data: 
    - objectName: sql-user-id                     # name of the mounted content to sync. this could be the object name or object alias 
      key: sql-user-id
  parameters:
    usePodIdentity: "true"
    keyvaultName: "aks-csi-azkv"
    objects: |
      array:
        - |
          objectName: sql-user-id
          objectType: secret
          objectVersion: ""       
    tenantId: ""

```
I deploy my application pods don't start as they don't find the secret. The deployment yaml should mount the volume and create the secret as per the deployment.yaml

```
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  35m                  default-scheduler  Successfully assigned my-app/nginx0-6f6b59dcff-b4fdf to aks-nodepool1-28764885-vmss000000
  Warning  Failed     33m (x12 over 35m)   kubelet            Error: secret "loginsecret1" not found
```
