### ISSUE TITLE
Problem with generating TLS certeficate on NGINX Ingress Controller with TLS   secrets-store-csi-driver-provider-azure  

### ISSUE THREAD

**Issue by silandrew** [Azure/secrets-store-csi-driver-provider-azure#852]
**Have you**
Problem with generating TLS certeficate on NGINX Ingress Controller with TLS  new secrets-store-csi-driver-provider-azure  charl version 

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
when Ive download  the  latest

Problem with generating TLS certeficate on NGINX Ingress Controller with TLS  when Ive  used  lattest helm 3, **only  working with 
	- helm install csi-secrets-store-provider-azure/csi-secrets-store-provider-azure --version 0.0.16--generate-name
		

with following YAML config
```yaml
  namespace:xxx
spec:
  provider: azure
  secretObjects:                                
  - secretName: ingress-tls-csi    #name of the secret that gets created - this is the value we provide to nginx
    type: kubernetes.io/tls
    data: 
    - objectName: xxxx
      key: tls.key
    - objectName: xxxx
      key: tls.crt
  parameters:
    usePodIdentity: "true"   #since we are using aad pod identity we set this to true
    keyvaultName: "kv-mngt-dev"                        
    objects: |
      array:
        - |
          objectName: wcportalpfx
          objectType: secret
          #objectAlias: ""
          #objectVersion: ""
    tenantId: " xxxxxxxxxx"
```
**What did you expect to happen:**

-------------

nginx helm
```
helm install ingress-nginx/ingress-nginx --generate-name --namespace=portal-dev --set controller.replicaCount=2 --set controller.podLabels.aadpodidbinding=xxxxx -f - <<EOF
controller:
  extraVolumes:
      - name: secrets-store-inline
        csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "ingress-tls"   #name of the SecretProviderClass we created above
  extraVolumeMounts:
      - name: secrets-store-inline
        mountPath: "/mnt/secrets-store"
        readOnly: true
EOF
```
----------------
app Nginx conf
```
--
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portal-ingress
  namespace: portal-dev
  annotations:
    # kubernetes.io/ingress.allow-http: "false"
    # defines controller implementing this ingress resource: https://docs.microsoft.com/en-us/azure/dev-spaces/how-to/ingress-https-traefik
    # ingress.class annotation is being deprecated in Kubernetes 1.18: https://kubernetes.io/docs/concepts/services-networking/ingress/#deprecated-annotation
    # For backwards compatibility, when this annotation is set, precedence is given over the new field ingressClassName under spec.
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/affinity-mode: persistent
    #traefik.ingress.kubernetes.io/router.entrypoints: websecure
    # traefik.ingress.kubernetes.io/router.tls: "true"
    # traefik.ingress.kubernetes.io/router.tls.options: default
    # traefik.ingress.kubernetes.io/router.middlewares: gzip-compress@file
spec:
  # ingressClassName: "traefik-internal"
  tls:
  - hosts:
      - "*.e-learningportal.com"
    secretName: ingress-tls-csi    
  rules:
  - host: "*.e-learningportal.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: portal-dev
            port: 
              number: 80
```
---    -------------------------------

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Which access mode did you use to access the Azure Key Vault instance:**
[e.g. Service Principal, Pod Identity, User Assigned Managed Identity, System Assigned Managed Identity]

Ive  used  Service Principal,
**Environment:**
on any  version above Chart Version 0.0.16 doesn't generate a TSL certificate secret 
- Secrets Store CSI Driver version: (use the image tag):   1.1.0 doesn't generate a TSL certificate secret, on version 0.0.19 generates TSL secret
- Azure Key Vault provider version: (use the image tag):1.1.2 doesn't generate a TSL certificate secret, on version 0.0.12 generates TSL  
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`): 1.21.9
- Cluster type: (e.g. AKS, aks-engine, etc):AKS
