### ISSUE TITLE
Failed to watch *v1.Secret: failed to list *v1.Secret: secrets is forbidden: 

### ISSUE THREAD

**Issue by krisnuttall** [Azure/secrets-store-csi-driver-provider-azure#854]
**What steps did you take and what happened:**
New deployments started failing this morning after no configuration changes. Viewing the secrets-store-csi-driver logs reveals lots of errors such as:
W0408 17:48:13.201034 1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.0/tools/cache/reflector.go:167: failed to list *v1.Secret: secrets is forbidden: User "system:serviceaccount:kube-system:secrets-store-csi-driver" cannot list resource "secrets" in API group "" at the cluster scope
E0408 17:48:13.201073 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.0/tools/cache/reflector.go:167: Failed to watch *v1.Secret: failed to list *v1.Secret: secrets is forbidden: User "system:serviceaccount:kube-system:secrets-store-csi-driver" cannot list resource "secrets" in API group "" at the cluster scope

Problems started between 10:36 and 10:43 BST this morning.

**What did you expect to happen:**
Deploys to succeed using secrets as they did.

**Anything else you would like to add:**
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: providername
spec:
  provider: azure
  parameters:
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "[guid]"
    keyvaultName: "keyvault" # the name of the KeyVault

**Which access mode did you use to access the Azure Key Vault instance:**
User Assigned Managed Identity

**Environment:**

- Secrets Store CSI Driver version: 1.1.2
- Azure Key Vault provider version: 1.1.2
- Kubernetes version: v1.21.9 
- Cluster type: AKS 
Also tried earlier versions of k8s and csi providers.

**Comment by nilekhc** [comment]
Thanks for opening issue @krisnuttall. Seems like the role/role binding might be failing. Is sync secret and rotation enabled while installing?

**Comment by krisnuttall** [comment]
I used the default helm chart options, but also forced sync-secret to false:
```
USER-SUPPLIED VALUES:
secrets-store-csi-driver:
  syncSecret:
    enabled: false
```

**Comment by krisnuttall** [comment]
Also forced rotation to false now as well:
```
USER-SUPPLIED VALUES:          
secrets-store-csi-driver:
  enableSecretRotation: false
  syncSecret:
    enabled: false
```

**Comment by nilekhc** [comment]
When sync secrets and rotation is set to false, related role and role bindings are not installed. Could you share the SecretProviderClass which is being used in new deployments?

**Comment by krisnuttall** [comment]
here it is, but obfuscated some strings
```
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: providername
spec:
  provider: azure
  parameters:
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "guid"
    keyvaultName: "keyVaultName" # the name of the KeyVault
    cloudName: "" # [OPTIONAL available for version > 0.0.4] if not provided, azure environment will default to AzurePublicCloud
    objects: |
      array:
        - |
          objectName: DB-Key   
          objectType: secret        # object types: secret, key or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: EventMessage
          objectType: secret
          objectVersion: ""
        - |
          objectName: OAuth
          objectType: secret
          objectVersion: ""
        - |
          objectName: ConnectionString
          objectType: secret
          objectVersion: ""
    resourceGroup: "myrg"
    subscriptionId: "guid"
    tenantId: "guid" # the tenant ID of the KeyVault
  secretObjects:
    - data:
        - key: DB-Key
          objectName: DB-Key
        - key: EventMessage
          objectName: EventMessage
        - key: OAuth
          objectName: OAuth
        - key: ConnectionString
          objectName: ConnectionString
      secretName: my-secrets
      type: Opaque

```
