### ISSUE TITLE
Only last part of ssl chain is imported into k8s secret

### ISSUE THREAD

**Issue by mszczepaniuk** [Azure/secrets-store-csi-driver-provider-azure#860]
**Have you**

- [*] Read [Troubleshooting Guide](https://azure.github.io/secrets-store-csi-driver-provider-azure/troubleshooting/)
- [*] Searched on [GitHub issues](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues) and [Discussions](https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions)

**What steps did you take and what happened:**
Certificate in .pfx format is imported into Azure Key Vault. Crt part of cert taken from key vault into k8s secret contains only last part of the chain which causes some browsers to throw an error while connecting to website. Other than that certificate is imported properly and works well on e.g. Chrome browser.

**What did you expect to happen:**
Crt part of the certificate is imported in it's full form consisting of complete chain.

**Anything else you would like to add:**
Downloading cert from Azure via Azure Portal as .pem shows that certificate is still complete which causes me to believe that there is some issue while converting from .pfx to .crt.

SecretProviderClass config:
```
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{ .Values.global.secretProviderClassName }}
spec:
  provider: azure
  secretObjects:
    {{- if not .Values.global.useLetsEncrypt }}
    - data:
      - key: tls.crt
        objectName: {{ .Values.global.tlsKeyVaultName }}
      - key: tls.key
        objectName: {{ .Values.global.tlsKeyVaultName }}
      secretName: {{ index .Values "admin-portal" "tlsSecretName" }}
      type: kubernetes.io/tls
    {{- end }}
  parameters:
    keyvaultName: {{ .Values.global.keyVaultName }}
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.global.identityClientId | quote }}
    objects:  | 
      array:
        {{- if not .Values.global.useLetsEncrypt }}
        - |
          objectName: {{ .Values.global.tlsKeyVaultName }}
          objectType: secret
        {{- end }}
    tenantId: {{ .Values.global.tenantId }}

```

**Which access mode did you use to access the Azure Key Vault instance:**
[e.g. Service Principal, Pod Identity, User Assigned Managed Identity, System Assigned Managed Identity]
User-assigned Managed Identity

**Environment:**
- Secrets Store CSI Driver version: (use the image tag):
```
v1.0.0
```
- Azure Key Vault provider version: (use the image tag):
```
v1.0.0
```
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`):
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:16:05Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.9", GitCommit:"a5e4de7e277a707bd28d448bd75de58b4f1cdc22", GitTreeState:"clean", BuildDate:"2021-11-16T01:09:55Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}

VERSION      OS-IMAGE              KERNEL-VERSION      CONTAINER-RUNTIME
v1.20.9      Ubuntu 18.04.6 LTS   5.4.0-1062-azure     containerd://1.4.9+azure
v1.20.9      Ubuntu 18.04.6 LTS   5.4.0-1062-azure     containerd://1.4.9+azure
```
- Cluster type: (e.g. AKS, aks-engine, etc): 
```
AKS
```
