### ISSUE TITLE
Support for extracting JSON paths from a secret

### ISSUE THREAD

**Issue by Garbett1** [Azure/secrets-store-csi-driver-provider-azure#885]
**Extracting JSON paths from secrets**
We use JSON strings in our secret and would like to be able to configure the `SecretProviderClass` to extract the value for a specific key.

There is prior art in both [HashiCorp Vault](https://www.vaultproject.io/docs/platform/k8s/csi/configurations#secretkey) and [AWS Secret Manager](https://docs.aws.amazon.com/secretsmanager/latest/userguide/integrating_csi_driver.html) (see `jmesPath`).

I'm happy to raise a PR to add this functionality, but want to confirm what approach to extract the key would be ideal. 

HashiCorp Vault only allows specifying a key, while AWS allows an arbitrary path to extract. If I was to raise a PR adding this, which approach would be preferred? Specifying only the key is simpler but less flexible.

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): v1.1.1+
- Azure Key Vault provider version: (use the image tag): v1.1.0+
- Kubernetes version: (use `kubectl version`): 1.21.0+
- Cluster type: (e.g. AKS, aks-engine, etc): AKS

**Comment by nilekhc** [comment]
Hi @Garbett1, Thanks for opening issue. Could you describe your approach? Also, PR is always welcome. We can review implementation there as well.

**Comment by Garbett1** [comment]
Hi @nilekhc ,

Given a secret of:
```
{
  "foo": "123",
  "bar": "456"
}
```
and a `SecretProviderClass` of:
```
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-wi
spec:
  provider: azure
  parameters:
   # omitting other fields
    objects:  |
      array:
        - |
          objectName: example-secret
          objectType: secret
          jsonPath: 
              - path: foo
                objectAlias: fooThing
              - path: bar
                objectAlias: barThing
```

If I mounted the secret at `/mnt/secrets-store`, I'd expect to find two files. `fooThing` and `barThing` with the contents: `123` and `456` respectively.
