### ISSUE TITLE
unable mount Secret Provider Class

### ISSUE THREAD

**Issue by rajendar38** [Azure/secrets-store-csi-driver-provider-azure#890]
### Discussed in https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions/889

<div type='discussions-op-text'>

<sup>Originally posted by **rajendar38** May 16, 2022</sup>
Hi All ,
I am trying to integrate azure key Valut with aks cluster ,  as part of that I created  SPC and trying to mount it as volume .
I have few secrets in the key vault .

```
# This is a SecretProviderClass example using system-assigned identity to access Keyvault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-system-msi-mds
spec:
  provider: azure
  secretObjects:
  - secretName: abc -keyvault-secret
    type: Opaque
    data:
    - objectName: CLIENT-SECRET
      key: client-secret
    - objectName: META-TENANT
      key: meta-tenant
    - objectName: KEY-VAULT-NAME
      key: key-vault-name
    - objectName: DB-USER-NAME
      key: db-user-name
    - objectName: DB-SERVER-NAME
      key: db-server-name
    - objectName: DB-SCHEMA-NAME
      key: db-schema-name
    - objectName: DB-PORT
      key: db-port
    - objectName: CLIENT-SECRET
      key: client-secret
    - objectName: META-CLIENT-ID
      key: meta-client-id
    - objectName: DB-PASSWORD
      key: db-password
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"    # Set to true for using managed identity
    userAssignedIdentityID: "ab7"      # If empty, then defaults to use the system assigned identity on the VM
    keyvaultName: "MetaDataServiceKeyvault"
    cloudName: ""                   # [OPTIONAL for Azure] if not provided, azure environment will default to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: CLIENT-SECRET
          objectType: secret        
          objectVersion: ""         
        - |
          objectName: META-TENANT
          objectType: secret
          objectVersion: ""
        - |
          objectName: KEY-VAULT-NAME
          objectType: secret        
          objectVersion: ""         
        - |
          objectName: DB-USER-NAME
          objectType: secret
          objectVersion: ""
        - |
          objectName: DB-SERVER-NAME
          objectType: secret        
          objectVersion: ""         
        - |
          objectName: DB-SCHEMA-NAME
          objectType: secret
          objectVersion: ""       
        - |
          objectName: DB-PORT
          objectType: secret
          objectVersion: ""
       - |
          objectName: META-CLIENT-ID
          objectType: secret
          objectVersion: ""
      - |
          objectName: DB-PASSWORD
          objectType: secret
          objectVersion: ""
    tenantId: "6398azx"                 # the tenant ID of the KeyVault`

```
The problem is if add client Id and DB pass word to SPC , 
I am getting error `  MountVolume.SetUp failed for volume "secrets-store-inline" : rpc error: code = Unknown desc = failed to mount secrets store objects for pod mds/abc-xyz-service-589d454d6-xctdm, err: rpc error: code = Unknown desc = failed to mount objects, error: failed to yaml unmarshal objects, error: yaml: line 29: did not find expected key` 
if I remove these attributes from the SCP , it is working as expected , after so many trail and error I found this observations .  the values for these secrets 12345aff-fb6c-4a22-973b-70e4acfb71ea and Db password is normal password .
can anyone let me know what is the issue with attributes

</div>
