### ISSUE TITLE
Expose secret as env variable

### ISSUE THREAD

**Issue by bramvdklinkenberg** [Azure/secrets-store-csi-driver-provider-azure#92]
**Describe the solution you'd like**
I would like to be able to sync Key Vault secrets and expose them as an environment variables as well. As far as I know it is only possible to expose them via a volume, but a lot of applications still use environment variables (even thought that maybe not best practice).

**Anything else you would like to add:**
No

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): <latest>
- Azure Key Vault provider version: (use the image tag): <latest>
- Kubernetes version: (use `kubectl version`): <1.16.x>
- Cluster type: (e.g. AKS, aks-engine, etc): AKS

**Comment by aramase** [comment]
@bramvdklinkenberg This feature is already supported with the latest version of `secrets-store-csi-driver` and Azure Keyvault Provider.

PTAL at this doc for how to: https://github.com/kubernetes-sigs/secrets-store-csi-driver#optional-sync-with-kubernetes-secrets

Here is the azure provider sample used in the e2e:
https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/test/bats/tests/azure_synck8s_v1alpha1_secretproviderclass.yaml
and
https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/test/bats/tests/nginx-deployment-synck8s-azure.yaml

We also have this ingress controller tls sample: https://github.com/kubernetes-sigs/secrets-store-csi-driver/tree/master/sample/ingress-controller-tls

**Comment by lgmorand** [comment]
@aramase @ritazh should be definitely documented here as well, at least a small paragraph pointing to the great links you gave Anish :) 
As I remember, it was clearly a "by design" limitation for flexvolume (https://github.com/Azure/kubernetes-keyvault-flexvol/issues/28) and people would not notice this new possibility.

**Comment by ritazh** [comment]
Will definitely do that. Thanks everyone for the feedback!

**Comment by lgmorand** [comment]
@aramase small question for my own curiosity.

https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/test/bats/tests/nginx-deployment-synck8s-azure.yaml
It seems that we need the VolumeMount to be present to get it work (if not: "secret not found"). could not the ENV + Volumes part sufficient ?

I don't understand how the sample works

`apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: vault-foo-sync
spec:
  provider: vault
  secretObjects:
  - secretName: foosecret
    type: Opaque
    data: 
    - objectName: foo
      key: pwd
    - objectName: foo1
      key: username
  parameters:
    roleName: "example-role"
    vaultAddress: http://${VAULT_SERVICE_IP}:8200
    vaultSkipTLSVerify: "true"
    objects:  |
      array:
        - |
          objectPath: "/foo"
          objectName: "bar"
          objectVersion: ""
        - |
          objectPath: "/foo1"
          objectName: "bar"
          objectVersion: ""`

ObjectsName (in objects) are "bar" and "bar"  but secretObjects refer to foo and foo1. how does it do the mapping if names are not the same. Is an alias generated from the path ?

**Comment by ritazh** [comment]
The deployment yaml you linked is using 
```yaml
volumeAttributes:
  secretProviderClass: "azure-sync"
```
https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/test/bats/tests/nginx-deployment-synck8s-azure.yaml#L36

which is this file (the one you pasted is for Hashicorp Vault): https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/test/bats/tests/azure_synck8s_v1alpha1_secretproviderclass.yaml

As you can see below, the k8s secret `foosecret` is created from the content in the mounted file named `secretalias` as defined in `parameters`. 

```yaml
  - secretName: foosecret
    type: Opaque
    data: 
    - objectName: secretalias                    # name of the mounted content to sync. this could be the object name or object alias 
      key: username
  parameters:
    usePodIdentity: "false"                      # [OPTIONAL] if not provided, will default to "false"
    keyvaultName: "$KEYVAULT_NAME"               # the name of the KeyVault
    objects: |
      array:
        - |
          objectName: $SECRET_NAME
          objectType: secret                     # object types: secret, key or cert
          objectAlias: secretalias
          objectVersion: $SECRET_VERSION         # [OPTIONAL] object versions, default to latest if empty
```

**Comment by lgmorand** [comment]
I understand the links between the components, but someone just opened the same issue than my point: #99 

I successfully pinpointed the issue

- I have 1 secretProviderClass
- I have 1 pod mapping Env, but without volumeMounts property 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keyvault-app-deploy-env
  namespace: keyvault
  labels:
    app: keyvault-app-deploy-env
spec:
  replicas: 3
  selector:
    matchLabels:
      app: keyvault-app-env
  template:
    metadata:
      labels:
        app: keyvault-app-env
        aadpodidbinding: "keyvault-podidentity"
    spec:
      containers:
      - name: nginx
        image: nginx
        env:
        - name: MY_SECRET
          valueFrom:
            secretKeyRef:
              name: kv-secret
              key: my-secret
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvnam
```     


As it, it **does not work**, never. I get **CreateContainerConfigError** because secret not found

Workaround 1:
If I had volumeMounts to the same pod, it works, even if I don't plan to use it
```
volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
```

Workaround 2:
If I create another pod, using the same secretProviderClass and using volumeMounts but NOT using ENV, then both pods work properly


From my analyze, secret sync is only triggered once a volume mount is done. which does not seem natural
