### ISSUE TITLE
Support mounting certificate and private key in separate files

### ISSUE THREAD

**Issue by vaibhav1192** [Azure/secrets-store-csi-driver-provider-azure#933]
For a certificate, mount the private key and public key in separate files. Currently, CSI driver downloads the complete certificate and mounts it in a single file. This single file does not work with the non-Microsoft components. As they expect, key and cert to be provided as separate files. AKV CSI driver supports parsing AKV cert for k8s tls secret but not for the volume mounts.

EG. CSI driver can mount the three files : **/certName, /certName.key, certName.cert** for the below resource
  ```        
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: contour
  namespace: projectcontour
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"
    keyvaultName: "${KEYVAULT_NAME}"
    objects:  |
      array:
        - |
          objectName: certName
          objectType: secret
          objectVersion: ""
    tenantId: "${KEYVAULT_TENANT_ID}" 
```
We need to mount the cert & key in pem format in contour and envoy pods. Also pass the file paths in configuration.

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): v1.0.0
- Azure Key Vault provider version: (use the image tag): v1.0.0
- Kubernetes version: (use `kubectl version`): 1.22
- Cluster type: (e.g. AKS, aks-engine, etc): AKS
