### ISSUE TITLE
Volumes mounted with csi driver secrets-store.csi.k8s.io ignore securityContext.fsGroup

### ISSUE THREAD

**Issue by zioproto** [Azure/secrets-store-csi-driver-provider-azure#938]
**What steps did you take and what happened:**

I created a `SecretProviderClass`:

```
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: istio-tls
  namespace: istio-ingress
spec:
  provider: azure
  parameters:
......
```

I have a deployment where I use it:

```
        volumeMounts:
        - mountPath: /etc/istio/ingressgateway-certs
          name: ingressgateway-certs
          readOnly: true

[....CUT....]

      volumes:
      - csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: istio-tls
        name: ingressgateway-certs
```

The deployment also has a `securityContext`:

```
      securityContext:
        fsGroup: 1337
        runAsGroup: 1337
        runAsNonRoot: true
        runAsUser: 1337
```

I see the folder `/etc/istio/ingressgateway-certs` and the files created inside all have `root:root` ownership. Also the permissions `777` and it is not documented how to change the permission of the files. In a secret I would have used:

```
- name: ingressgateway-certs
        secret:
          defaultMode: 420
```

**What did you expect to happen:**

The `securityContext` should be respected when mounting the volume, and the documentation should clarify how to set the `defaultMode`.

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
Installed with the AKS addon:
```
  image: mcr.microsoft.com/oss/kubernetes-csi/livenessprobe:v2.6.0
  image: mcr.microsoft.com/oss/kubernetes-csi/csi-node-driver-registrar:v2.5.0
  image: mcr.microsoft.com/oss/kubernetes-csi/secrets-store/driver:v1.1.1.5
```

- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`):
Client Version: v1.24.2
Kustomize Version: v4.5.4
Server Version: v1.23.5
all nodes on v1.23.5

- Cluster type:  AKS
- Installation method:  [AKS managed add-on](https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver)
