### ISSUE TITLE
failed to get authorizer for keyvault client: nmi response failed with status    code: 404,

### ISSUE THREAD

**Issue by Arishb** [Azure/secrets-store-csi-driver-provider-azure#941]
error message at Daemon set pod
reason: FailedMount

message: >

  MountVolume.SetUp failed for volume "secrets-store-inline" : rpc error: code =

  Unknown desc = failed to mount secrets store objects for pod

  prometheus-collector/prometheus-collector-node-xxx, err: rpc error: code =

  Unknown desc = failed to mount objects, error: failed to get keyvault client:

  failed to get authorizer for keyvault client: nmi response failed with status

  code: 404, response body: getting assigned identities for pod

  prometheus-collector/prometheus-collector-node-5ttwd in CREATED state failed

  after 16 attempts, retry duration [5]s, error: <nil>. Check MIC pod logs for

  identity assignment error

NMI logs at that time:
I0721 01:48:19.749918       1 standard.go:179] matched identityType:0 clientid:85d9##### REDACTED #####a797 resource:https://vault.azure.net
I0721 01:48:19.758169       1 server.go:192] status (200) took 8749514 ns for req.method=GET reg.path=/host/token/ req.remote=127.0.0.1
E0721 01:49:47.841677       1 server.go:234] failed to get identities, error: getting assigned identities for pod prometheus-collector/prometheus-collector-node in CREATED state failed after 16 attempts, retry duration [5]s, error: <nil>. Check MIC pod logs for identity assignment errors
I0721 01:49:47.841725       1 server.go:192] status (404) took 80012464495 ns for req.method=GET reg.path=/host/token/ req.remote=127.0.0.1

MIC Pod Logs at that time:

I0721 01:48:29.190033       1 mic.go:1449] reconciling identity assignment for /subscriptions/somesubid/resourcegroups/managed-pod-identity-int/providers/Microsoft.ManagedIdentity/userAssignedIdentities/prom-collector-mpi-int  on node aks-userpool0-xxxx-vmss

Checked the RBAC clusteroles and clusterrolebinding of AAD in comparision to https://github.com/Azure/aad-pod-identity/blob/master/deploy/infra/deployment-rbac.yaml and everything is perfect

Checked the Roles and role binding of daemon sets as well eveything looks good

weird is that we also have the same setup for collector mounting the same CSI secret running as deployment and it works perfectly fine on the same namespace

can some one advice on what is going wrong here with the daemonset

```
# Source: prometheus-collector/templates/prometheus-collector-daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prometheus-collector-node
  namespace: prometheus-collector
  labels:
    component: prometheus-collector
spec:
  selector:
    matchLabels:
      dsName: prometheus-collector-node
  updateStrategy:
    type: RollingUpdate  
  template:
    metadata:
      labels:
        dsName: prometheus-collector-node
      annotations:
        agentVersion: "0.0.0.1"
        schema-versions: "v1"
    spec:
      serviceAccountName: prometheus-collector-serviceaccount
      containers:
        - name: prometheus-collector
          image: &collectorimagetag 
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 1
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
          env:
            - name: CLUSTER
              value: "**"  
            - name: CONTROLLER_TYPE
              value: "DaemonSet"
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONTAINER_CPU_LIMIT
              valueFrom:
                resourceFieldRef:
                  containerName: prometheus-collector
                  resource: limits.cpu
                  divisor: 1m
            - name: CONTAINER_MEMORY_LIMIT
              valueFrom:
                resourceFieldRef:
                  containerName: prometheus-collector
                  resource: limits.memory
                  divisor: 1Mi
            - name: KUBE_STATE_NAME
              value: prometheus-collector-kube-state-metrics
            - name: NODE_EXPORTER_NAME
              value: prometheus-collector-prometheus-node-exporter
            - name: NODE_EXPORTER_TARGETPORT
              value: "9100"
            - name: KUBE_STATE_VERSION
              value: "mcr.microsoft.com/oss/kubernetes/kube-state-metrics:v2.2.0"
            - name: NODE_EXPORTER_VERSION
              value: "mcr.microsoft.com/oss/prometheus/node-exporter:v1.2.2"
            - name: HELM_RELEASE_NAME
              value: "prometheus-collector"
            - name: AGENT_VERSION
              value: *collectorimagetag
            - name: MODE
              value: "advanced" # only supported mode is 'advanced', any other value will be the default/non-advance mode
            - name: WINMODE
              value: "" # WINDOWS: only supported mode is 'advanced', any other value will be the default/non-advance mode
          securityContext:
            privileged: false
          volumeMounts:
            - mountPath: /etc/config/settings/akv
              name: secrets-store-inline
              readOnly: true
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - /opt/microsoft/liveness/livenessprobe.sh
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - labelSelector:
                matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                    - linux
                  - key: type
                    operator: NotIn
                    values:
                      - virtual-kubelet
      # The following tolerations are removed for AKS, this is only required for non AKS
      tolerations:
        - operator: "Exists"
          effect: "NoSchedule"
        - operator: "Exists"
          effect: "NoExecute"
        - operator: "Exists"
          effect: "PreferNoSchedule"
      volumes:
        - name: secrets-store-inline       
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "prometheus-collector-azure-kv"
```
