### ISSUE TITLE
Pod with CSI volume does not mount when using Azure RBAC permission model on Azure Key Vault

### ISSUE THREAD

**Issue by dewolfs** [Azure/secrets-store-csi-driver-provider-azure#945]
**Have you**

- [ ] Read [Troubleshooting Guide](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/troubleshooting/): yes
- [ ] Searched on [GitHub issues](https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues) and [Discussions](https://github.com/Azure/secrets-store-csi-driver-provider-azure/discussions): yes

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

> When I deploy the secretProviderClass and deployment below in combination with an Azure Key Vault permission model "Vault access policy", everything works fine. The user-assigned identity of the AKS cluster is assigned All Secret permissions on the Key Vault resource level.
> 
> When I deploy the secretProviderClass and deployment below in combination with an Azure Key Vault permission model "Azure role-based access control", I get the error as seen below under Events.
> 
> I've tried assigning the roles Key Vault Administrator, Key Vault Secrets Office and Key vault Secrets User on the Key Vault resource level (inheritance to secrets) and also on the individual secrets level.

**SecretProviderClass.yml**

```apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-aks-csi-012-system-msi-01
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"    # Set to true for using managed identity
    userAssignedIdentityID: "66119fee-e3bd-4e69-aff5-67e167dd19cf"      # If empty, then defaults to use the system assigned identity on the VM
    keyvaultName: "kv-aks-csi-012"
    cloudName: ""                   # [OPTIONAL for Azure] if not provided, azure environment will default to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: db-user
          objectType: secret        # object types: secret, key or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: db-pass
          objectType: secret        # object types: secret, key or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
    tenantId: "f0d1d268-e79f-49c2-b61c-5ec11119b78c"                 # the tenant ID of the KeyVault
```

**Deployment.yml**

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.23.1
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - name: secrets-mount
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
        - name: secrets-mount
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kv-aks-csi-012-system-msi-01"
```

**Events**

> Events:
>   Type     Reason       Age                From               Message
>   ----     ------       ----               ----               -------
>   Normal   Scheduled    78s                default-scheduler  Successfully assigned default/nginx-deployment-7878559455-nb6h8 to aks-nodepool1-84859515-vmss000000
>   Warning  FailedMount  14s (x8 over 78s)  kubelet            MountVolume.SetUp failed for volume "secrets-mount" : rpc error: code = Unknown desc = failed to mount secrets store objects for pod default/nginx-deployment-7878559455-nb6h8, err: rpc error: code = Unknown desc = failed to mount objects, error: failed to get objectType:secret, objectName:db-user, objectVersion:: keyvault.BaseClient#GetSecret: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="Caller is not authorized to perform action on resource.\r\nIf role assignments, deny assignments or role definitions were changed recently, please observe propagation time.\r\nCaller: appid=66119fee-e3bd-4e69-aff5-67e167dd19cf;oid=19bb2ace-2297-4bfa-b357-367dc972e29b;iss=https://sts.windows.net/f0d1d268-e79f-49c2-b61c-5ec11119b78c/\r\nAction: 'Microsoft.KeyVault/vaults/secrets/getSecret/action'\r\nResource: '/subscriptions/.../resourcegroups/rg-prd-001/providers/microsoft.keyvault/vaults/kv-aks-csi-012/secrets/db-user'\r\nAssignment: (not found)\r\nVault: kv-aks-csi-012;location=germanywestcentral\r\n" InnerError={"code":"ForbiddenByRbac"}

**What did you expect to happen:**

- CSI driver works with the both Azure key vault permission models. Adopting least privilege principle allows us with the RBAC permission model to fine-grained provide access to an individual secret.
- CSI volume gets mounted and secrets are available inside the pod

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

I've waited more than 10 mins to propagate the permissions as indicated here : https://docs.microsoft.com/en-us/azure/key-vault/general/rbac-guide?tabs=azure-cli#known-limits-and-performance

**Which access mode did you use to access the Azure Key Vault instance:**
[e.g. Service Principal, Pod Identity, User Assigned Managed Identity, System Assigned Managed Identity]

> User Assigned Managed Identity

```
{
    "clientId": "66119fee-e3bd-4e69-aff5-67e167dd19cf",
    "id": "/subscriptions/...../resourcegroups/MC_rg-prd-001_aks-prd-001_germanywestcentral/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aks-prd-001-agentpool",
    "location": "germanywestcentral",
    "name": "aks-prd-001-agentpool",
    "principalId": "19bb2ace-2297-4bfa-b357-367dc972e29b",
    "resourceGroup": "MC_rg-prd-001_aks-prd-001_germanywestcentral",
    "tags": {},
    "tenantId": "....-e79f-49c2-....",
    "type": "Microsoft.ManagedIdentity/userAssignedIdentities"
  }
```

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): 

> mcr.microsoft.com/oss/kubernetes-csi/secrets-store/driver:v1.1.1.5

- Azure Key Vault provider version: (use the image tag):

> mcr.microsoft.com/oss/azure/secrets-store/provider-azure:v1.1.0

- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`): 

> v1.22.11

```kubectl get nodes -o wide
NAME                                STATUS   ROLES   AGE   VERSION    INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
aks-nodepool1-84859515-vmss000000   Ready    agent   26m   v1.22.11   10.224.0.4    <none>        Ubuntu 18.04.6 LTS   5.4.0-1085-azure   containerd://1.5.11+azure-2
```

- Cluster type: (e.g. AKS, aks-engine, etc): 

> AKS

- Installation method: ([Helm](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/getting-started/installation/#deployment-using-helm) , [Deployment yamls](https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/getting-started/installation/#using-deployment-yamls), [AKS managed add-on](https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver)):

> AKS managed add-on
