### ISSUE TITLE
Request CSI driver support in Azure Stack Hub with AD FS identity

### ISSUE THREAD

**Issue by Jeff-Chu-t** [Azure/secrets-store-csi-driver-provider-azure#998]
**Describe the solution you'd like**
We are integrating our applications in Azure Stack Hub, but there is no CSI driver support in Azure Stack Hub with AD FS identity.
We would like to request CSI driver support in Azure Stack Hub with AD FS identity.
(We have also created another related ticket: https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/980)

**Anything else you would like to add:**

**Environment:**
- Secrets Store CSI Driver version: (use the image tag): 1.2.0
- Azure Key Vault provider version: (use the image tag): 1.2.0 
- Kubernetes version: (use `kubectl version`): 1.21.10
- Cluster type: (e.g. AKS, aks-engine, etc): We would like to use aks-engine because AKS is in preview stage in Azure Stack Hub now

**Comment by aramase** [comment]
cc @jadarsie

**Comment by jadarsie** [comment]
It should be possible, I can propose something in a few days.

**Comment by Chiahung-Su** [comment]
Hi @jadarsie, may I know if there are any updates on this? Thanks.

**Comment by jadarsie** [comment]
I did not have time to validate, but while reading the code I got the impression that setting/adding parameter `tenantId: "adfs"` in the `SecretProviderClass` should work. No code changes needed.

```yaml
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: foo
spec:
  parameters:
    tenantId: "adfs"
```

I will validate as soon as I have a moment.

**Comment by Jeff-Chu-t** [comment]
Hi @jadarsie,

We have tried the solution (`tenantId: "adfs"`) in our Azure Stack environment (in ADFS identity), and there is an error
`Status Code = '400'. Response body: {"error":"invalid_request","error_description":"AADSTS900023: Specified tenant identifier 'adfs' is neither a valid DNS name, nor a valid external domain`

We also adjusted the apiVersion from `secrets-store.csi.x-k8s.io/v1` to `secrets-store.csi.x-k8s.io/v1alpha1`, and the error is the same.

For the complete error message, please refer to the following:

`MountVolume.SetUp failed for volume "backend-ssl-volume" : rpc error: code = Unknown desc = failed to mount secrets store objects for pod psd-sso-web/psd-sso-web-idp-azstack-7799598464-mcz6q, err: rpc error: code = Unknown desc = failed to mount objects, error: failed to get objectType:secret, objectName:APPGW-BED-CERT, objectVersion:: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://psd-jk3-adc2ba-common-kv.vault.adc2bal.azstack.trendmicro.com/secrets/APPGW-BED-CERT/?api-version=2016-10-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"AADSTS900023: Specified tenant identifier 'adfs' is neither a valid DNS name, nor a valid external domain.\r\nTrace ID: a5d8453f-6642-4b57-b7a5-a9fb60631100\r\nCorrelation ID: 5b7640fd-9766-457c-bb5b-8ffae4608169\r\nTimestamp: 2022-10-26 02:36:38Z","error_codes":[900023],"timestamp":"2022-10-26 02:36:38Z","trace_id":"a5d8453f-6642-4b57-b7a5-a9fb60631100","correlation_id":"5b7640fd-9766-457c-bb5b-8ffae4608169","error_uri":"[https://login.microsoftonline.com/error?code=900023"}](https://login.microsoftonline.com/error?code=900023%22%7D) Endpoint https://login.microsoftonline.com/adfs/oauth2/token?api-version=1.0`

**Comment by jadarsie** [comment]
Hopefully you did not try out the snipped as I pasted it. I was just showing were/how to add `tenantId`.

I got it to work. This what I did:

- AKS Engine cluster on Azure Stack Hub
- AD FS identity provider (`jq .tenantId -r /etc/kubernetes/azure.json` should return `adfs`)
- Key Vault created in the same ASH instance
- Secret Store CSI driver deployed with Helm
- Custom environment volumes and mounts added to the chart's values file
- Created `SecretProviderClass` resource and pod mounting the secret

```bash
cat << EOF | kubectl apply -f -
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: the-secret-provider-class
spec:
  provider: azure
  parameters:
    keyvaultName: the-keyvault
    cloudName: AzureStackCloud
    cloudEnvFileName: /etc/kubernetes/azurestackcloud.json
    objects: |
      array:
        - |
          objectType: secret
          objectName: the-secret
          resourceGroup: the-keyvault-rg
          subscriptionId: AAAAAAAA-BBBB-CCCC-DDDD-EEEEEEEEEEEE
    tenantId: "adfs"
---
kind: Pod
apiVersion: v1
metadata:
  name: nginx-secrets-store-inline
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - name: secrets-store-inline
      mountPath: /mnt/secrets-store
      readOnly: true
  nodeSelector:
    kubernetes.io/os: linux
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: the-secret-provider-class
        nodePublishSecretRef:
          # AZURE_CLIENT_ID=$(sudo jq .aadClientId -r /etc/kubernetes/azure.json)
          # AZURE_CLIENT_SECRET=$(sudo jq .aadClientSecret -r /etc/kubernetes/azure.json)
          # kubectl create secret generic secrets-store-creds --from-literal clientid=$AZURE_CLIENT_ID --from-literal clientsecret=$AZURE_CLIENT_SECRET
          name: secrets-store-creds
EOF

kubectl exec nginx-secrets-store-inline -- cat /mnt/secrets-store/the-secret
```

**Comment by aramase** [comment]
@jadarsie Once we get confirmation from other folks on the thread it works, we can add a section about this configuration required for `AzureStackHub`. WDYT?

**Comment by jadarsie** [comment]
Yep, we are in the same page, I am waiting for confirmation as well.

**Comment by FawenYo** [comment]
Hi, After testing by our members, there are still some errors. Here are the configuration files:

* configmap_csi.yaml

  ```yaml
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: csi-config
  data:
    environmentFile.json: |-
      {
        "name": "AzureStackCloud",
        "activeDirectoryEndpoint": "https://login.microsoftonline.com/",
        "keyVaultEndpoint": "{{ .Values.KV_ENDPOINT  }}",
        "keyVaultDNSSuffix": "vault.{{ .Values.AZ_FQDN  }}"
      }
  ```

* secret_db.yaml

  ```yaml
  apiVersion: secrets-store.csi.x-k8s.io/v1
  kind: SecretProviderClass
  metadata:
    name: secret-azstack
  spec:
    parameters:
      cloudEnvFileName: /cloudEnv/environmentFile.json
      cloudName: AzureStackCloud
      keyvaultName: {{ .Values.PSD_KV_NAME  }}
      objects: |
        array:
          - |
            objectName: "REDIS-PASSWORD"
            objectAlias: "store.redis.password"
            objectType: secret
            resourceGroup: "RG"
            subscriptionId: "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX" 
      tenantId: "adfs"
    provider: azure
  ```

* values_csi.yaml

  ```yaml
  linux:
    volumes:
      - name: csi-env-config
        configMap:
          name: csi-config
    volumeMounts:
      - name: csi-env-config
        mountPath: "/cloudEnv/environmentFile.json"
        subPath: "environmentFile.json"
   
  secrets-store-csi-driver:
    syncSecret:
      enabled: true
  ```

* secret_csi.yaml

  ```yaml
  apiVersion: v1
  kind: Secret
  metadata:
    name: csi-secret
    labels:
      secrets-store.csi.k8s.io/used: 'true'
  type: Opaque
  data:
    clientid: {{ .Values.CLIENT_ID | b64enc  }}
    clientsecret: {{ .Values.CLIENT_SECRET | b64enc  }}
  ```

* Deployment.yaml

  ```yaml
  ...
  - csi:
      driver: secrets-store.csi.k8s.io
      nodePublishSecretRef:
        name: csi-secret
      readOnly: true
      volumeAttributes:
        secretProviderClass: secret-azstack
    name: csi-volume
  ```

And the error message would be like...

```
MountVolume.SetUp failed for volume "csi-volume" : rpc error: code = Unknown desc = failed to mount secrets store objects for pod XXX, err: rpc error: code = Unknown desc = failed to mount objects, error: failed to get objectType:secret, objectName:REDIS-PASSWORD, objectVersion:: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://xxx-kv.vault.xxx.com/secrets/REDIS-PASSWORD/?api-version=2016-10-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"AADSTS900023: Specified tenant identifier 'adfs' is neither a valid DNS name, nor a valid external domain.\r\nTrace ID: xxx\r\nCorrelation ID: xxx\r\nTimestamp: 2022-10-27 07:16:18Z","error_codes":[900023],"timestamp":"2022-10-27 07:16:18Z","trace_id":"xxx","correlation_id":"xxx5","error_uri":"https://login.microsoftonline.com/error?code=900023"} Endpoint https://login.microsoftonline.com/adfs/oauth2/token?api-version=1.0
```

Would you please help us to solve the problem? Thanks!

**Comment by jadarsie** [comment]
Thx @FawenYo for sharing the details. I would try to updating your config map content:

```json
{
  "name": "AzureStackCloud",
  "activeDirectoryEndpoint": "https://login.microsoftonline.com/",
  "keyVaultEndpoint": "{{ .Values.KV_ENDPOINT  }}",
  "keyVaultDNSSuffix": "vault.{{ .Values.AZ_FQDN  }}"
  "tenantId": "adfs"
}
```

- there is a missing comma (`keyVaultDNSSuffix` line)
- I do not think `tenantId` is a valid value here
- `activeDirectoryEndpoint` seems invalid for a AD FS deployment, I would expect something like `https://adfs.{{ .Values.AZ_FQDN  }}`
- for the rest of values, please make sure the property values match the ones found in `/etc/kubernetes/azurestackcloud.json`

**Comment by Jeff-Chu-t** [comment]
Hi @jadarsie,
Thanks for your information; we will try and verify it in our environment.
May I ask whether my steps/understanding is correct?

- Currently I have found the file `/etc/kubernetes/azure.json` from a `kube-proxy` pod, and `jq .tenantId -r /etc/kubernetes/azure.json` has returned `adfs`
- The value of the `cloudEnvFileName` can be our customized file path (ex: `cloudEnvFileName: /cloudEnv/environmentFile.json` instead of `cloudEnvFileName: /etc/kubernetes/azurestackcloud.json`)
- Can we just copy all the content from `/etc/kubernetes/azurestackcloud.json` and paste to our customized file, or should it just need these four keys: `"name"`, `"activeDirectoryEndpoint"`, `"keyVaultEndpoint"`, and `"keyVaultDNSSuffix"`?

**Comment by jadarsie** [comment]
> - Currently I have found the file /etc/kubernetes/azure.json from a kube-proxy pod

Yes, `kube-proxy` is mounting host path `/etc/kubernetes`, the host directory where `azurestackcloud.json` is found. 

> - The value of the cloudEnvFileName can be our customized file path (ex: cloudEnvFileName: /cloudEnv/environmentFile.json instead of cloudEnvFileName: /etc/kubernetes/azurestackcloud.json)

I usually go with `/etc/kubernetes/azurestackcloud.json`, I recommend using that path. If you must change it, the set env variable `AZURE_ENVIRONMENT_FILEPATH`.

> - Can we just copy all the content from /etc/kubernetes/azurestackcloud.json (also got from the kube-proxy pod), and paste to our customized file, or should we just leave these four keys: "name", "activeDirectoryEndpoint", "keyVaultEndpoint", and "keyVaultDNSSuffix"?

You can, you do not have to.

**Comment by jadarsie** [comment]
> There may be a way to change it by setting env variable AZURE_ENVIRONMENT_FILEPATH, but I never tried that myself.

Just checked the code. The driver will set `AZURE_ENVIRONMENT_FILEPATH` to `parameters.cloudEnvFileName`. So, you are fine as long as `parameters.cloudEnvFileName` is mounted.

**Comment by FawenYo** [comment]
> Thx @FawenYo for sharing the details. I would try updating your config map content:
> 
> ```json
> {
>   "name": "AzureStackCloud",
>   "activeDirectoryEndpoint": "https://login.microsoftonline.com/",
>   "keyVaultEndpoint": "{{ .Values.KV_ENDPOINT  }}",
>   "keyVaultDNSSuffix": "vault.{{ .Values.AZ_FQDN  }}"
>   "tenantId": "adfs"
> }
> ```
> 
> * there is a missing comma (`keyVaultDNSSuffix` line)
> * I do not think `tenantId` is a valid value here
> * `activeDirectoryEndpoint` seems invalid for a AD FS deployment, I would expect something like `https://adfs.{{ .Values.AZ_FQDN  }}`
> * for the rest of values, please make sure the property values match the ones found in `/etc/kubernetes/azurestackcloud.json`

OK, We'll test this. Thanks for your help!

**Comment by FawenYo** [comment]
Hi, after testing, there are still errors:

```
MountVolume.SetUp failed for volume "csi-volume" : rpc error: code = Unknown desc = failed to mount secrets store objects for pod NAMESPACE/pPOD, err: rpc error: code = Unknown desc = failed to mount objects, error: failed to get objectType:secret, objectName:REDIS-PASSWORD, objectVersion:: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://KV.vault.DOMAIN.com/secrets/REDIS-PASSWORD/?api-version=2016-10-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"AADSTS900023: Specified tenant identifier 'adfs' is neither a valid DNS name, nor a valid external domain.\r\nTrace ID: XXX\r\nCorrelation ID: XXX\r\nTimestamp: XXX","error_codes":[900023],"timestamp":"2022-10-28 13:31:30Z","trace_id":"XXX","correlation_id":"XXX","error_uri":"https://login.microsoftonline.com/error?code=900023"} Endpoint https://login.microsoftonline.com/adfs/oauth2/token?api-version=1.0
```

Here is my modification 

* configmap_csi.yaml

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: csi-config
data:
  environmentFile.json: |-
    {
      "name": "AzureStackCloud",
      "activeDirectoryEndpoint": "https://adfs.{{ .Values.AZ_FQDN }}",
      "keyVaultEndpoint": "{{ .Values.KV_ENDPOINT  }}",
      "keyVaultDNSSuffix": "vault.{{ .Values.AZ_FQDN  }}"
    }
```

* values_csi.yaml

```
linux:
  volumes:
    - name: psd-sso-web-csi-env-config
      configMap:
        name: psd-sso-web-csi-config
    - name: sslcerts
      hostPath:
        path: "/etc/ssl/certs"
  volumeMounts:
    - name: psd-sso-web-csi-env-config
      mountPath: "/cloudEnv/environmentFile.json"
      subPath: "environmentFile.json"
    - name: sslcerts
      mountPath: "/etc/ssl/certs"
      readOnly: true
 
secrets-store-csi-driver:
  syncSecret:
    enabled: true
```

Hope this can help you debug. Thanks!

**Comment by jadarsie** [comment]
> Endpoint https://login.microsoftonline.com/adfs/oauth2/token?api-version=1.0

This seems to indicate that the expected `activeDirectoryEndpoint` is still not used. Try mounting the host file instead of the config map.

To increase verbosity, add this to the `csi-secrets-store-provider-azure` daemonset container.

```yaml
env:
- name: AZURE_GO_SDK_LOG_LEVEL
  value: DEBUG
```

This is a simplified version of what I see

```

INFO: REQUEST: POST https://adfs.THE-FQDN/adfs/oauth2/token?api-version=1.0
Content-Type: application/x-www-form-urlencoded
**REDACTED** authentication body

INFO: RESPONSE: 200 https://adfs.THE-FQDN/adfs/oauth2/token?api-version=1.0
Content-Type: application/json;charset=UTF-8
**REDACTED** authentication body

INFO: REQUEST: GET https://THE-KV.vault.THE-FQDN/secrets/THE-SECRET/?api-version=2016-10-01
Authorization: **REDACTED**

INFO: RESPONSE: 200 https://THE-KV.vault.THE-FQDN/secrets/THE-SECRET/?api-version=2016-10-01
Content-Type: application/json; charset=utf-8
{
    "value": "**REDACTED**",
    "id": "https://THE-KV.vault.THE-FQDN/secrets/THE-SECRET/39d2e0fb612443379281e8caa8f1fd38",
    "attributes": {
        "enabled": true,
        "created": 1666761200,
        "updated": 1666761200,
        "recoveryLevel": "Purgeable"
    }
}
```
